# =============================================================================
# Plik: pulseaudio.conf
# =============================================================================

load-module module-native-protocol-unix
load-module module-suspend-on-idle timeout=86400
load-module module-always-sink

# Bazowy null-sink (ukryty, uzywany jako master dla virtual-sink)
load-module module-null-sink sink_name=null_base sink_properties=device.description="null"
# Virtual-sink (monitor DZIALA, w przeciwienstwie do null-sink)
load-module module-virtual-sink sink_name=speaker master=null_base sink_properties=device.description="Speaker"

# TTS
load-module module-null-sink sink_name=tts sink_properties=device.description="TTS"

# Bot mikrofon
load-module module-remap-source master=tts.monitor source_name=bot_mic source_properties=device.description="Bot-Microphone"

set-default-sink speaker
set-default-source bot_mic
