# ===== File: sampling.mojo — on-GPU token sampling over f32 logits =====
# Replaces the per-token vocab-sized logits download with a 8-byte result:
# argmax for greedy decoding and a top-k/top-p/min-p categorical draw for
# temperature sampling. The draw uses a counter-based hash on (seed, step),
# so a request replays deterministically without any device-resident RNG
# state. Repetition penalty runs as a separate in-place pass over the logits
# buffer (the buffer is regenerated by the decode graph every step).

from std.gpu import block_dim, block_idx, thread_idx, global_idx
from std.gpu.sync import barrier
from std.gpu.memory import AddressSpace
from std.memory import stack_allocation
from std.math import exp, log

comptime SAMPLE_BLOCK = 256
# Per-block slice staged in shared memory by topk_partial_f32 (16 KiB f32).
comptime SAMPLE_CHUNK = 4096
comptime MAX_TOPK = 64
# Grid ceiling for topk_partial; bounds the final merge input at
# MAX_SAMPLE_BLOCKS * MAX_TOPK pairs and the supported vocab at
# MAX_SAMPLE_BLOCKS * SAMPLE_CHUNK = 262144 (covers every current model).
comptime MAX_SAMPLE_BLOCKS = 64
comptime MAX_PARTS = MAX_SAMPLE_BLOCKS * MAX_TOPK
# Lowest finite f32: masks selected entries without NaN semantics.
comptime NEG_INF: Float32 = -3.4028235e38


def _block_argmax(v: Float32, idx: Int) -> Tuple[Float32, Int]:
    # Full-block (value, index) max via a shared-memory tree; ties resolve to
    # the LOWEST index so greedy output is reproducible against a sequential
    # CPU scan. Every thread receives the winner. Block dim must be a power
    # of two (launchers always use SAMPLE_BLOCK).
    sv = stack_allocation[SAMPLE_BLOCK, Float32, address_space = AddressSpace.SHARED]()
    si = stack_allocation[SAMPLE_BLOCK, Int32, address_space = AddressSpace.SHARED]()
    tid = Int(thread_idx.x)
    # Entry barrier: back-to-back calls reuse the same shared slots.
    barrier()
    sv[tid] = v
    si[tid] = Int32(idx)
    barrier()
    var off = Int(block_dim.x) // 2
    while off > 0:
        if tid < off:
            ov = sv[tid + off]
            oi = si[tid + off]
            if ov > sv[tid] or (ov == sv[tid] and Int(oi) < Int(si[tid])):
                sv[tid] = ov
                si[tid] = oi
        barrier()
        off //= 2
    return (sv[0], Int(si[0]))


def _rand_u01(seed: UInt64, step: UInt64) -> Float32:
    # splitmix64 finalizer over a (seed, step) counter: stateless, so the
    # draw for a given request seed and decode step is deterministic.
    var z = seed + (step + 1) * UInt64(0x9E3779B97F4A7C15)
    z = (z ^ (z >> 30)) * UInt64(0xBF58476D1CE4E5B9)
    z = (z ^ (z >> 27)) * UInt64(0x94D049BB133111EB)
    z = z ^ (z >> 31)
    return Float32(Int(z >> 40)) / Float32(1 << 24)


def penalize_f32(
    logits: UnsafePointer[Float32, MutAnyOrigin],
    ids: UnsafePointer[Int32, MutAnyOrigin],
    n_ids: Int,
    penalty: Float32,
):
    """In-place repetition penalty over `n_ids` DISTINCT token ids (host
    deduplicates so the penalty never compounds). Mirrors the CPU rule:
    positive logits divide, non-positive multiply."""
    i = Int(global_idx.x)
    if i >= n_ids:
        return
    t = Int(ids[i])
    l = logits[t]
    if l > 0.0:
        logits[t] = l / penalty
    else:
        logits[t] = l * penalty


def _penalized_logit(
    logit: Float32,
    count: Int,
    repetition_penalty: Float32,
    frequency_penalty: Float32,
    presence_penalty: Float32,
) -> Float32:
    var value = logit
    if repetition_penalty != 1.0:
        if value > 0.0:
            value /= repetition_penalty
        else:
            value *= repetition_penalty
    return value - presence_penalty - frequency_penalty * Float32(count)


def penalize_histogram_f32(
    logits: UnsafePointer[Float32, MutAnyOrigin],
    ids: UnsafePointer[Int32, MutAnyOrigin],
    counts: UnsafePointer[Int32, MutAnyOrigin],
    n_ids: Int,
    vocab: Int,
    repetition_penalty: Float32,
    frequency_penalty: Float32,
    presence_penalty: Float32,
):
    """Nakłada kary z histogramu unikalnych identyfikatorów tokenów."""
    item = Int(global_idx.x)
    if item >= n_ids:
        return
    token = Int(ids[item])
    if token < 0 or token >= vocab:
        return
    logits[token] = _penalized_logit(
        logits[token],
        Int(counts[item]),
        repetition_penalty,
        frequency_penalty,
        presence_penalty,
    )


def penalized_argmax_f32(
    out_id: UnsafePointer[Int32, MutAnyOrigin],
    out_lp: UnsafePointer[Float32, MutAnyOrigin],
    logits: UnsafePointer[Float32, MutAnyOrigin],
    ids: UnsafePointer[Int32, MutAnyOrigin],
    counts: UnsafePointer[Int32, MutAnyOrigin],
    n_ids: Int,
    vocab: Int,
    repetition_penalty: Float32,
    frequency_penalty: Float32,
    presence_penalty: Float32,
):
    """Nakłada kary z histogramu i wybiera greedy w jednym launchu."""
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)
    var item = tid
    while item < n_ids:
        history_token = Int(ids[item])
        if history_token >= 0 and history_token < vocab:
            logits[history_token] = _penalized_logit(
                logits[history_token],
                Int(counts[item]),
                repetition_penalty,
                frequency_penalty,
                presence_penalty,
            )
        item += bd
    barrier()

    var best_value = NEG_INF
    var best_id = 0x7FFFFFFF
    var scan_token = tid
    while scan_token < vocab:
        current_value = logits[scan_token]
        if current_value != current_value or current_value < NEG_INF:
            current_value = NEG_INF
        if best_id == 0x7FFFFFFF or current_value > best_value or (current_value == best_value and scan_token < best_id):
            best_value = current_value
            best_id = scan_token
        scan_token += bd
    (_, winner) = _block_argmax(best_value, best_id)
    if tid == 0:
        out_id[0] = Int32(winner)
        out_lp[0] = 0.0


def penalized_topk_f32(
    out_id: UnsafePointer[Int32, MutAnyOrigin],
    out_lp: UnsafePointer[Float32, MutAnyOrigin],
    logits: UnsafePointer[Float32, MutAnyOrigin],
    ids: UnsafePointer[Int32, MutAnyOrigin],
    counts: UnsafePointer[Int32, MutAnyOrigin],
    n_ids: Int,
    vocab: Int,
    repetition_penalty: Float32,
    frequency_penalty: Float32,
    presence_penalty: Float32,
    k: Int,
    inv_t: Float32,
    top_p: Float32,
    min_p: Float32,
    seed: UInt64,
    step: UInt64,
):
    """Nakłada kary i wykonuje losowanie top-k w jednym launchu."""
    topv = stack_allocation[MAX_TOPK, Float32, address_space = AddressSpace.SHARED]()
    topi = stack_allocation[MAX_TOPK, Int32, address_space = AddressSpace.SHARED]()
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)
    var item = tid
    while item < n_ids:
        history_token = Int(ids[item])
        if history_token >= 0 and history_token < vocab:
            logits[history_token] = _penalized_logit(
                logits[history_token],
                Int(counts[item]),
                repetition_penalty,
                frequency_penalty,
                presence_penalty,
            )
        item += bd
    barrier()

    for rank in range(k):
        var best_value = NEG_INF
        var best_id = 0x7FFFFFFF
        var scan_token = tid
        while scan_token < vocab:
            var selected = False
            for previous in range(rank):
                if scan_token == Int(topi[previous]):
                    selected = True
            if not selected:
                current_value = logits[scan_token]
                if current_value != current_value or current_value < NEG_INF:
                    current_value = NEG_INF
                if best_id == 0x7FFFFFFF or current_value > best_value or (current_value == best_value and scan_token < best_id):
                    best_value = current_value
                    best_id = scan_token
            scan_token += bd
        (winner_value, winner_id) = _block_argmax(best_value, best_id)
        if tid == 0:
            topv[rank] = winner_value
            topi[rank] = Int32(winner_id)
        barrier()

    if tid != 0:
        return
    if topv[0] == NEG_INF:
        out_id[0] = topi[0]
        out_lp[0] = 0.0
        return
    maximum = topv[0] * inv_t
    var total: Float32 = 0.0
    for rank in range(k):
        probability = exp(topv[rank] * inv_t - maximum)
        topv[rank] = probability
        total += probability
    for rank in range(k):
        topv[rank] /= total

    var candidates = k
    if min_p > 0.0:
        floor = min_p * topv[0]
        var keep = 0
        while keep < k and topv[keep] >= floor:
            keep += 1
        if keep == 0:
            out_id[0] = topi[0]
            out_lp[0] = log(topv[0])
            return
        candidates = keep
    if top_p < 1.0:
        var cumulative: Float32 = 0.0
        var cut = candidates
        for rank in range(candidates):
            cumulative += topv[rank]
            if cumulative >= top_p:
                cut = rank + 1
                break
        candidates = cut

    var surviving_total: Float32 = 0.0
    for rank in range(candidates):
        surviving_total += topv[rank]
    var draw = _rand_u01(seed, step) * surviving_total
    var chosen = candidates - 1
    for rank in range(candidates):
        draw -= topv[rank]
        if draw <= 0.0:
            chosen = rank
            break
    out_id[0] = topi[chosen]
    out_lp[0] = log(topv[chosen])


def argmax_partial_f32(
    logits: UnsafePointer[Float32, MutAnyOrigin],
    part_vals: UnsafePointer[Float32, MutAnyOrigin],
    part_idx: UnsafePointer[Int32, MutAnyOrigin],
    n: Int,
    chunk: Int,
):
    """Pass 1 of greedy argmax: each block reduces its `chunk`-sized slice of
    the logits to one (value, index) pair. Grid.x = ceil(n / chunk)."""
    base = Int(block_idx.x) * chunk
    var bv = NEG_INF
    var bi = 0x7FFFFFFF
    var i = base + Int(thread_idx.x)
    end = min(base + chunk, n)
    while i < end:
        v = logits[i]
        if v != v or v < NEG_INF:
            v = NEG_INF
        if bi == 0x7FFFFFFF or v > bv or (v == bv and i < bi):
            bv = v
            bi = i
        i += Int(block_dim.x)
    (mv, mi) = _block_argmax(bv, bi)
    if Int(thread_idx.x) == 0:
        part_vals[Int(block_idx.x)] = mv
        part_idx[Int(block_idx.x)] = Int32(mi)


def argmax_final_f32(
    out_id: UnsafePointer[Int32, MutAnyOrigin],
    out_lp: UnsafePointer[Float32, MutAnyOrigin],
    part_vals: UnsafePointer[Float32, MutAnyOrigin],
    part_idx: UnsafePointer[Int32, MutAnyOrigin],
    n_parts: Int,
):
    """Pass 2: one block reduces the per-block partials to the global argmax.
    Greedy has probability 1 by definition, so the logprob slot is 0."""
    var bv = NEG_INF
    var bi = 0x7FFFFFFF
    var i = Int(thread_idx.x)
    while i < n_parts:
        v = part_vals[i]
        t = Int(part_idx[i])
        if bi == 0x7FFFFFFF or v > bv or (v == bv and t < bi):
            bv = v
            bi = t
        i += Int(block_dim.x)
    (_, mi) = _block_argmax(bv, bi)
    if Int(thread_idx.x) == 0:
        out_id[0] = Int32(mi)
        out_lp[0] = 0.0


def topk_partial_f32(
    logits: UnsafePointer[Float32, MutAnyOrigin],
    part_vals: UnsafePointer[Float32, MutAnyOrigin],
    part_idx: UnsafePointer[Int32, MutAnyOrigin],
    n: Int,
    chunk: Int,
    k: Int,
):
    """Pass 1 of the categorical draw: each block stages its slice
    (chunk <= SAMPLE_CHUNK) in shared memory and extracts its local top-k by
    k rounds of block-argmax with -inf masking. Output pairs land descending
    at part[block * k .. block * k + k]. Grid.x = ceil(n / chunk)."""
    sm = stack_allocation[SAMPLE_CHUNK, Float32, address_space = AddressSpace.SHARED]()
    selected = stack_allocation[SAMPLE_CHUNK, UInt8, address_space = AddressSpace.SHARED]()
    blk = Int(block_idx.x)
    base = blk * chunk
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)

    var s = tid
    while s < chunk:
        gi = base + s
        if gi < n:
            value = logits[gi]
            if value != value or value < NEG_INF:
                value = NEG_INF
            sm[s] = value
        else:
            sm[s] = NEG_INF
        selected[s] = 0
        s += bd
    barrier()

    for r in range(k):
        var bv = NEG_INF
        var bs = 0x7FFFFFFF
        s = tid
        while s < chunk:
            v = sm[s]
            if selected[s] == 0 and (bs == 0x7FFFFFFF or v > bv or (v == bv and s < bs)):
                bv = v
                bs = s
            s += bd
        (mv, ms) = _block_argmax(bv, bs)
        if tid == 0:
            part_vals[blk * k + r] = mv
            part_idx[blk * k + r] = Int32(base + ms)
            selected[ms] = 1
        barrier()


def topk_final_f32(
    out_id: UnsafePointer[Int32, MutAnyOrigin],
    out_lp: UnsafePointer[Float32, MutAnyOrigin],
    part_vals: UnsafePointer[Float32, MutAnyOrigin],
    part_idx: UnsafePointer[Int32, MutAnyOrigin],
    n_parts: Int,
    k: Int,
    inv_t: Float32,
    top_p: Float32,
    min_p: Float32,
    seed: UInt64,
    step: UInt64,
):
    """Pass 2: one block merges the per-block partial top-k lists into the
    global top-k, then thread 0 replays the CPU sampler's pipeline over the
    <= MAX_TOPK survivors: temperature softmax, min-p floor, top-p cut, and
    the counter-hash categorical draw. Emits the token id and its logprob
    within the top-k softmax."""
    sv = stack_allocation[MAX_PARTS, Float32, address_space = AddressSpace.SHARED]()
    si = stack_allocation[MAX_PARTS, Int32, address_space = AddressSpace.SHARED]()
    selected = stack_allocation[MAX_PARTS, UInt8, address_space = AddressSpace.SHARED]()
    topv = stack_allocation[MAX_TOPK, Float32, address_space = AddressSpace.SHARED]()
    topi = stack_allocation[MAX_TOPK, Int32, address_space = AddressSpace.SHARED]()
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)

    var s = tid
    while s < n_parts:
        sv[s] = part_vals[s]
        si[s] = part_idx[s]
        selected[s] = 0
        s += bd
    barrier()

    # Global top-k selection: k rounds over the merged pairs. Value ties
    # resolve by slot (deterministic; pass 1 already orders slots by
    # ascending token id within a block).
    for r in range(k):
        var bv = NEG_INF
        var bs = 0x7FFFFFFF
        s = tid
        while s < n_parts:
            v = sv[s]
            if selected[s] == 0 and (bs == 0x7FFFFFFF or v > bv or (v == bv and s < bs)):
                bv = v
                bs = s
            s += bd
        (mv, ms) = _block_argmax(bv, bs)
        if tid == 0:
            topv[r] = mv
            topi[r] = si[ms]
            selected[ms] = 1
        barrier()

    if tid != 0:
        return

    if topv[0] == NEG_INF:
        out_id[0] = topi[0]
        out_lp[0] = 0.0
        return

    # Candidates are sorted descending, so probabilities after the softmax
    # are non-increasing — min-p keeps a prefix and top-p cuts a prefix,
    # exactly like the CPU path's sorted-candidate logic.
    m = topv[0] * inv_t
    var total: Float32 = 0.0
    for j in range(k):
        p = exp(topv[j] * inv_t - m)
        topv[j] = p
        total += p
    for j in range(k):
        topv[j] /= total

    var n_c = k
    if min_p > 0.0:
        floor = min_p * topv[0]
        var keep = 0
        while keep < k and topv[keep] >= floor:
            keep += 1
        if keep == 0:
            # Numerical edge: fall back to greedy like the CPU sampler.
            out_id[0] = topi[0]
            out_lp[0] = log(topv[0])
            return
        n_c = keep

    if top_p < 1.0:
        var cum: Float32 = 0.0
        var cut = n_c
        for j in range(n_c):
            cum += topv[j]
            if cum >= top_p:
                cut = j + 1
                break
        n_c = cut

    var remaining: Float32 = 0.0
    for j in range(n_c):
        remaining += topv[j]
    var r = _rand_u01(seed, step) * remaining
    var chosen = n_c - 1
    for j in range(n_c):
        r -= topv[j]
        if r <= 0.0:
            chosen = j
            break
    out_id[0] = topi[chosen]
    out_lp[0] = log(topv[chosen])


def penalize_batched_f32(
    logits: UnsafePointer[Float32, MutAnyOrigin],
    vocab: Int,
    ids: UnsafePointer[Int32, MutAnyOrigin],
    counts: UnsafePointer[Int32, MutAnyOrigin],
    offsets: UnsafePointer[Int32, MutAnyOrigin],
    penalties: UnsafePointer[Float32, MutAnyOrigin],
    frequency_penalties: UnsafePointer[Float32, MutAnyOrigin],
    presence_penalties: UnsafePointer[Float32, MutAnyOrigin],
):
    """Nakłada kary z histogramów na każdy wiersz batcha."""
    seq = Int(block_idx.x)
    base = seq * vocab
    start = Int(offsets[seq])
    end = Int(offsets[seq + 1])
    pen = penalties[seq]
    frequency = frequency_penalties[seq]
    presence = presence_penalties[seq]
    bd = Int(block_dim.x)
    var i = start + Int(thread_idx.x)
    while i < end:
        t = Int(ids[i])
        if t >= 0 and t < vocab:
            logits[base + t] = _penalized_logit(
                logits[base + t], Int(counts[i]), pen, frequency, presence
            )
        i += bd


def argmax_batched_f32(
    out_ids: UnsafePointer[Int32, MutAnyOrigin],
    logits: UnsafePointer[Float32, MutAnyOrigin],
    vocab: Int,
):
    """Batched greedy argmax over `logits` ([n_seqs, vocab]). One block per
    sequence scans its whole row; ties resolve to the lowest index, matching
    the single-row argmax_partial/argmax_final pair. Grid.x = n_seqs, block
    SAMPLE_BLOCK. out_ids[seq] receives the winning token id."""
    seq = Int(block_idx.x)
    base = seq * vocab
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)
    var bv = NEG_INF
    var bi = 0x7FFFFFFF
    var i = tid
    while i < vocab:
        v = logits[base + i]
        if v != v or v < NEG_INF:
            v = NEG_INF
        if bi == 0x7FFFFFFF or v > bv or (v == bv and i < bi):
            bv = v
            bi = i
        i += bd
    (_, mi) = _block_argmax(bv, bi)
    if tid == 0:
        out_ids[seq] = Int32(mi)


def topk_batched_f32(
    out_ids: UnsafePointer[Int32, MutAnyOrigin],
    logits: UnsafePointer[Float32, MutAnyOrigin],
    vocab: Int,
    k_arr: UnsafePointer[Int32, MutAnyOrigin],
    inv_t_arr: UnsafePointer[Float32, MutAnyOrigin],
    top_p_arr: UnsafePointer[Float32, MutAnyOrigin],
    min_p_arr: UnsafePointer[Float32, MutAnyOrigin],
    seed_arr: UnsafePointer[UInt64, MutAnyOrigin],
    step_arr: UnsafePointer[UInt64, MutAnyOrigin],
):
    """Batched categorical draw over `logits` ([n_seqs, vocab]) with per-seq
    params. One block per sequence extracts its top-k by k rounds of
    full-row block-argmax with in-place NEG_INF masking (the logits buffer is
    regenerated every step), then thread 0 replays the exact softmax /
    min-p / top-p / counter-hash pipeline of topk_final_f32. Value ties
    resolve to the lowest token id, so the survivors and their order match the
    single-row two-pass path bit-for-bit. Grid.x = n_seqs, block SAMPLE_BLOCK."""
    topv = stack_allocation[MAX_TOPK, Float32, address_space = AddressSpace.SHARED]()
    topi = stack_allocation[MAX_TOPK, Int32, address_space = AddressSpace.SHARED]()
    seq = Int(block_idx.x)
    base = seq * vocab
    tid = Int(thread_idx.x)
    bd = Int(block_dim.x)
    k = Int(k_arr[seq])
    if k > MAX_TOPK:
        k = MAX_TOPK
    if k > vocab:
        k = vocab

    for r in range(k):
        var bv = NEG_INF
        var bi = 0x7FFFFFFF
        var i = tid
        while i < vocab:
            v = logits[base + i]
            var selected = False
            for previous in range(r):
                if i == Int(topi[previous]):
                    selected = True
            if not selected:
                if v != v or v < NEG_INF:
                    v = NEG_INF
                if bi == 0x7FFFFFFF or v > bv or (v == bv and i < bi):
                    bv = v
                    bi = i
            i += bd
        (mv, mi) = _block_argmax(bv, bi)
        if tid == 0:
            topv[r] = mv
            topi[r] = Int32(mi)
        barrier()

    if tid != 0:
        return

    if topv[0] == NEG_INF:
        out_ids[seq] = topi[0]
        return

    inv_t = inv_t_arr[seq]
    top_p = top_p_arr[seq]
    min_p = min_p_arr[seq]
    m = topv[0] * inv_t
    var total: Float32 = 0.0
    for j in range(k):
        p = exp(topv[j] * inv_t - m)
        topv[j] = p
        total += p
    for j in range(k):
        topv[j] /= total

    var n_c = k
    if min_p > 0.0:
        floor = min_p * topv[0]
        var keep = 0
        while keep < k and topv[keep] >= floor:
            keep += 1
        if keep == 0:
            out_ids[seq] = topi[0]
            return
        n_c = keep

    if top_p < 1.0:
        var cum: Float32 = 0.0
        var cut = n_c
        for j in range(n_c):
            cum += topv[j]
            if cum >= top_p:
                cut = j + 1
                break
        n_c = cut

    var remaining: Float32 = 0.0
    for j in range(n_c):
        remaining += topv[j]
    var r = _rand_u01(seed_arr[seq], step_arr[seq]) * remaining
    var chosen = n_c - 1
    for j in range(n_c):
        r -= topv[j]
        if r <= 0.0:
            chosen = j
            break
    out_ids[seq] = topi[chosen]
