// =============================================================================
// File: protocol/ui/schema/data_unions.rs — tagged-union schema (auto-generated)
// Generated by scripts/gen_unions.py from manual `Encode`/`Decode` impls.
// DO NOT EDIT BY HAND — re-run the generator after enum edits.
// =============================================================================

use super::types::{FieldMeta, UnionMeta, VariantMeta};

pub const RESUMESTATUS_UNION: UnionMeta = UnionMeta {
    name: "ResumeStatus",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Fresh",
            wire_kind: "fresh",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Resumed",
            wire_kind: "resumed",
            fields: &[
                FieldMeta { key: 0, name: "mode", wire: "Enum<ResumeMode>", required: true, default: None },
                FieldMeta { key: 1, name: "next_msg_id", wire: "u64", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Rejected",
            wire_kind: "rejected",
            fields: &[
                FieldMeta { key: 0, name: "reason", wire: "tstr", required: true, default: None },
            ],
        },
    ],
};

pub const REJECTREASON_UNION: UnionMeta = UnionMeta {
    name: "RejectReason",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "VersionMismatch",
            wire_kind: "version_mismatch",
            fields: &[
                FieldMeta { key: 0, name: "supported", wire: "Array<u16>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "AuthRequired",
            wire_kind: "auth_required",
            fields: &[
                FieldMeta { key: 0, name: "method", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "AuthInvalid",
            wire_kind: "auth_invalid",
            fields: &[],
        },
        VariantMeta {
            rust_name: "AuthExpired",
            wire_kind: "auth_expired",
            fields: &[],
        },
        VariantMeta {
            rust_name: "OriginBlocked",
            wire_kind: "origin_blocked",
            fields: &[],
        },
        VariantMeta {
            rust_name: "CapabilityRequired",
            wire_kind: "capability_required",
            fields: &[
                FieldMeta { key: 0, name: "capability", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "RateLimited",
            wire_kind: "rate_limited",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Maintenance",
            wire_kind: "maintenance",
            fields: &[],
        },
        VariantMeta {
            rust_name: "ServerOverloaded",
            wire_kind: "server_overloaded",
            fields: &[],
        },
    ],
};

pub const RATELIMITSCOPE_UNION: UnionMeta = UnionMeta {
    name: "RateLimitScope",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Global",
            wire_kind: "global",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Channel",
            wire_kind: "channel",
            fields: &[
                FieldMeta { key: 0, name: "channel", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Action",
            wire_kind: "action",
            fields: &[
                FieldMeta { key: 0, name: "action_id", wire: "tstr", required: true, default: None },
            ],
        },
    ],
};

pub const ACTIONSTATUS_UNION: UnionMeta = UnionMeta {
    name: "ActionStatus",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Ok",
            wire_kind: "ok",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Rejected",
            wire_kind: "rejected",
            fields: &[
                FieldMeta { key: 0, name: "reason", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "error_code", wire: "u16", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "PermissionDenied",
            wire_kind: "permission_denied",
            fields: &[
                FieldMeta { key: 0, name: "required_permission", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "RateLimited",
            wire_kind: "rate_limited",
            fields: &[
                FieldMeta { key: 0, name: "retry_after_ms", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "ValidationFailed",
            wire_kind: "validation_failed",
            fields: &[
                FieldMeta { key: 0, name: "field_errors", wire: "Array<Inline<FieldError>>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Error",
            wire_kind: "error",
            fields: &[
                FieldMeta { key: 0, name: "error_code", wire: "u16", required: true, default: None },
                FieldMeta { key: 1, name: "message", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Redirected",
            wire_kind: "redirected",
            fields: &[
                FieldMeta { key: 0, name: "to_action_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "params", wire: "Array<Inline<ParamEntry>>", required: true, default: None },
            ],
        },
    ],
};

pub const PATHSEGMENT_UNION: UnionMeta = UnionMeta {
    name: "PathSegment",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Key",
            wire_kind: "key",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Index",
            wire_kind: "index",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
    ],
};

pub const BINDREF_UNION: UnionMeta = UnionMeta {
    name: "BindRef",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Literal",
            wire_kind: "literal",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Bound",
            wire_kind: "bound",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
    ],
};

pub const BINDSPEC_UNION: UnionMeta = UnionMeta {
    name: "BindSpec",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Text",
            wire_kind: "text",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "format", wire: "Option<Inline<ValueFormat>>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Attr",
            wire_kind: "attr",
            fields: &[
                FieldMeta { key: 0, name: "name", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "ClassToggle",
            wire_kind: "class_toggle",
            fields: &[
                FieldMeta { key: 0, name: "class_name", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 2, name: "negate", wire: "bool", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Show",
            wire_kind: "show",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "negate", wire: "bool", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "List",
            wire_kind: "list",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "item_template_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 2, name: "key_field", wire: "Option<tstr>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "TwoWay",
            wire_kind: "two_way",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
    ],
};

pub const FORMVALIDATOR_UNION: UnionMeta = UnionMeta {
    name: "FormValidator",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "AllRequired",
            wire_kind: "all_required",
            fields: &[
                FieldMeta { key: 0, name: "field_ids", wire: "Array<tstr>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "AnyRequired",
            wire_kind: "any_required",
            fields: &[
                FieldMeta { key: 0, name: "field_ids", wire: "Array<tstr>", required: true, default: None },
                FieldMeta { key: 1, name: "error_message", wire: "BindRef", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Match",
            wire_kind: "match",
            fields: &[
                FieldMeta { key: 0, name: "field_a", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "field_b", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Custom",
            wire_kind: "custom",
            fields: &[
                FieldMeta { key: 0, name: "id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "params", wire: "Option<CborMap>", required: false, default: None },
            ],
        },
    ],
};

pub const FAILUREPOLICY_UNION: UnionMeta = UnionMeta {
    name: "FailurePolicy",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Toast",
            wire_kind: "toast",
            fields: &[],
        },
        VariantMeta {
            rust_name: "RevertOptimistic",
            wire_kind: "revert_optimistic",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Custom",
            wire_kind: "custom",
            fields: &[
                FieldMeta { key: 0, name: "action", wire: "Inline<LocalAction>", required: true, default: None },
            ],
        },
    ],
};

pub const LOCALACTION_UNION: UnionMeta = UnionMeta {
    name: "LocalAction",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "ShowModal",
            wire_kind: "show_modal",
            fields: &[
                FieldMeta { key: 0, name: "slot_id", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "HideModal",
            wire_kind: "hide_modal",
            fields: &[
                FieldMeta { key: 0, name: "slot_id", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "ToggleSlot",
            wire_kind: "toggle_slot",
            fields: &[
                FieldMeta { key: 0, name: "slot_id", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "SetState",
            wire_kind: "set_state",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "DeleteState",
            wire_kind: "delete_state",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Toggle",
            wire_kind: "toggle",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Increment",
            wire_kind: "increment",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "delta", wire: "i64", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Navigate",
            wire_kind: "navigate",
            fields: &[
                FieldMeta { key: 0, name: "panel_id", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Focus",
            wire_kind: "focus",
            fields: &[
                FieldMeta { key: 0, name: "component_id", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Scroll",
            wire_kind: "scroll",
            fields: &[
                FieldMeta { key: 0, name: "component_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "behavior", wire: "Enum<ScrollBehavior>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Copy",
            wire_kind: "copy",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Confirm",
            wire_kind: "confirm",
            fields: &[
                FieldMeta { key: 0, name: "title", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "message", wire: "tstr", required: true, default: None },
                FieldMeta { key: 2, name: "destructive", wire: "bool", required: true, default: None },
                FieldMeta { key: 3, name: "then", wire: "Inline<Handler>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Validate",
            wire_kind: "validate",
            fields: &[
                FieldMeta { key: 0, name: "field_component_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "rules", wire: "Array<Inline<ValidationRule>>", required: true, default: None },
                FieldMeta { key: 2, name: "on_invalid", wire: "Inline<LocalAction>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Debounce",
            wire_kind: "debounce",
            fields: &[
                FieldMeta { key: 0, name: "ms", wire: "u32", required: true, default: None },
                FieldMeta { key: 1, name: "then", wire: "Inline<Handler>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Sequence",
            wire_kind: "sequence",
            fields: &[
                FieldMeta { key: 0, name: "steps", wire: "Array<Inline<Handler>>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Conditional",
            wire_kind: "conditional",
            fields: &[
                FieldMeta { key: 0, name: "when", wire: "Inline<StateCondition>", required: true, default: None },
                FieldMeta { key: 1, name: "then", wire: "Inline<Handler>", required: true, default: None },
                FieldMeta { key: 2, name: "else_branch", wire: "Option<Inline<Handler>>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Noop",
            wire_kind: "noop",
            fields: &[],
        },
    ],
};

pub const HANDLER_UNION: UnionMeta = UnionMeta {
    name: "Handler",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Local",
            wire_kind: "local",
            fields: &[
                FieldMeta { key: 0, name: "action", wire: "Inline<LocalAction>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Backend",
            wire_kind: "backend",
            fields: &[
                FieldMeta { key: 0, name: "action_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "params", wire: "CborMap", required: true, default: None },
                FieldMeta { key: 2, name: "optimistic", wire: "Option<Array<Inline<PatchOp>>>", required: false, default: None },
                FieldMeta { key: 3, name: "on_failure", wire: "Inline<FailurePolicy>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Both",
            wire_kind: "both",
            fields: &[
                FieldMeta { key: 0, name: "action_id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "params", wire: "CborMap", required: true, default: None },
                FieldMeta { key: 2, name: "optimistic", wire: "Array<Inline<PatchOp>>", required: true, default: None },
                FieldMeta { key: 3, name: "on_failure", wire: "Inline<FailurePolicy>", required: true, default: None },
            ],
        },
    ],
};

pub const ICONREF_UNION: UnionMeta = UnionMeta {
    name: "IconRef",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Named",
            wire_kind: "named",
            fields: &[
                FieldMeta { key: 0, name: "name", wire: "Enum<IconName>", required: true, default: None },
                FieldMeta { key: 1, name: "size", wire: "Option<Enum<IconSize>>", required: false, default: None },
                FieldMeta { key: 2, name: "tone", wire: "Option<Enum<Tone>>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Asset",
            wire_kind: "asset",
            fields: &[
                FieldMeta { key: 0, name: "ref_", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "size_px", wire: "Option<u16>", required: false, default: None },
                FieldMeta { key: 2, name: "alt", wire: "Option<tstr>", required: false, default: None },
            ],
        },
    ],
};

pub const AVATARREF_UNION: UnionMeta = UnionMeta {
    name: "AvatarRef",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Image",
            wire_kind: "image",
            fields: &[
                FieldMeta { key: 0, name: "ref_", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Initials",
            wire_kind: "initials",
            fields: &[
                FieldMeta { key: 0, name: "initials", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Icon",
            wire_kind: "icon",
            fields: &[
                FieldMeta { key: 0, name: "icon", wire: "Inline<IconRef>", required: true, default: None },
            ],
        },
    ],
};

pub const SELECTVALUE_UNION: UnionMeta = UnionMeta {
    name: "SelectValue",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Text",
            wire_kind: "tstr",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "UInt",
            wire_kind: "u32",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Int",
            wire_kind: "i32",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "i32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Bool",
            wire_kind: "bool",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "bool", required: true, default: None },
            ],
        },
    ],
};

pub const DIMENSIONTOKEN_UNION: UnionMeta = UnionMeta {
    name: "DimensionToken",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Auto",
            wire_kind: "auto",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Full",
            wire_kind: "full",
            fields: &[],
        },
        VariantMeta {
            rust_name: "FitContent",
            wire_kind: "fit_content",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Vh",
            wire_kind: "vh",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Vw",
            wire_kind: "vw",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Fr",
            wire_kind: "fr",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Percent",
            wire_kind: "percent",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Spacing",
            wire_kind: "spacing",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Enum<Spacing>", required: true, default: None },
            ],
        },
    ],
};

pub const ASPECTRATIO_UNION: UnionMeta = UnionMeta {
    name: "AspectRatio",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "R1To1",
            wire_kind: "1:1",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R16To9",
            wire_kind: "16:9",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R4To3",
            wire_kind: "4:3",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R21To9",
            wire_kind: "21:9",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R3To2",
            wire_kind: "3:2",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R2To1",
            wire_kind: "2:1",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R9To16",
            wire_kind: "9:16",
            fields: &[],
        },
        VariantMeta {
            rust_name: "R3To4",
            wire_kind: "3:4",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Custom",
            wire_kind: "custom",
            fields: &[
                FieldMeta { key: 0, name: "ratio", wire: "f64", required: true, default: None },
            ],
        },
    ],
};

pub const TABLECOLUMNWIDTH_UNION: UnionMeta = UnionMeta {
    name: "TableColumnWidth",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Auto",
            wire_kind: "auto",
            fields: &[],
        },
        VariantMeta {
            rust_name: "MinContent",
            wire_kind: "min_content",
            fields: &[],
        },
        VariantMeta {
            rust_name: "MaxContent",
            wire_kind: "max_content",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Fr",
            wire_kind: "fr",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
    ],
};

pub const HEATMAPSCALE_UNION: UnionMeta = UnionMeta {
    name: "HeatmapScale",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Linear",
            wire_kind: "linear",
            fields: &[
                FieldMeta { key: 0, name: "min", wire: "f64", required: true, default: None },
                FieldMeta { key: 1, name: "max", wire: "f64", required: true, default: None },
                FieldMeta { key: 2, name: "color_from", wire: "Enum<Tone>", required: true, default: None },
                FieldMeta { key: 3, name: "color_to", wire: "Enum<Tone>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Logarithmic",
            wire_kind: "logarithmic",
            fields: &[
                FieldMeta { key: 0, name: "min", wire: "f64", required: true, default: None },
                FieldMeta { key: 1, name: "max", wire: "f64", required: true, default: None },
                FieldMeta { key: 2, name: "base", wire: "f64", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Categorical",
            wire_kind: "categorical",
            fields: &[
                FieldMeta { key: 0, name: "buckets", wire: "Array<Inline<HeatmapBucket>>", required: true, default: None },
            ],
        },
    ],
};

pub const DATEPRESETRESOLVE_UNION: UnionMeta = UnionMeta {
    name: "DatePresetResolve",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Today",
            wire_kind: "today",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Yesterday",
            wire_kind: "yesterday",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Last7Days",
            wire_kind: "last_7_days",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Last30Days",
            wire_kind: "last_30_days",
            fields: &[],
        },
        VariantMeta {
            rust_name: "ThisMonth",
            wire_kind: "this_month",
            fields: &[],
        },
        VariantMeta {
            rust_name: "LastMonth",
            wire_kind: "last_month",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Custom",
            wire_kind: "custom",
            fields: &[
                FieldMeta { key: 0, name: "offset_days", wire: "i32", required: true, default: None },
            ],
        },
    ],
};

pub const BORDERTOKEN_UNION: UnionMeta = UnionMeta {
    name: "BorderToken",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "None",
            wire_kind: "none",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Hairline",
            wire_kind: "hairline",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Thin",
            wire_kind: "thin",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Strong",
            wire_kind: "strong",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Accent",
            wire_kind: "accent",
            fields: &[
                FieldMeta { key: 0, name: "tone", wire: "Enum<Tone>", required: true, default: None },
            ],
        },
    ],
};

pub const SPACEVALUE_UNION: UnionMeta = UnionMeta {
    name: "SpaceValue",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Token",
            wire_kind: "token",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Enum<Spacing>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u16", required: true, default: None },
            ],
        },
    ],
};

pub const RADIUSVALUE_UNION: UnionMeta = UnionMeta {
    name: "RadiusValue",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Token",
            wire_kind: "token",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Enum<RadiusToken>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u16", required: true, default: None },
            ],
        },
    ],
};

pub const SPLITSIZE_UNION: UnionMeta = UnionMeta {
    name: "SplitSize",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Auto",
            wire_kind: "auto",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Percent",
            wire_kind: "percent",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "f64", required: true, default: None },
            ],
        },
    ],
};

pub const GRIDCOL_UNION: UnionMeta = UnionMeta {
    name: "GridCol",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Auto",
            wire_kind: "auto",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Fill",
            wire_kind: "fill",
            fields: &[],
        },
        VariantMeta {
            rust_name: "MinContent",
            wire_kind: "min_content",
            fields: &[],
        },
        VariantMeta {
            rust_name: "MaxContent",
            wire_kind: "max_content",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Fr",
            wire_kind: "fr",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Px",
            wire_kind: "px",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u32", required: true, default: None },
            ],
        },
    ],
};

pub const GRIDTRACK_UNION: UnionMeta = UnionMeta {
    name: "GridTrack",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Equal",
            wire_kind: "equal",
            fields: &[
                FieldMeta { key: 0, name: "count", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Explicit",
            wire_kind: "explicit",
            fields: &[
                FieldMeta { key: 0, name: "cols", wire: "Array<Inline<GridCol>>", required: true, default: None },
            ],
        },
    ],
};

pub const PATCHOPKIND_UNION: UnionMeta = UnionMeta {
    name: "PatchOpKind",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Set",
            wire_kind: "set",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Delete",
            wire_kind: "delete",
            fields: &[],
        },
        VariantMeta {
            rust_name: "AppendArray",
            wire_kind: "append_array",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "PrependArray",
            wire_kind: "prepend_array",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "InsertArray",
            wire_kind: "insert_array",
            fields: &[
                FieldMeta { key: 0, name: "index", wire: "u32", required: true, default: None },
                FieldMeta { key: 1, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "RemoveArray",
            wire_kind: "remove_array",
            fields: &[
                FieldMeta { key: 0, name: "index", wire: "u32", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "MergeMap",
            wire_kind: "merge_map",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "CborMap", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Increment",
            wire_kind: "increment",
            fields: &[
                FieldMeta { key: 0, name: "delta", wire: "i64", required: true, default: None },
            ],
        },
    ],
};

pub const VALIDATIONRULE_UNION: UnionMeta = UnionMeta {
    name: "ValidationRule",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Required",
            wire_kind: "required",
            fields: &[],
        },
        VariantMeta {
            rust_name: "MinLength",
            wire_kind: "min_length",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u16", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "MaxLength",
            wire_kind: "max_length",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "u16", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Min",
            wire_kind: "min",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "f64", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Max",
            wire_kind: "max",
            fields: &[
                FieldMeta { key: 0, name: "value", wire: "f64", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Pattern",
            wire_kind: "pattern",
            fields: &[
                FieldMeta { key: 0, name: "regex", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Email",
            wire_kind: "email",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Url",
            wire_kind: "url",
            fields: &[
                FieldMeta { key: 0, name: "schemes", wire: "Array<tstr>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Iban",
            wire_kind: "iban",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Phone",
            wire_kind: "phone",
            fields: &[
                FieldMeta { key: 0, name: "region", wire: "Option<tstr>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Uuid",
            wire_kind: "uuid",
            fields: &[],
        },
        VariantMeta {
            rust_name: "DateRange",
            wire_kind: "date_range",
            fields: &[
                FieldMeta { key: 0, name: "min", wire: "Option<tstr>", required: false, default: None },
                FieldMeta { key: 1, name: "max", wire: "Option<tstr>", required: false, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Custom",
            wire_kind: "custom",
            fields: &[
                FieldMeta { key: 0, name: "id", wire: "tstr", required: true, default: None },
                FieldMeta { key: 1, name: "params", wire: "Option<CborMap>", required: false, default: None },
            ],
        },
    ],
};

pub const STATECONDITION_UNION: UnionMeta = UnionMeta {
    name: "StateCondition",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "IsTruthy",
            wire_kind: "is_truthy",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "IsFalsy",
            wire_kind: "is_falsy",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Equals",
            wire_kind: "equals",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "value", wire: "Value", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "NotEquals",
            wire_kind: "not_equals",
            fields: &[
                FieldMeta { key: 0, name: "path", wire: "StatePath", required: true, default: None },
                FieldMeta { key: 1, name: "value", wire: "Value", required: true, default: None },
            ],
        },
    ],
};

pub const VALUEFORMAT_UNION: UnionMeta = UnionMeta {
    name: "ValueFormat",
    discriminator_key: "kind",
    variants: &[
        VariantMeta {
            rust_name: "Number",
            wire_kind: "number",
            fields: &[
                FieldMeta { key: 0, name: "decimals", wire: "u8", required: true, default: None },
                FieldMeta { key: 1, name: "thousands_sep", wire: "bool", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Currency",
            wire_kind: "currency",
            fields: &[
                FieldMeta { key: 0, name: "code", wire: "tstr", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Percent",
            wire_kind: "percent",
            fields: &[
                FieldMeta { key: 0, name: "decimals", wire: "u8", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Bytes",
            wire_kind: "bytes",
            fields: &[
                FieldMeta { key: 0, name: "base", wire: "Enum<BytesBase>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Duration",
            wire_kind: "duration",
            fields: &[
                FieldMeta { key: 0, name: "style", wire: "Enum<DurationStyle>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Date",
            wire_kind: "date",
            fields: &[
                FieldMeta { key: 0, name: "style", wire: "Enum<DateStyle>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Time",
            wire_kind: "time",
            fields: &[
                FieldMeta { key: 0, name: "style", wire: "Enum<TimeStyle>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "DateTime",
            wire_kind: "datetime",
            fields: &[
                FieldMeta { key: 0, name: "style", wire: "Enum<DateTimeStyle>", required: true, default: None },
            ],
        },
        VariantMeta {
            rust_name: "Relative",
            wire_kind: "relative",
            fields: &[],
        },
        VariantMeta {
            rust_name: "Plain",
            wire_kind: "plain",
            fields: &[],
        },
    ],
};

/// All tagged unions captured by the schema registry.
pub const ALL_TAGGED_UNIONS: &[&UnionMeta] = &[
    &RESUMESTATUS_UNION,
    &REJECTREASON_UNION,
    &RATELIMITSCOPE_UNION,
    &ACTIONSTATUS_UNION,
    &PATHSEGMENT_UNION,
    &BINDREF_UNION,
    &BINDSPEC_UNION,
    &FORMVALIDATOR_UNION,
    &FAILUREPOLICY_UNION,
    &LOCALACTION_UNION,
    &HANDLER_UNION,
    &ICONREF_UNION,
    &AVATARREF_UNION,
    &SELECTVALUE_UNION,
    &DIMENSIONTOKEN_UNION,
    &ASPECTRATIO_UNION,
    &TABLECOLUMNWIDTH_UNION,
    &HEATMAPSCALE_UNION,
    &DATEPRESETRESOLVE_UNION,
    &BORDERTOKEN_UNION,
    &SPACEVALUE_UNION,
    &RADIUSVALUE_UNION,
    &SPLITSIZE_UNION,
    &GRIDCOL_UNION,
    &GRIDTRACK_UNION,
    &PATCHOPKIND_UNION,
    &VALIDATIONRULE_UNION,
    &STATECONDITION_UNION,
    &VALUEFORMAT_UNION,
];
