// =============================================================================
// File: tentanas/shares.rs — SMB and NFS file shares of one node (plan-02
//       §5.4, tab "Udostępnianie").
//
//       TentaNas OWNS its configuration and never reads it back: `nas_shares`
//       is the desired state and `/etc/samba/tentanas.conf` +
//       `/etc/exports.d/tentanas.exports` are generated from it on every
//       change. The app's only footprint in the distribution's own `smb.conf`
//       is one marker-delimited `include` line, so a hand-written share of the
//       admin's can never be lost by a rewrite of ours.
//
//       A section is materialized ONLY after the source path is verified to be
//       a mounted dataset (§3.4 "Materializacja configów"): a share pointing
//       at an unmounted mountpoint is an empty, writable directory on the
//       rootfs, and the writes that land there disappear the moment the pool
//       mounts over them.
//
//       Generation is pure text over rows, so the fixtures below exercise the
//       whole config surface on a host with neither Samba nor NFS.
// =============================================================================

use std::collections::BTreeMap;
use std::path::Path;
use std::time::Duration;

use anyhow::{anyhow, Result};
use serde_json::Value;
use tentaflow_protocol::tentanas::{
    NasDataset, NasDirEntry, NasNfsOptions, NasShare, NasShareService, NasShareSession,
    NasSmbOptions,
};
use tentanas_helper::HelperCommand;

use super::db::{self as store, ShareRow};
use crate::db::DbPool;
use crate::profiling::collectors::elevation::ElevationToken;

/// Where a fleet mount of another node's share lands on this one.
pub const MOUNT_ROOT: &str = tentanas_helper::FLEET_MOUNT_ROOT;

/// A privileged step of the apply pipeline gets a generous window: `exportfs`
/// waits for the kernel and `smbcontrol` for every smbd child.
const APPLY_TIMEOUT: Duration = Duration::from_secs(120);

// =============================================================================
// smb.conf generation
// =============================================================================

/// The header of the app-owned include file. It is a comment, so smbd ignores
/// it, and it tells an admin reading `/etc/samba/tentanas.conf` by hand that
/// editing it is pointless — the next share change overwrites the file.
const SMB_HEADER: &str = "# Generated by TentaNas. Every section below is rebuilt from the app's\n\
                          # database on every share change; edits here are lost.\n";

fn line(out: &mut String, key: &str, value: &str) {
    out.push('\t');
    out.push_str(key);
    out.push_str(" = ");
    out.push_str(value);
    out.push('\n');
}

/// The share section of one SMB share. `read only = no` plus explicit
/// `write list`/`read list` is what makes the per-user grants decide, and the
/// masks match the setgid share root `ShareChown` creates.
pub fn smb_section(share: &ShareRow) -> String {
    let smb = share.smb.clone().unwrap_or_default();
    let mut out = format!("[{}]\n", share.name);
    line(&mut out, "path", &share.source_path);
    line(&mut out, "browseable", "yes");
    line(&mut out, "read only", "no");
    line(&mut out, "guest ok", if smb.guests { "yes" } else { "no" });
    if smb.guests {
        // A guest connection maps to a user outside the share group, so the
        // group has to be forced for the files it creates to stay shared.
        line(&mut out, "force group", tentanas_helper::SHARE_GROUP);
    }
    let names: Vec<&str> = smb.users.iter().map(|u| u.user.as_str()).collect();
    if !names.is_empty() {
        line(&mut out, "valid users", &names.join(", "));
        let write: Vec<&str> = smb
            .users
            .iter()
            .filter(|u| u.mode == "rw")
            .map(|u| u.user.as_str())
            .collect();
        let read: Vec<&str> = smb
            .users
            .iter()
            .filter(|u| u.mode != "rw")
            .map(|u| u.user.as_str())
            .collect();
        if !write.is_empty() {
            line(&mut out, "write list", &write.join(", "));
        }
        if !read.is_empty() {
            line(&mut out, "read list", &read.join(", "));
        }
    }
    line(&mut out, "create mask", "0660");
    line(&mut out, "directory mask", "2770");

    // vfs_fruit must load before streams_xattr, and catia is what makes the
    // illegal-character mapping fruit expects work.
    let mut vfs: Vec<&str> = Vec::new();
    if smb.time_machine {
        vfs.extend(["catia", "fruit", "streams_xattr"]);
    }
    if smb.previous_versions {
        vfs.push("shadow_copy2");
    }
    if smb.recycle_bin {
        vfs.push("recycle");
    }
    if !vfs.is_empty() {
        line(&mut out, "vfs objects", &vfs.join(" "));
    }
    if smb.previous_versions {
        // ZFS exposes its snapshots under `.zfs/snapshot`, and the app names
        // them `auto-<YYYYMMDD>-<HHMM>-<tier>` / `manual-<YYYYMMDD>-<HHMMSS>`
        // in NODE LOCAL time. snapprefix + delimiter split that prefix off so
        // one format matches both; a snapshot named by hand outside those two
        // shapes is simply not offered as a previous version.
        line(&mut out, "shadow:snapdir", ".zfs/snapshot");
        line(&mut out, "shadow:sort", "desc");
        line(&mut out, "shadow:localtime", "yes");
        line(&mut out, "shadow:snapprefix", "^(auto|manual)$");
        line(&mut out, "shadow:delimiter", "-");
        line(&mut out, "shadow:format", "%Y%m%d-%H%M");
    }
    if smb.recycle_bin {
        line(&mut out, "recycle:repository", ".recycle/%U");
        line(&mut out, "recycle:keeptree", "yes");
        line(&mut out, "recycle:versions", "yes");
        line(&mut out, "recycle:touch", "yes");
    }
    if smb.time_machine {
        line(&mut out, "fruit:time machine", "yes");
        line(&mut out, "fruit:metadata", "stream");
        line(&mut out, "fruit:model", "RackMac");
    }
    out
}

/// The whole app-owned include file for the shares that are actually
/// exportable right now.
///
/// `ksmbd_interfaces` is the listener split of §5.4b: when the second SMB
/// backend takes the node's RDMA interfaces, Samba has to stop binding them or
/// the two servers fight over TCP 445 — whichever starts first wins and the
/// other silently serves nothing. Samba's `interfaces` has no exclusion
/// syntax, so the `[global]` block names everything ksmbd did NOT take. An
/// empty list means ksmbd is not running and smbd keeps its own defaults.
pub fn smb_document(shares: &[ShareRow], ksmbd_interfaces: &[String]) -> String {
    let mut out = SMB_HEADER.to_string();
    if !ksmbd_interfaces.is_empty() {
        let keep = super::ksmbd::samba_interfaces_here(ksmbd_interfaces);
        out.push('\n');
        out.push_str("[global]\n");
        line(&mut out, "interfaces", &keep.join(" "));
        line(&mut out, "bind interfaces only", "yes");
    }
    for share in shares.iter().filter(|s| s.protocol == "smb") {
        out.push('\n');
        out.push_str(&smb_section(share));
    }
    out
}

// =============================================================================
// exports generation
// =============================================================================

/// The option list of one export as the share configured it.
pub fn export_options(nfs: &NasNfsOptions) -> String {
    let mut opts = vec![if nfs.read_only { "ro" } else { "rw" }];
    opts.push(if nfs.async_writes { "async" } else { "sync" });
    opts.push(if nfs.root_squash {
        "root_squash"
    } else {
        "no_root_squash"
    });
    // Subtree checks break on a renamed open file and buy nothing on a
    // whole-dataset export, which is the only shape this app produces.
    opts.push("no_subtree_check");
    opts.join(",")
}

/// The options a FLEET mount gets. Fleet traffic is node-to-node over the LAN
/// the mesh already trusts, but a remote root still must not become local
/// root, hence `root_squash` regardless of what the share itself allows.
pub const FLEET_EXPORT_OPTIONS: &str = "rw,sync,root_squash,no_subtree_check";

/// The whole exports file: one line per exported path with every client of
/// that path, because `exportfs` warns about a directory listed twice. The
/// share's own clients win over the fleet clients when both name the same
/// address — the admin's intent for that address is the explicit one.
pub fn exports_document(shares: &[ShareRow], fleet_clients: &[String]) -> String {
    let mut by_path: BTreeMap<&str, Vec<(String, String)>> = BTreeMap::new();
    for share in shares {
        if let Some(nfs) = share.nfs.as_ref() {
            let opts = export_options(nfs);
            let clients: Vec<String> = if nfs.networks.is_empty() {
                vec!["*".to_string()]
            } else {
                nfs.networks.clone()
            };
            let entry = by_path.entry(share.source_path.as_str()).or_default();
            for client in clients {
                if !entry.iter().any(|(c, _)| *c == client) {
                    entry.push((client, opts.clone()));
                }
            }
        }
    }
    for share in shares.iter().filter(|s| s.fleet_mount) {
        let entry = by_path.entry(share.source_path.as_str()).or_default();
        for client in fleet_clients {
            if !entry.iter().any(|(c, _)| c == client) {
                entry.push((client.clone(), FLEET_EXPORT_OPTIONS.to_string()));
            }
        }
    }
    let mut out = String::from(
        "# Generated by TentaNas. The whole file is app-owned and rebuilt on\n\
         # every share change; edits here are lost.\n",
    );
    for (path, clients) in by_path {
        if clients.is_empty() {
            continue;
        }
        out.push_str(path);
        for (client, opts) in clients {
            out.push(' ');
            out.push_str(&client);
            out.push('(');
            out.push_str(&opts);
            out.push(')');
        }
        out.push('\n');
    }
    out
}

// =============================================================================
// source paths
// =============================================================================

/// A source path resolved against the node's datasets.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Source {
    pub path: String,
    /// The dataset that owns the path, when one does.
    pub dataset: Option<String>,
    /// Whether that dataset is mounted right now.
    pub mounted: bool,
}

/// The dataset whose mountpoint owns `path`: the longest mountpoint that is
/// `path` itself or a parent of it.
pub fn owning_dataset<'a>(datasets: &'a [NasDataset], path: &str) -> Option<&'a NasDataset> {
    datasets
        .iter()
        .filter(|d| {
            d.mountpoint
                .as_deref()
                .is_some_and(|m| path == m || path.starts_with(&format!("{m}/")))
        })
        .max_by_key(|d| d.mountpoint.as_deref().unwrap_or_default().len())
}

/// Validates a share source: it must be an existing directory under a POOL
/// mountpoint, and the canonical path must equal what was asked for — a
/// symlink under the pool that points at `/etc` would otherwise export `/etc`.
pub fn resolve_source(datasets: &[NasDataset], raw: &str) -> Result<Source> {
    tentanas_helper::validate_share_path(raw).map_err(|e| anyhow!(e.to_string()))?;
    let pool_roots: Vec<&str> = datasets
        .iter()
        .filter(|d| !d.name.contains('/'))
        .filter_map(|d| d.mountpoint.as_deref())
        .collect();
    if !pool_roots
        .iter()
        .any(|m| raw == *m || raw.starts_with(&format!("{m}/")))
    {
        return Err(anyhow!(
            "'{raw}' is not under a pool mountpoint of this node"
        ));
    }
    let path = Path::new(raw);
    if !path.is_dir() {
        return Err(anyhow!("'{raw}' is not a directory on this node"));
    }
    let canonical = std::fs::canonicalize(path)
        .map_err(|e| anyhow!("'{raw}' cannot be resolved: {e}"))?;
    if canonical != path {
        return Err(anyhow!(
            "'{raw}' resolves to '{}' — a share source may not be a symlink",
            canonical.display()
        ));
    }
    let owner = owning_dataset(datasets, raw);
    Ok(Source {
        dataset: owner
            .filter(|d| d.mountpoint.as_deref() == Some(raw))
            .map(|d| d.name.clone()),
        mounted: owner.is_some_and(|d| d.mounted),
        path: raw.to_string(),
    })
}

// =============================================================================
// service state
// =============================================================================

/// Whether a process with this name runs right now, read from `/proc`. Needed
/// for `nfsd`, which is a kernel thread with no pid file and no unit name that
/// is the same on every distribution.
pub fn process_running(name: &str) -> bool {
    let Ok(entries) = std::fs::read_dir("/proc") else {
        return false;
    };
    for entry in entries.flatten() {
        let file = entry.file_name();
        let Some(pid) = file.to_str() else { continue };
        if !pid.bytes().all(|b| b.is_ascii_digit()) {
            continue;
        }
        if let Ok(comm) = std::fs::read_to_string(entry.path().join("comm")) {
            if comm.trim() == name {
                return true;
            }
        }
    }
    false
}

/// The two protocol services as the Sharing tab shows them.
pub async fn services(db: &DbPool) -> Vec<NasShareService> {
    let env = super::environment::cached_or_probe(db).await.ok();
    let feature = |id: &str| {
        env.as_ref()
            .and_then(|e| e.features.iter().find(|f| f.id == id).cloned())
    };
    let smb = feature("samba");
    let nfs = feature("nfs");
    vec![
        NasShareService {
            protocol: "smb".to_string(),
            installed: smb.as_ref().is_some_and(|f| f.status == "ok"),
            running: process_running("smbd"),
            version: smb.as_ref().and_then(|f| f.version.clone()),
            config_path: tentanas_helper::SMB_INCLUDE_PATH.to_string(),
            detail: smb.map(|f| f.detail).unwrap_or_default(),
        },
        NasShareService {
            protocol: "nfs".to_string(),
            installed: nfs.as_ref().is_some_and(|f| f.status == "ok"),
            running: process_running("nfsd"),
            version: nfs.as_ref().and_then(|f| f.version.clone()),
            config_path: tentanas_helper::NFS_EXPORTS_PATH.to_string(),
            detail: nfs.map(|f| f.detail).unwrap_or_default(),
        },
    ]
}

fn service_installed(protocol: &str) -> bool {
    match protocol {
        "smb" => super::environment::find_binary("smbd").is_some(),
        _ => super::environment::find_binary("exportfs").is_some(),
    }
}

/// What a share's `state`/`state_detail` are right now, without touching the
/// system: disabled by the admin, broken for a reason the UI can act on, or
/// active. The reason is what decides whether the share reaches the generated
/// config at all.
///
/// `installed` answers "does this node have that protocol's server", passed in
/// so the whole verdict is decided by arguments rather than by the host the
/// function happens to run on. `smb_direct_refusal` is the node's ksmbd
/// verdict (§5.4b) when it cannot serve SMB Direct: a share that asked for it
/// stays ACTIVE — Samba keeps exporting it over the LAN, which is most of what
/// it is for — but carries the reason, so the UI shows a warning instead of
/// the option looking as if it took effect.
pub fn share_state(
    share: &ShareRow,
    source: &Result<Source>,
    installed: &dyn Fn(&str) -> bool,
    smb_direct_refusal: Option<&str>,
) -> (&'static str, String) {
    if !share.enabled {
        return ("disabled", String::new());
    }
    match source {
        Err(e) => ("error", e.to_string()),
        Ok(s) if !s.mounted => (
            "error",
            "source path is not mounted — the share stays out of the config".to_string(),
        ),
        Ok(_) => {
            if !installed(&share.protocol) {
                let missing = if share.protocol == "smb" {
                    "samba missing"
                } else {
                    "nfs-kernel-server missing"
                };
                return ("error", missing.to_string());
            }
            // A fleet mount is always served over NFS, whatever the share's
            // own protocol is — see fleet_mounts.rs.
            if share.fleet_mount && !installed("nfs") {
                return ("error", "nfs-kernel-server missing".to_string());
            }
            match smb_direct_refusal.filter(|_| super::ksmbd::smb_direct(share)) {
                Some(reason) => ("active", reason.to_string()),
                None => ("active", String::new()),
            }
        }
    }
}

// =============================================================================
// apply
// =============================================================================

/// Recomputes every share's state and rewrites the app-owned configs. Returns
/// the log lines the calling job records.
///
/// Only `active` shares reach the generated files; a share whose source is not
/// mounted stays out of them and says so in `state_detail`.
pub async fn apply(
    db: &DbPool,
    main_db: &DbPool,
    addon_id: &str,
    explicit: Option<&ElevationToken>,
) -> Result<Vec<String>> {
    let datasets = super::datasets::list("").await.unwrap_or_default();
    let mut shares = store::list_shares(db)?;
    let mut log = Vec::new();

    // §5.4b: the ksmbd verdict is taken BEFORE the states, so a share that
    // asked for SMB Direct on a node that may not serve it carries the reason
    // rather than the app starting a kernel SMB server the guard forbids.
    let ksmbd = super::ksmbd::probe();
    let refusal = (!ksmbd.ready()).then(|| super::ksmbd::refusal(&ksmbd));

    for share in shares.iter_mut() {
        let source = resolve_source(&datasets, &share.source_path);
        let (state, detail) = share_state(share, &source, &service_installed, refusal.as_deref());
        if share.state != state || share.state_detail != detail {
            store::set_share_state(db, &share.share_id, state, &detail)?;
        }
        share.state = state.to_string();
        share.state_detail = detail;
        // An active share with a detail is the SMB Direct refusal: never
        // silent, so it goes into the job log next to the hard errors.
        if !share.state_detail.is_empty() {
            log.push(format!("{}: {}", share.name, share.state_detail));
        }
    }
    let active: Vec<ShareRow> = shares.iter().filter(|s| s.state == "active").cloned().collect();

    // The interfaces the second SMB backend takes, or none when no share asked
    // for SMB Direct or this node may not serve it.
    let serves_smb_direct = super::ksmbd::wants_smb_direct(&active) && ksmbd.ready();
    let ksmbd_interfaces = if serves_smb_direct {
        ksmbd.netdevs()
    } else {
        Vec::new()
    };

    // SMB: the include line first, so the file the next step writes is already
    // read by smbd when it reloads.
    if service_installed("smb") {
        run(db, &HelperCommand::SmbIncludeEnsure {}, None, explicit, &mut log).await?;
        let document = smb_document(&active, &ksmbd_interfaces);
        run(
            db,
            &HelperCommand::SmbConfigWrite {},
            Some(document.as_bytes()),
            explicit,
            &mut log,
        )
        .await?;

        // ksmbd goes AFTER Samba, and never before it: smbd binds 0.0.0.0:445
        // until the include above takes the RDMA interfaces away from it, and
        // whichever server holds that socket first leaves the other silently
        // serving nothing.
        if let Err(e) = apply_ksmbd(db, &active, &ksmbd_interfaces, explicit, &mut log).await {
            // The exclusion is already live, so the RDMA interfaces would now
            // carry no SMB at all. Give them back to Samba before reporting —
            // a failed upgrade must not cost the node the service it had.
            let document = smb_document(&active, &[]);
            run(
                db,
                &HelperCommand::SmbConfigWrite {},
                Some(document.as_bytes()),
                explicit,
                &mut log,
            )
            .await?;
            // The message, not a log line: an apply that fails reports its
            // error and the collected log does not survive the job.
            return Err(anyhow!("SMB Direct not applied: {e}; smbd took the RDMA interfaces back"));
        }
    }

    // NFS: the shares' own exports plus one fleet export per share that is
    // mounted fleet-wide.
    if service_installed("nfs") {
        let clients = super::fleet_mounts::fleet_client_addresses(main_db, addon_id);
        let document = exports_document(&active, &clients);
        run(
            db,
            &HelperCommand::NfsExportsWrite {},
            Some(document.as_bytes()),
            explicit,
            &mut log,
        )
        .await?;
        store::set_setting(db, SETTING_EXPORTS, &document)?;

        // The RDMA listener is one per SERVER, not one per export, so it is
        // on exactly while some share asked for it (§5.5a). Acting only when
        // the answer changed keeps a share edit from restarting a listener
        // every other share is already using — and keeps a node that never
        // wanted RDMA free of an nfs.conf drop-in altogether.
        //
        // The live probe is ANDed in: a card that went down since the share
        // was configured leaves the share's intent alone (it comes back with
        // the link) but closes the listener, so clients fall back to TCP
        // instead of every apply failing on a port nfsd cannot open.
        let rdma = wants_rdma(&active) && super::rdma::probe().ready();
        let wanted = rdma_setting(rdma);
        // Unset reads as off, so a node that never touched the transport does
        // not spend a privileged call proving the drop-in is absent.
        let stored = store::setting(db, SETTING_NFS_RDMA)?
            .unwrap_or_else(|| rdma_setting(false).to_string());
        if stored != wanted {
            let command = if rdma {
                HelperCommand::NfsRdmaSet {}
            } else {
                HelperCommand::NfsRdmaClear {}
            };
            run(db, &command, None, explicit, &mut log).await?;
            store::set_setting(db, SETTING_NFS_RDMA, wanted)?;
        }
    }

    // The share root must belong to the app's group for the grants to mean
    // anything; a failure here is reported but does not undo the config.
    for share in &active {
        let command = HelperCommand::ShareChown {
            path: share.source_path.clone(),
            guests: share.smb.as_ref().is_some_and(|s| s.guests),
        };
        if let Err(e) = run(db, &command, None, explicit, &mut log).await {
            log.push(format!("{}: ownership not set: {e}", share.name));
        }
    }

    super::fleet_mounts::publish_shares(main_db, addon_id, &shares);
    super::fleet_mounts::request_reconcile();
    Ok(log)
}

/// Writes (or removes) the app-owned ksmbd config so it matches what the node
/// may serve. Comparing against the stored document is what keeps an unrelated
/// share edit from restarting a listener every SMB Direct client is using, and
/// keeps a node that never wanted SMB Direct free of a privileged call
/// proving the file is absent.
async fn apply_ksmbd(
    db: &DbPool,
    active: &[ShareRow],
    interfaces: &[String],
    explicit: Option<&ElevationToken>,
    log: &mut Vec<String>,
) -> Result<()> {
    let wanted = if interfaces.is_empty() {
        String::new()
    } else {
        super::ksmbd::ksmbd_document(active, interfaces)
    };
    let stored = store::setting(db, SETTING_KSMBD)?.unwrap_or_default();
    if stored == wanted {
        return Ok(());
    }
    let command = if wanted.is_empty() {
        HelperCommand::KsmbdConfigClear {}
    } else {
        HelperCommand::KsmbdConfigWrite {}
    };
    run(db, &command, (!wanted.is_empty()).then(|| wanted.as_bytes()), explicit, log).await?;
    store::set_setting(db, SETTING_KSMBD, &wanted)?;
    Ok(())
}

/// The exports document the last successful apply wrote. The reconcile loop
/// compares against it so a fleet whose addresses have not changed does not
/// rewrite and reload the exports every minute.
pub const SETTING_EXPORTS: &str = "exports_document";

/// The ksmbd config the last successful apply wrote; empty (or unset) on a
/// node that serves no SMB Direct.
pub const SETTING_KSMBD: &str = "ksmbd_document";

/// Whether the last successful apply left the node's NFS RDMA listener on
/// ('on' | 'off'). Unset on a node that never touched the transport, which
/// reads the same as 'off'.
pub const SETTING_NFS_RDMA: &str = "nfs_rdma_enabled";

fn rdma_setting(enabled: bool) -> &'static str {
    if enabled {
        "on"
    } else {
        "off"
    }
}

/// Whether any exportable share asked for the RDMA transport. One share is
/// enough: the listener belongs to the server, not to an export.
pub fn wants_rdma(shares: &[ShareRow]) -> bool {
    shares
        .iter()
        .any(|s| s.nfs.as_ref().is_some_and(|n| n.rdma))
}

async fn run(
    db: &DbPool,
    command: &HelperCommand,
    payload: Option<&[u8]>,
    explicit: Option<&ElevationToken>,
    log: &mut Vec<String>,
) -> Result<()> {
    if let Ok(plan) = command.plan() {
        log.push(format!("$ {}", plan.display()));
    }
    let (out, channel) = match payload {
        Some(bytes) => {
            super::broker::run_privileged_with_key(db, command, bytes, explicit, APPLY_TIMEOUT)
                .await?
        }
        None => super::broker::run_privileged(db, command, explicit, APPLY_TIMEOUT).await?,
    };
    log.push(format!("channel: {}", channel.as_str()));
    for text in [&out.stdout, &out.stderr] {
        for l in text.lines().filter(|l| !l.trim().is_empty()) {
            log.push(l.trim_end().to_string());
        }
    }
    if !out.success() {
        return Err(anyhow!(
            "{}",
            out.stderr
                .trim()
                .lines()
                .next()
                .unwrap_or("the privileged step failed")
        ));
    }
    Ok(())
}

/// Removes the app's whole footprint from both services. Used by the uninstall
/// teardown (§5.8 step 2); the shares' DATA is never touched.
pub async fn remove_all(db: &DbPool, explicit: Option<&ElevationToken>) -> Vec<String> {
    let mut log = Vec::new();
    // ksmbd first (§5.8): it is the server that took TCP 445 on the RDMA
    // interfaces, and the Samba include below is what gives them back. Doing
    // it the other way round would have smbd try to bind a port ksmbd still
    // holds.
    if Path::new(tentanas_helper::KSMBD_CONF_PATH).exists() {
        if let Err(e) = run(db, &HelperCommand::KsmbdConfigClear {}, None, explicit, &mut log).await
        {
            log.push(format!("ksmbd not stopped: {e}"));
        }
    }
    // Keyed on the FILES, not on the services: a node where Samba was removed
    // after the shares were made still has the app's include line, and the
    // teardown plan promised to take it out.
    if Path::new(tentanas_helper::SMB_INCLUDE_PATH).exists() {
        if let Err(e) = run(db, &HelperCommand::SmbIncludeRemove {}, None, explicit, &mut log).await
        {
            log.push(format!("smb.conf include not removed: {e}"));
        }
    }
    if Path::new(tentanas_helper::NFS_EXPORTS_PATH).exists() {
        let empty = exports_document(&[], &[]);
        if let Err(e) = run(
            db,
            &HelperCommand::NfsExportsWrite {},
            Some(empty.as_bytes()),
            explicit,
            &mut log,
        )
        .await
        {
            log.push(format!("exports not cleared: {e}"));
        }
    }
    // The nfs.conf drop-in and the RDMA listener are ours too (§5.8 step 2);
    // keyed on the FILE for the same reason the two above are.
    if Path::new(tentanas_helper::NFS_CONF_PATH).exists() {
        if let Err(e) = run(db, &HelperCommand::NfsRdmaClear {}, None, explicit, &mut log).await {
            log.push(format!("NFS RDMA drop-in not removed: {e}"));
        }
    }
    log
}

// =============================================================================
// sessions
// =============================================================================

/// Connected SMB clients per share name, from `smbstatus --json`. A tree
/// connect is what the UI calls a session: one client attached to one share.
pub fn parse_smbstatus(text: &str) -> BTreeMap<String, Vec<NasShareSession>> {
    let mut out: BTreeMap<String, Vec<NasShareSession>> = BTreeMap::new();
    let Ok(doc) = serde_json::from_str::<Value>(text) else {
        return out;
    };
    let sessions = doc.get("sessions").and_then(Value::as_object);
    let user_of = |session_id: Option<&str>| -> String {
        session_id
            .and_then(|id| sessions?.get(id))
            .and_then(|s| s.get("username"))
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string()
    };
    let Some(tcons) = doc.get("tcons").and_then(Value::as_object) else {
        return out;
    };
    for tcon in tcons.values() {
        let Some(service) = tcon.get("service").and_then(Value::as_str) else {
            continue;
        };
        // IPC$ is Samba's own named-pipe tree, not a share anybody configured.
        if service == "IPC$" {
            continue;
        }
        out.entry(service.to_string())
            .or_default()
            .push(NasShareSession {
                client: tcon
                    .get("machine")
                    .and_then(Value::as_str)
                    .unwrap_or_default()
                    .to_string(),
                user: user_of(tcon.get("session_id").and_then(Value::as_str)),
                connected_at: tcon
                    .get("connected_at")
                    .and_then(Value::as_str)
                    .map(str::to_string),
            });
    }
    out
}

/// One `/proc/fs/nfsd/clients/<id>/info` document.
pub fn parse_nfs_client_info(text: &str) -> Option<NasShareSession> {
    let mut address = None;
    let mut name = None;
    for line in text.lines() {
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim().trim_matches('"').to_string();
        match key.trim() {
            "address" => address = Some(value),
            "name" => name = Some(value),
            _ => {}
        }
    }
    Some(NasShareSession {
        client: address?,
        user: name.unwrap_or_default(),
        connected_at: None,
    })
}

/// Every NFSv4 client the kernel currently holds state for. NFSv4 state is
/// per CLIENT, not per export, so this is the same list for every NFS share of
/// the node — there is no per-export session to report.
pub fn nfs_clients() -> Vec<NasShareSession> {
    let Ok(entries) = std::fs::read_dir("/proc/fs/nfsd/clients") else {
        return Vec::new();
    };
    entries
        .flatten()
        .filter_map(|e| std::fs::read_to_string(e.path().join("info")).ok())
        .filter_map(|text| parse_nfs_client_info(&text))
        .collect()
}

/// Sessions of one share. SMB needs root (Samba's tdb files), NFS does not.
pub async fn sessions(db: &DbPool, share: &ShareRow) -> Vec<NasShareSession> {
    if share.protocol == "nfs" {
        return nfs_clients();
    }
    let Ok((out, _)) = super::broker::run_privileged(
        db,
        &HelperCommand::SmbStatus {},
        None,
        Duration::from_secs(30),
    )
    .await
    else {
        return Vec::new();
    };
    if !out.success() {
        return Vec::new();
    }
    parse_smbstatus(&out.stdout)
        .remove(&share.name)
        .unwrap_or_default()
}

/// Session COUNTS for the whole list view: one `smbstatus` call for every SMB
/// share instead of one per row.
pub async fn session_counts(db: &DbPool, shares: &[ShareRow]) -> BTreeMap<String, u32> {
    let mut out = BTreeMap::new();
    if shares.iter().any(|s| s.protocol == "smb") {
        if let Ok((result, _)) = super::broker::run_privileged(
            db,
            &HelperCommand::SmbStatus {},
            None,
            Duration::from_secs(30),
        )
        .await
        {
            if result.success() {
                for (name, list) in parse_smbstatus(&result.stdout) {
                    out.insert(name, list.len() as u32);
                }
            }
        }
    }
    if shares.iter().any(|s| s.protocol == "nfs") {
        let clients = nfs_clients().len() as u32;
        for share in shares.iter().filter(|s| s.protocol == "nfs") {
            out.insert(share.name.clone(), clients);
        }
    }
    out
}

// =============================================================================
// source browser
// =============================================================================

/// The share source browser. An empty `path` lists the pool mountpoints; any
/// other path must be one of them or below it, so the browser can never walk
/// out of the pools.
pub async fn browse(db: &DbPool, path: &str) -> Result<(String, Vec<NasDirEntry>)> {
    let datasets = super::datasets::list("").await.map_err(|e| anyhow!("{e}"))?;
    let shares = store::list_shares(db)?;
    let shared_as = |p: &str| -> Vec<String> {
        shares
            .iter()
            .filter(|s| s.source_path == p)
            .map(|s| s.name.clone())
            .collect()
    };
    let dataset_at = |p: &str| -> Option<String> {
        datasets
            .iter()
            .find(|d| d.mountpoint.as_deref() == Some(p))
            .map(|d| d.name.clone())
    };
    if path.is_empty() {
        let entries = datasets
            .iter()
            .filter(|d| !d.name.contains('/'))
            .filter_map(|d| d.mountpoint.as_ref().map(|m| (d, m)))
            .map(|(d, mountpoint)| NasDirEntry {
                name: d.name.clone(),
                dataset: Some(d.name.clone()),
                shared_as: shared_as(mountpoint),
                path: mountpoint.clone(),
            })
            .collect();
        return Ok((String::new(), entries));
    }
    let source = resolve_source(&datasets, path)?;
    let mut entries = Vec::new();
    for entry in std::fs::read_dir(&source.path)
        .map_err(|e| anyhow!("'{}' cannot be listed: {e}", source.path))?
        .flatten()
    {
        // Only real directories: a symlink here would be a way to browse (and
        // then export) something outside the pools.
        if !entry.file_type().is_ok_and(|t| t.is_dir()) {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') {
            continue;
        }
        let child = format!("{}/{name}", source.path.trim_end_matches('/'));
        entries.push(NasDirEntry {
            dataset: dataset_at(&child),
            shared_as: shared_as(&child),
            path: child,
            name,
        });
    }
    entries.sort_by(|a, b| a.name.cmp(&b.name));
    Ok((source.path, entries))
}

// =============================================================================
// protocol shape
// =============================================================================

/// The wire shape of one share, without the fleet mount rows (which the
/// caller joins from the per-node registry) and without its sessions.
pub fn to_protocol(share: &ShareRow) -> NasShare {
    NasShare {
        share_id: share.share_id.clone(),
        name: share.name.clone(),
        protocol: share.protocol.clone(),
        source_path: share.source_path.clone(),
        dataset: share.dataset.clone(),
        enabled: share.enabled,
        smb: share.smb.clone(),
        nfs: share.nfs.clone(),
        fleet_mount: share.fleet_mount,
        mounts: Vec::new(),
        sessions: 0,
        state: share.state.clone(),
        state_detail: share.state_detail.clone(),
        created_at: share.created_at.clone(),
        updated_at: share.updated_at.clone(),
    }
}

/// Validates the options the wizard sent for the protocol it chose. The NFS
/// networks are the only free-form values that reach a generated config line,
/// so they are checked here rather than at write time.
///
/// `rdma_available` is what this node's RDMA probe said (§5.5a): the "TCP +
/// RDMA" transport may only be stored when the node can actually serve it, so
/// a share can never end up promising a listener that will not open.
/// `smb_direct_available` is the same contract for §5.4b — the ksmbd row of
/// the Environment tab, which also carries the exposure guard, so the option
/// cannot be stored on a node whose only RDMA interface routes the world.
pub fn validate_options(
    protocol: &str,
    smb: &Option<NasSmbOptions>,
    nfs: &Option<NasNfsOptions>,
    rdma_available: bool,
    smb_direct_available: bool,
) -> Result<()> {
    match protocol {
        "smb" => {
            let Some(smb) = smb else {
                return Err(anyhow!("an SMB share needs its SMB options"));
            };
            for grant in &smb.users {
                tentanas_helper::validate_share_user(&grant.user)
                    .map_err(|e| anyhow!(e.to_string()))?;
                if grant.mode != "rw" && grant.mode != "ro" {
                    return Err(anyhow!("unknown access mode '{}'", grant.mode));
                }
            }
            if smb.smb_direct && !smb_direct_available {
                return Err(anyhow!(
                    "this node may not serve SMB Direct — see the ksmbd row of the Environment tab"
                ));
            }
            Ok(())
        }
        "nfs" => {
            let Some(nfs) = nfs else {
                return Err(anyhow!("an NFS share needs its NFS options"));
            };
            for network in &nfs.networks {
                tentanas_helper::validate_nfs_network(network)
                    .map_err(|e| anyhow!(e.to_string()))?;
            }
            if nfs.rdma && !rdma_available {
                return Err(anyhow!(
                    "this node has no usable RDMA device — see the RDMA row of the Environment tab"
                ));
            }
            Ok(())
        }
        other => Err(anyhow!("unknown share protocol '{other}'")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tentaflow_protocol::tentanas::NasShareAccess;

    fn smb_share(smb: NasSmbOptions) -> ShareRow {
        ShareRow {
            share_id: "s1".into(),
            name: "projekty".into(),
            protocol: "smb".into(),
            source_path: "/mnt/tank/projekty".into(),
            dataset: Some("tank/projekty".into()),
            enabled: true,
            fleet_mount: true,
            smb: Some(smb),
            nfs: None,
            state: "active".into(),
            state_detail: String::new(),
            created_at: "2026-09-01T14:00:00Z".into(),
            updated_at: "2026-09-01T14:00:00Z".into(),
        }
    }

    #[test]
    fn a_plain_share_generates_the_minimal_section() {
        let section = smb_section(&smb_share(NasSmbOptions::default()));
        assert_eq!(
            section,
            "[projekty]\n\
             \tpath = /mnt/tank/projekty\n\
             \tbrowseable = yes\n\
             \tread only = no\n\
             \tguest ok = no\n\
             \tcreate mask = 0660\n\
             \tdirectory mask = 2770\n"
        );
        assert!(tentanas_helper::validate_smb_config(&section).is_ok());
    }

    #[test]
    fn the_four_toggles_each_add_exactly_their_own_lines() {
        let all = smb_section(&smb_share(NasSmbOptions {
            guests: true,
            previous_versions: true,
            recycle_bin: true,
            time_machine: true,
            smb_direct: false,
            users: vec![
                NasShareAccess {
                    user: "anna".into(),
                    mode: "rw".into(),
                },
                NasShareAccess {
                    user: "jan".into(),
                    mode: "ro".into(),
                },
            ],
        }));
        assert_eq!(
            all,
            "[projekty]\n\
             \tpath = /mnt/tank/projekty\n\
             \tbrowseable = yes\n\
             \tread only = no\n\
             \tguest ok = yes\n\
             \tforce group = tentanas-share\n\
             \tvalid users = anna, jan\n\
             \twrite list = anna\n\
             \tread list = jan\n\
             \tcreate mask = 0660\n\
             \tdirectory mask = 2770\n\
             \tvfs objects = catia fruit streams_xattr shadow_copy2 recycle\n\
             \tshadow:snapdir = .zfs/snapshot\n\
             \tshadow:sort = desc\n\
             \tshadow:localtime = yes\n\
             \tshadow:snapprefix = ^(auto|manual)$\n\
             \tshadow:delimiter = -\n\
             \tshadow:format = %Y%m%d-%H%M\n\
             \trecycle:repository = .recycle/%U\n\
             \trecycle:keeptree = yes\n\
             \trecycle:versions = yes\n\
             \trecycle:touch = yes\n\
             \tfruit:time machine = yes\n\
             \tfruit:metadata = stream\n\
             \tfruit:model = RackMac\n"
        );
        assert!(tentanas_helper::validate_smb_config(&all).is_ok());

        // Each toggle on its own only brings its own module.
        let versions = smb_section(&smb_share(NasSmbOptions {
            previous_versions: true,
            ..Default::default()
        }));
        assert!(versions.contains("\tvfs objects = shadow_copy2\n"));
        assert!(!versions.contains("recycle:"));
        let recycle = smb_section(&smb_share(NasSmbOptions {
            recycle_bin: true,
            ..Default::default()
        }));
        assert!(recycle.contains("\tvfs objects = recycle\n"));
        assert!(!recycle.contains("shadow:"));
        let machine = smb_section(&smb_share(NasSmbOptions {
            time_machine: true,
            ..Default::default()
        }));
        assert!(machine.contains("\tvfs objects = catia fruit streams_xattr\n"));
        assert!(machine.contains("\tfruit:time machine = yes\n"));
    }

    #[test]
    fn the_generated_document_only_holds_the_shares_of_its_protocol() {
        let nfs = ShareRow {
            share_id: "s2".into(),
            name: "backups".into(),
            protocol: "nfs".into(),
            source_path: "/mnt/tank/backups".into(),
            smb: None,
            nfs: Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                read_only: false,
                root_squash: true,
                async_writes: false,
                rdma: false,
            }),
            fleet_mount: false,
            ..smb_share(NasSmbOptions::default())
        };
        let document = smb_document(&[smb_share(NasSmbOptions::default()), nfs.clone()], &[]);
        assert!(document.contains("[projekty]"));
        assert!(!document.contains("[backups]"));
        assert!(tentanas_helper::validate_smb_config(&document).is_ok());
    }

    #[test]
    fn export_options_follow_the_wizard_toggles() {
        assert_eq!(
            export_options(&NasNfsOptions {
                networks: vec![],
                read_only: false,
                root_squash: true,
                async_writes: false,
                rdma: false,
            }),
            "rw,sync,root_squash,no_subtree_check"
        );
        assert_eq!(
            export_options(&NasNfsOptions {
                networks: vec![],
                read_only: true,
                root_squash: false,
                async_writes: true,
                rdma: false,
            }),
            "ro,async,no_root_squash,no_subtree_check"
        );
    }

    #[test]
    fn the_exports_file_merges_fleet_clients_into_one_line_per_path() {
        let nfs = ShareRow {
            share_id: "s2".into(),
            name: "backups".into(),
            protocol: "nfs".into(),
            source_path: "/mnt/tank/backups".into(),
            smb: None,
            nfs: Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                read_only: false,
                root_squash: true,
                async_writes: false,
                rdma: false,
            }),
            fleet_mount: true,
            ..smb_share(NasSmbOptions::default())
        };
        // An SMB share with fleet_mount is exported over NFS too — that is the
        // whole fleet-mount design.
        let document = exports_document(
            &[smb_share(NasSmbOptions::default()), nfs],
            &["10.10.0.6".to_string(), "10.10.0.7".to_string()],
        );
        let lines: Vec<&str> = document.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(
            lines,
            vec![
                "/mnt/tank/backups 10.10.0.0/24(rw,sync,root_squash,no_subtree_check) 10.10.0.6(rw,sync,root_squash,no_subtree_check) 10.10.0.7(rw,sync,root_squash,no_subtree_check)",
                "/mnt/tank/projekty 10.10.0.6(rw,sync,root_squash,no_subtree_check) 10.10.0.7(rw,sync,root_squash,no_subtree_check)",
            ]
        );
        for line in document.lines() {
            assert!(
                tentanas_helper::validate_export_line(line).is_ok(),
                "{line}"
            );
        }
        // A share the admin's own networks already cover keeps its options for
        // that client instead of getting the fleet ones twice.
        let single = exports_document(
            &[ShareRow {
                nfs: Some(NasNfsOptions {
                    networks: vec!["10.10.0.6".into()],
                    read_only: true,
                    root_squash: true,
                    async_writes: false,
                    rdma: false,
                }),
                protocol: "nfs".into(),
                smb: None,
                fleet_mount: true,
                ..smb_share(NasSmbOptions::default())
            }],
            &["10.10.0.6".to_string()],
        );
        assert!(single.contains("10.10.0.6(ro,sync,root_squash,no_subtree_check)"));
        assert_eq!(single.matches("10.10.0.6(").count(), 1);
    }

    #[test]
    fn an_empty_fleet_and_no_shares_still_produce_a_valid_file() {
        let document = exports_document(&[], &[]);
        assert!(document.lines().all(|l| l.starts_with('#')));
        assert!(tentanas_helper::validate_smb_config(&smb_document(&[], &[])).is_ok());
    }

    fn dataset(name: &str, mountpoint: &str, mounted: bool) -> NasDataset {
        NasDataset {
            name: name.to_string(),
            pool: name.split('/').next().unwrap_or(name).to_string(),
            kind: "filesystem".to_string(),
            mountpoint: Some(mountpoint.to_string()),
            mounted,
            ..Default::default()
        }
    }

    #[test]
    fn the_owning_dataset_is_the_longest_matching_mountpoint() {
        let datasets = vec![
            dataset("tank", "/mnt/tank", true),
            dataset("tank/projekty", "/mnt/tank/projekty", true),
            dataset("fast", "/mnt/fast", false),
        ];
        assert_eq!(
            owning_dataset(&datasets, "/mnt/tank/projekty/dokumenty")
                .map(|d| d.name.as_str()),
            Some("tank/projekty")
        );
        assert_eq!(
            owning_dataset(&datasets, "/mnt/tank/backups").map(|d| d.name.as_str()),
            Some("tank")
        );
        // A prefix that is not a path boundary must not match.
        assert_eq!(owning_dataset(&datasets, "/mnt/tank-old"), None);
        assert_eq!(owning_dataset(&datasets, "/mnt/other"), None);
    }

    #[test]
    fn a_source_outside_every_pool_is_refused_before_anything_is_written() {
        let datasets = vec![dataset("tank", "/mnt/tank", true)];
        assert!(resolve_source(&datasets, "/etc/samba").is_err());
        assert!(resolve_source(&datasets, "/mnt/other/x").is_err());
        assert!(resolve_source(&datasets, "/mnt/../etc").is_err());
    }

    #[test]
    fn state_reports_the_reason_a_share_is_not_exported() {
        let share = smb_share(NasSmbOptions::default());
        let disabled = ShareRow {
            enabled: false,
            ..share.clone()
        };
        assert_eq!(
            share_state(&disabled, &Ok(Source::default_for_test()), &|_| true, None).0,
            "disabled"
        );
        assert_eq!(
            share_state(&share, &Err(anyhow!("'/etc' is not under a pool mountpoint")), &|_| true, None),
            ("error", "'/etc' is not under a pool mountpoint".to_string())
        );
        let unmounted = Source {
            path: "/mnt/tank/projekty".into(),
            dataset: Some("tank/projekty".into()),
            mounted: false,
        };
        assert_eq!(share_state(&share, &Ok(unmounted), &|_| true, None).0, "error");
    }

    #[test]
    fn smbstatus_tree_connects_become_per_share_sessions() {
        let json = r#"{
            "version": "4.19.5",
            "sessions": {
                "31": {"session_id": "31", "username": "anna", "remote_machine": "10.10.0.7"},
                "32": {"session_id": "32", "username": "jan", "remote_machine": "10.10.0.9"}
            },
            "tcons": {
                "1": {"service": "projekty", "session_id": "31", "machine": "10.10.0.7",
                      "connected_at": "2026-09-01T14:00:00+00:00"},
                "2": {"service": "IPC$", "session_id": "31", "machine": "10.10.0.7"},
                "3": {"service": "projekty", "session_id": "32", "machine": "10.10.0.9"}
            }
        }"#;
        let by_share = parse_smbstatus(json);
        assert_eq!(by_share.len(), 1, "IPC$ is not a share");
        let mut sessions = by_share["projekty"].clone();
        sessions.sort_by(|a, b| a.client.cmp(&b.client));
        assert_eq!(sessions.len(), 2);
        assert_eq!(sessions[0].user, "anna");
        assert_eq!(
            sessions[0].connected_at.as_deref(),
            Some("2026-09-01T14:00:00+00:00")
        );
        assert_eq!(sessions[1].user, "jan");
        assert!(parse_smbstatus("not json").is_empty());
    }

    #[test]
    fn an_nfsd_client_document_becomes_one_session() {
        let info = "clientid: 0x6c1a\naddress: \"10.10.0.7:0\"\nstatus: confirmed\nname: \"Linux NFSv4.2 atlas\"\nminor version: 2\n";
        let session = parse_nfs_client_info(info).expect("session");
        assert_eq!(session.client, "10.10.0.7:0");
        assert_eq!(session.user, "Linux NFSv4.2 atlas");
        assert!(parse_nfs_client_info("status: confirmed\n").is_none());
    }

    #[test]
    fn options_are_validated_against_the_protocol_that_was_chosen() {
        assert!(validate_options("smb", &Some(NasSmbOptions::default()), &None, false, false).is_ok());
        assert!(validate_options("smb", &None, &None, false, false).is_err());
        assert!(validate_options(
            "smb",
            &Some(NasSmbOptions {
                users: vec![NasShareAccess {
                    user: "anna".into(),
                    mode: "write".into()
                }],
                ..Default::default()
            }),
            &None,
            false,
            false
        )
        .is_err());
        assert!(validate_options(
            "nfs",
            &None,
            &Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                ..Default::default()
            }),
            false,
            false
        )
        .is_ok());
        assert!(validate_options(
            "nfs",
            &None,
            &Some(NasNfsOptions {
                networks: vec!["10.10.0.0/33".into()],
                ..Default::default()
            }),
            false,
            false
        )
        .is_err());
        assert!(validate_options("iscsi", &None, &None, false, false).is_err());
    }

    #[test]
    fn the_rdma_transport_is_refused_on_a_node_whose_probe_says_no() {
        let rdma = |on: bool| {
            Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                rdma: on,
                ..Default::default()
            })
        };
        // A node that can serve it stores it.
        assert!(validate_options("nfs", &None, &rdma(true), true, false).is_ok());
        // A node that cannot says why instead of storing a share that would
        // advertise a listener nfsd will never open.
        let refused = validate_options("nfs", &None, &rdma(true), false, false).expect_err("refused");
        assert!(refused.to_string().contains("RDMA"), "{refused}");
        // TCP is unaffected either way — the probe only gates the upgrade.
        assert!(validate_options("nfs", &None, &rdma(false), false, false).is_ok());
    }

    #[test]
    fn the_rdma_listener_follows_the_shares_that_asked_for_it() {
        let tcp = ShareRow {
            protocol: "nfs".into(),
            smb: None,
            nfs: Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                ..Default::default()
            }),
            ..smb_share(NasSmbOptions::default())
        };
        let rdma = ShareRow {
            nfs: Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                rdma: true,
                ..Default::default()
            }),
            ..tcp.clone()
        };
        assert!(!wants_rdma(&[]));
        assert!(!wants_rdma(&[tcp.clone()]));
        // An SMB share never turns the listener on by itself.
        assert!(!wants_rdma(&[smb_share(NasSmbOptions::default())]));
        // One share is enough: the listener belongs to the server.
        assert!(wants_rdma(&[tcp, rdma]));
    }

    #[test]
    fn the_transport_never_reaches_the_export_line() {
        // `rdma=y` lives in nfs.conf, not in the exports file: an export is
        // transport-agnostic and adding an option there would be refused by
        // the catalog's own parser.
        let share = ShareRow {
            protocol: "nfs".into(),
            smb: None,
            nfs: Some(NasNfsOptions {
                networks: vec!["10.10.0.0/24".into()],
                rdma: true,
                ..Default::default()
            }),
            fleet_mount: false,
            ..smb_share(NasSmbOptions::default())
        };
        let document = exports_document(&[share], &[]);
        assert!(!document.contains("rdma"), "{document}");
        for line in document.lines() {
            assert!(tentanas_helper::validate_export_line(line).is_ok(), "{line}");
        }
    }

    #[test]
    fn the_include_gains_a_global_block_only_when_ksmbd_takes_an_interface() {
        let share = smb_share(NasSmbOptions::default());
        // No SMB Direct anywhere: smbd keeps its own listener defaults and the
        // app leaves nothing in [global] at all.
        let plain = smb_document(&[share.clone()], &[]);
        assert!(!plain.contains("[global]"), "{plain}");
        assert!(!plain.contains("bind interfaces only"));
        assert!(tentanas_helper::validate_smb_config(&plain).is_ok());

        // ksmbd took an interface: Samba is pinned to everything else, and the
        // block sits BEFORE the share sections so it is still in [global] when
        // smbd reads it.
        let taken = "tfrdmatest0".to_string();
        let split = smb_document(&[share], std::slice::from_ref(&taken));
        let global = split.find("[global]").expect("the listener block");
        assert!(global < split.find("[projekty]").expect("the share"));
        assert!(split.contains("\n\tbind interfaces only = yes\n"), "{split}");
        // Loopback is always kept: without it smbpasswd and smbstatus, which
        // this app runs against the local smbd, stop reaching it.
        assert!(split.contains("\tinterfaces = lo"), "{split}");
        assert!(!split.contains(&taken), "the RDMA interface is what smbd gives up");
        assert!(tentanas_helper::validate_smb_config(&split).is_ok());
    }

    #[test]
    fn a_share_refused_smb_direct_stays_active_and_carries_the_reason() {
        let direct = smb_share(NasSmbOptions {
            smb_direct: true,
            ..Default::default()
        });
        let plain = smb_share(NasSmbOptions::default());
        let refusal = "SMB Direct is not served on this node: enp3s0 192.168.1.20 also carries the default gateway";

        // Samba keeps exporting it — the LAN half of the share is unaffected —
        // but the option that did not take effect is never silent.
        let (state, detail) = share_state(&direct, &Ok(Source::default_for_test()), &|_| true, Some(refusal));
        assert_eq!(state, "active");
        assert_eq!(detail, refusal);

        // A share that never asked for SMB Direct is untouched by the refusal.
        assert_eq!(
            share_state(&plain, &Ok(Source::default_for_test()), &|_| true, Some(refusal)),
            ("active", String::new())
        );
        // And a node that can serve it reports nothing.
        assert_eq!(
            share_state(&direct, &Ok(Source::default_for_test()), &|_| true, None),
            ("active", String::new())
        );
        // A hard error still wins: an unmounted source keeps the share out of
        // BOTH configs, which is a different and worse problem.
        let unmounted = Source {
            path: "/mnt/tank/projekty".into(),
            dataset: Some("tank/projekty".into()),
            mounted: false,
        };
        assert_eq!(share_state(&direct, &Ok(unmounted), &|_| true, Some(refusal)).0, "error");
    }

    #[test]
    fn smb_direct_is_refused_on_a_node_whose_ksmbd_row_says_no() {
        let direct = |on: bool| {
            Some(NasSmbOptions {
                smb_direct: on,
                ..Default::default()
            })
        };
        assert!(validate_options("smb", &direct(true), &None, false, true).is_ok());
        let refused =
            validate_options("smb", &direct(true), &None, false, false).expect_err("refused");
        assert!(refused.to_string().contains("SMB Direct"), "{refused}");
        // The plain SMB share is unaffected: the gate only guards the upgrade.
        assert!(validate_options("smb", &direct(false), &None, false, false).is_ok());
        // The two transports are independent gates.
        assert!(validate_options("smb", &direct(true), &None, true, false).is_err());
    }

    #[test]
    fn the_two_backends_generate_from_the_same_row() {
        // One `nas_shares` row, two configs: the grants and the path are the
        // same in both, and only Samba carries the module options.
        let share = smb_share(NasSmbOptions {
            smb_direct: true,
            previous_versions: true,
            users: vec![NasShareAccess {
                user: "anna".into(),
                mode: "rw".into(),
            }],
            ..Default::default()
        });
        let samba = smb_section(&share);
        let ksmbd = super::super::ksmbd::ksmbd_section(&share);
        for common in [
            "\tpath = /mnt/tank/projekty\n",
            "\tvalid users = anna\n",
            "\twrite list = anna\n",
            "\tcreate mask = 0660\n",
        ] {
            assert!(samba.contains(common), "{common} missing from samba");
            assert!(ksmbd.contains(common), "{common} missing from ksmbd");
        }
        assert!(samba.contains("shadow_copy2"));
        assert!(!ksmbd.contains("shadow_copy2"), "ksmbd has no such module");
    }

    impl Source {
        fn default_for_test() -> Self {
            Self {
                path: "/mnt/tank/projekty".into(),
                dataset: Some("tank/projekty".into()),
                mounted: true,
            }
        }
    }
}
