# =============================================================================
# File: executor/run_perf.py — executes perf items: runs Locust headless in a
# subprocess over a generated wrapper locustfile (network guard installed
# before the user script is imported), then parses the CSV stats into
# PerfStats per endpoint + a downsampled timeline.
# =============================================================================

from __future__ import annotations

import csv
import os
import sys
from pathlib import Path
from typing import TYPE_CHECKING, List, Optional

from .junit import ItemOutcome, StepState, truncate_message

if TYPE_CHECKING:
    from .job import ItemContext

# Locust imports the wrapper AFTER gevent monkey-patching, so the guard wraps
# gevent's socket layer — every HttpUser request goes through the allowlist.
LOCUSTFILE_TEMPLATE = '''\
# Generated by TentaFlow test-runner — do not edit. Installs the network
# guard, then re-exports the user's HttpUser classes for locust discovery.
from executor.sandbox_net import install_socket_guard

install_socket_guard()

from user_locust import *  # noqa: F401,F403
'''

DEFAULT_USERS = 10
DEFAULT_DURATION_SECS = 30
MIN_DURATION_SECS = 5
MAX_DURATION_SECS = 3600
MAX_USERS = 2000


def _clamp(value, low, high):
    return max(low, min(high, value))


def _float(row: dict, key: str, default: float = 0.0) -> float:
    try:
        return float(row.get(key, default) or default)
    except (TypeError, ValueError):
        return default


def _int(row: dict, key: str, default: int = 0) -> int:
    try:
        return int(float(row.get(key, default) or default))
    except (TypeError, ValueError):
        return default


def _parse_summary(stats_path: Path) -> List[dict]:
    if not stats_path.is_file():
        return []
    summary = []
    with stats_path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            name = (row.get("Name") or "").strip()
            if not name:
                continue
            method = (row.get("Type") or "").strip()
            endpoint = f"{method} {name}".strip() if name != "Aggregated" else "Aggregated"
            summary.append(
                {
                    "endpoint": endpoint,
                    "requests": _int(row, "Request Count"),
                    "failures": _int(row, "Failure Count"),
                    "rps": _float(row, "Requests/s"),
                    "p50_ms": _float(row, "50%"),
                    "p90_ms": _float(row, "90%"),
                    "p99_ms": _float(row, "99%"),
                    "avg_ms": _float(row, "Average Response Time"),
                    "min_ms": _float(row, "Min Response Time"),
                    "max_ms": _float(row, "Max Response Time"),
                }
            )
    return summary


def _parse_timeline(history_path: Path, sample_secs: int) -> List[dict]:
    if not history_path.is_file():
        return []
    timeline = []
    base_ts: Optional[int] = None
    last_kept: Optional[int] = None
    with history_path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if (row.get("Name") or "").strip() != "Aggregated":
                continue
            ts = _int(row, "Timestamp")
            if base_ts is None:
                base_ts = ts
            ts_s = ts - base_ts
            if last_kept is not None and ts_s - last_kept < sample_secs:
                continue
            last_kept = ts_s
            timeline.append(
                {
                    "ts_s": ts_s,
                    "rps": _float(row, "Requests/s"),
                    "p90_ms": _float(row, "90%"),
                    "failures": _int(row, "Total Failure Count"),
                    "users": _int(row, "User Count"),
                }
            )
    return timeline


def run(ctx: "ItemContext") -> ItemOutcome:
    script = ctx.content.get("script")
    if not isinstance(script, str) or not script.strip():
        return ItemOutcome(status="error", message="item content has no script")

    profile = ctx.content.get("profile") or ctx.config.get("profile") or {}
    users = _clamp(int(profile.get("users", DEFAULT_USERS) or DEFAULT_USERS), 1, MAX_USERS)
    spawn_rate = _clamp(
        float(profile.get("spawn_rate", users) or users), 0.1, float(MAX_USERS)
    )
    duration = _clamp(
        int(profile.get("duration_secs", DEFAULT_DURATION_SECS) or DEFAULT_DURATION_SECS),
        MIN_DURATION_SECS,
        MAX_DURATION_SECS,
    )

    (ctx.workdir / "user_locust.py").write_text(script, encoding="utf-8")
    (ctx.workdir / "locustfile.py").write_text(LOCUSTFILE_TEMPLATE, encoding="utf-8")

    # CSV files go straight into the artifacts dir so they are collected and
    # downloadable (kind perf_stats).
    csv_prefix = ctx.artifacts_dir / "perf"
    cmd = [
        sys.executable,
        "-m",
        "locust",
        "-f",
        "locustfile.py",
        "--headless",
        "-u",
        str(users),
        "-r",
        str(spawn_rate),
        "-t",
        f"{duration}s",
        "--csv",
        str(csv_prefix),
        "--csv-full-history",
        "--loglevel",
        "WARNING",
    ]
    base_url = ctx.env.get("TF_BASE_URL", "")
    if base_url:
        cmd += ["--host", base_url]

    sub = ctx.run(cmd, log_name="console.log")

    if sub.cancelled:
        return ItemOutcome(status="error", message="cancelled")
    if sub.timed_out:
        return ItemOutcome(
            status="error", message=f"item timed out after {ctx.timeout_secs}s"
        )

    sample_secs = max(1, int(os.environ.get("TEST_RUNNER_PERF_SAMPLE_SECS", "1")))
    summary = _parse_summary(Path(f"{csv_prefix}_stats.csv"))
    timeline = _parse_timeline(Path(f"{csv_prefix}_stats_history.csv"), sample_secs)

    # Locust exits 1 when some requests failed; the load run itself still
    # completed, so failures are reported through the stats, not the status.
    if sub.returncode not in (0, 1) or not summary:
        return ItemOutcome(
            status="error",
            message=truncate_message(
                f"locust exited with code {sub.returncode} and produced "
                f"{'no' if not summary else 'partial'} stats"
            ),
            perf_summary=summary,
            perf_timeline=timeline,
        )

    aggregated = next(
        (row for row in summary if row["endpoint"] == "Aggregated"), summary[-1]
    )
    step_message = (
        f"{aggregated['requests']} requests, {aggregated['failures']} failures, "
        f"{aggregated['rps']:.1f} rps, p90 {aggregated['p90_ms']:.0f} ms"
    )
    status = "passed" if sub.returncode == 0 else "failed"
    return ItemOutcome(
        status=status,
        message="" if status == "passed" else step_message,
        steps=[
            StepState(
                index=0,
                name=f"locust {users}u/{duration}s",
                status=status,
                message=step_message,
            )
        ],
        perf_summary=summary,
        perf_timeline=timeline,
    )
