// ===== File: baseline.rs — ratcheting allowance list for known violations =====

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Allowance for one (rule, file) pair.
///
/// The list exists so the gates can be red for today's repository without
/// blocking every commit, and it ratchets: an entry whose file improved past
/// the recorded value is reported as stale and must be lowered. Without the
/// stale check the list would only ever grow, which is how a lint stops meaning
/// anything.
pub type Baseline = BTreeMap<(String, String), usize>;

pub const FILE: &str = "xtask/baseline.tsv";

pub fn load(root: &Path) -> Baseline {
    let mut map = Baseline::new();
    let text = match fs::read_to_string(root.join(FILE)) {
        Ok(t) => t,
        Err(_) => return map,
    };
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split('\t');
        let (Some(rule), Some(path), Some(allowed)) = (parts.next(), parts.next(), parts.next())
        else {
            continue;
        };
        if let Ok(allowed) = allowed.trim().parse::<usize>() {
            map.insert((rule.to_string(), path.to_string()), allowed);
        }
    }
    map
}

pub fn allowance(baseline: &Baseline, rule: &str, path: &str, default: usize) -> usize {
    baseline
        .get(&(rule.to_string(), path.to_string()))
        .copied()
        .unwrap_or(default)
}

pub fn write(root: &Path, entries: &Baseline) -> std::io::Result<()> {
    let mut out = String::new();
    out.push_str("# Known violations, one per (rule, file). Generated by `cargo xtask lint --update-baseline`.\n");
    out.push_str(
        "# This list may only shrink. A value better than recorded is reported as stale,\n",
    );
    out.push_str("# which is the mechanism that makes the gates tighten over time.\n");
    out.push_str("# rule\tpath\tallowed\n");
    for ((rule, path), allowed) in entries {
        out.push_str(&format!("{rule}\t{path}\t{allowed}\n"));
    }
    fs::create_dir_all(root.join("xtask"))?;
    fs::write(root.join(FILE), out)
}
