// =============================================================================
// Plik: build.rs
// Opis: Auto-generacja C/C++ headera `tentaflow_client.h` z cbindgen (Task #40).
//       Uruchamia sie przy kazdym cargo build i produkuje header obok .rlib.
//       .NET (C# P/Invoke) importuje symbole z tego headera przez dotnet-native.
// =============================================================================

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    let out_header = PathBuf::from(&out_dir).join("tentaflow_client.h");
    let include_header = PathBuf::from(&crate_dir).join("include").join("tentaflow_client.h");

    // Rerun hints — kazda zmiana w src/ffi.rs lub types.rs regeneruje header.
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=src/types.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        header: Some(
            "/* =====================================================================\n\
             * tentaflow_client.h — Auto-generated by cbindgen from tentaflow-client-native.\n\
             * DO NOT EDIT. Source of truth: src/ffi.rs + src/types.rs.\n\
             * Regenerate: cargo build (build.rs auto-runs cbindgen).\n\
             * ===================================================================== */\n\
             #ifndef TENTAFLOW_CLIENT_H\n#define TENTAFLOW_CLIENT_H"
                .to_string(),
        ),
        trailer: Some("#endif /* TENTAFLOW_CLIENT_H */".to_string()),
        include_guard: None, // mamy w header+trailer wyzej
        cpp_compat: true,
        pragma_once: false,
        autogen_warning: Some("/* AUTOGENERATED — zmieniaj w src/ffi.rs + cargo build. */".to_string()),
        documentation: true,
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            // Pisz do OUT_DIR (zwykla cargo build output) + do include/ (dla .NET wrappera).
            bindings.write_to_file(&out_header);
            std::fs::create_dir_all(include_header.parent().unwrap()).ok();
            bindings.write_to_file(&include_header);
            println!(
                "cargo:warning=cbindgen: wygenerowano {} i {}",
                out_header.display(),
                include_header.display()
            );
        }
        Err(e) => {
            // Nie failuj buildu jesli cbindgen ma problem z parse — header pozostanie stary.
            println!("cargo:warning=cbindgen nie udal sie: {}", e);
        }
    }
}
