// ===== File: lib.rs — raw FFI bindings to the zvec C API =====
//
// Generated by bindgen from `vendor/include/zvec/c_api.h` at build time. This crate
// is the unsafe `-sys` layer; the safe wrapper + `VectorBackend` impl live in
// tentaflow-core (`services::vector::zvec_backend`).
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    // Proves the vendored static archive links and the zvec runtime initializes.
    #[test]
    fn check_version_links_and_runs() {
        let ok = unsafe { zvec_check_version(0, 1, 0) };
        assert!(ok, "zvec_check_version(0,1,0) should return true");
    }
}
