// ===== File: flavour.rs — Whisper checkpoint flavours: names, dims, layout =====
//
// The same Whisper model ships in two conversions that agree on the maths and
// disagree on everything else: HF transformers naming with an HF config schema,
// and the OpenAI naming that mlx-whisper keeps, with OpenAI's config keys.
// Three differences are semantic, not cosmetic, and each one is a silent wrong
// answer if missed:
//
//   1. the encoder positional embedding is STORED by HF and GENERATED by MLX
//      (fixed sinusoids), so a loader that only looks it up finds nothing;
//   2. convolution weights are [out, in, k] in HF and [out, k, in] in MLX;
//   3. MLX linear weights are quantized triples, HF ones are plain f16.
//
// Everything else is a name, and names live in the table below rather than in
// branches spread through the loader.

use forge_types::{ForgeError, Result};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WhisperFlavour {
    /// `model.encoder.layers.N.self_attn.q_proj.weight`, config in HF keys.
    HfTransformers,
    /// `encoder.blocks.N.attn.query.weight`, config in OpenAI keys, quantized.
    MlxOpenAi,
}

/// Tensor-name fragments for one flavour. Data, not code: adding a third
/// conversion is a new constant, not a new branch in the loader.
pub struct Names {
    pub enc_block: &'static str,
    pub dec_block: &'static str,
    pub self_attn: &'static str,
    pub self_attn_ln: &'static str,
    pub cross_attn: &'static str,
    pub cross_attn_ln: &'static str,
    pub mlp_ln: &'static str,
    pub q: &'static str,
    pub k: &'static str,
    pub v: &'static str,
    pub o: &'static str,
    pub fc1: &'static str,
    pub fc2: &'static str,
    pub conv1: &'static str,
    pub conv2: &'static str,
    pub enc_ln: &'static str,
    pub dec_ln: &'static str,
    pub tok_emb: &'static str,
    pub dec_pos: &'static str,
    /// `None` means the encoder positions are not stored and must be generated.
    pub enc_pos: Option<&'static str>,
    /// Convolution weight axis order as stored.
    pub conv_layout: ConvLayout,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConvLayout {
    /// [out_channels, in_channels, kernel]
    OutInK,
    /// [out_channels, kernel, in_channels]
    OutKIn,
}

const HF_NAMES: Names = Names {
    enc_block: "model.encoder.layers",
    dec_block: "model.decoder.layers",
    self_attn: "self_attn",
    self_attn_ln: "self_attn_layer_norm",
    cross_attn: "encoder_attn",
    cross_attn_ln: "encoder_attn_layer_norm",
    mlp_ln: "final_layer_norm",
    q: "q_proj",
    k: "k_proj",
    v: "v_proj",
    o: "out_proj",
    fc1: "fc1",
    fc2: "fc2",
    conv1: "model.encoder.conv1",
    conv2: "model.encoder.conv2",
    enc_ln: "model.encoder.layer_norm",
    dec_ln: "model.decoder.layer_norm",
    tok_emb: "model.decoder.embed_tokens.weight",
    dec_pos: "model.decoder.embed_positions.weight",
    enc_pos: Some("model.encoder.embed_positions.weight"),
    conv_layout: ConvLayout::OutInK,
};

const MLX_NAMES: Names = Names {
    enc_block: "encoder.blocks",
    dec_block: "decoder.blocks",
    self_attn: "attn",
    self_attn_ln: "attn_ln",
    cross_attn: "cross_attn",
    cross_attn_ln: "cross_attn_ln",
    mlp_ln: "mlp_ln",
    q: "query",
    k: "key",
    v: "value",
    o: "out",
    fc1: "mlp1",
    fc2: "mlp2",
    conv1: "encoder.conv1",
    conv2: "encoder.conv2",
    enc_ln: "encoder.ln_post",
    dec_ln: "decoder.ln",
    tok_emb: "decoder.token_embedding.weight",
    dec_pos: "decoder.positional_embedding",
    enc_pos: None,
    conv_layout: ConvLayout::OutKIn,
};

impl WhisperFlavour {
    pub fn names(self) -> &'static Names {
        match self {
            WhisperFlavour::HfTransformers => &HF_NAMES,
            WhisperFlavour::MlxOpenAi => &MLX_NAMES,
        }
    }

    /// Decides the flavour from config.json. The two schemas share no dimension
    /// key, so the choice is unambiguous and never a heuristic on file names.
    pub fn detect(config: &serde_json::Value) -> Result<Self> {
        if config.get("d_model").is_some() {
            return Ok(WhisperFlavour::HfTransformers);
        }
        if config.get("n_audio_state").is_some() {
            return Ok(WhisperFlavour::MlxOpenAi);
        }
        Err(ForgeError::Format(
            "whisper config.json: ani `d_model` (HF), ani `n_audio_state` (MLX)".into(),
        ))
    }
}

/// Dimensions in OpenAI's config keys, as mlx-whisper writes them.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct OpenAiDims {
    pub n_mels: usize,
    pub n_audio_ctx: usize,
    pub n_audio_state: usize,
    pub n_audio_head: usize,
    pub n_audio_layer: usize,
    pub n_vocab: usize,
    pub n_text_ctx: usize,
    pub n_text_state: usize,
    pub n_text_head: usize,
    pub n_text_layer: usize,
}

impl OpenAiDims {
    /// Feed-forward width. Whisper fixes it at 4x the model width in every
    /// released size; the loader still checks the stored tensor against this,
    /// so a checkpoint that broke the rule fails loudly instead of quietly.
    pub fn ffn(width: usize) -> usize {
        width * 4
    }
}

/// Fixed sinusoidal positional embedding, the one OpenAI computes instead of
/// storing. Same formula as the reference implementation: the first half of the
/// channels are sines, the second half cosines, over a log-spaced frequency
/// range with 10 000 as the maximum timescale.
pub fn sinusoids(length: usize, channels: usize) -> Result<Vec<f32>> {
    if !channels.is_multiple_of(2) {
        return Err(ForgeError::Format(format!(
            "whisper: sinusoidy wymagają parzystej liczby kanałów, jest {channels}"
        )));
    }
    let half = channels / 2;
    let log_timescale_increment = (10_000f32).ln() / (half - 1) as f32;
    let mut out = vec![0f32; length * channels];
    for pos in 0..length {
        for i in 0..half {
            let inv_timescale = (-log_timescale_increment * i as f32).exp();
            let scaled = pos as f32 * inv_timescale;
            out[pos * channels + i] = scaled.sin();
            out[pos * channels + half + i] = scaled.cos();
        }
    }
    Ok(out)
}

/// Rewrites a convolution weight into [out, in, k] regardless of how it was
/// stored. A transposed convolution kernel produces no error and no NaN — just
/// a model that mishears everything.
pub fn conv_to_out_in_k(
    values: &[f32],
    out_ch: usize,
    in_ch: usize,
    kernel: usize,
    layout: ConvLayout,
) -> Vec<f32> {
    match layout {
        ConvLayout::OutInK => values.to_vec(),
        ConvLayout::OutKIn => {
            let mut dst = vec![0f32; values.len()];
            for o in 0..out_ch {
                for k in 0..kernel {
                    for i in 0..in_ch {
                        dst[(o * in_ch + i) * kernel + k] = values[(o * kernel + k) * in_ch + i];
                    }
                }
            }
            dst
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flavour_is_decided_by_config_keys_not_by_guesswork() {
        let hf = serde_json::json!({"d_model": 1280, "encoder_layers": 32});
        assert_eq!(
            WhisperFlavour::detect(&hf).unwrap(),
            WhisperFlavour::HfTransformers
        );

        let mlx = serde_json::json!({"n_audio_state": 1280, "n_audio_layer": 32});
        assert_eq!(
            WhisperFlavour::detect(&mlx).unwrap(),
            WhisperFlavour::MlxOpenAi
        );

        assert!(WhisperFlavour::detect(&serde_json::json!({"model_type": "whisper"})).is_err());
    }

    #[test]
    fn sinusoids_match_the_reference_formula_at_the_edges() {
        let s = sinusoids(4, 8).unwrap();
        // Position zero: sin(0) = 0 for the whole first half, cos(0) = 1 for the second.
        for i in 0..4 {
            assert_eq!(s[i], 0.0);
            assert_eq!(s[4 + i], 1.0);
        }
        // Channel zero has inverse timescale 1, so it is sin(pos) exactly.
        for pos in 0..4 {
            assert!((s[pos * 8] - (pos as f32).sin()).abs() < 1e-6, "pos {pos}");
        }
        assert!(sinusoids(4, 7).is_err(), "nieparzysta liczba kanałów");
    }

    #[test]
    fn conv_transpose_moves_the_kernel_axis_to_the_end() {
        // out=2, in=3, k=2 stored as [out, k, in].
        let stored = vec![
            // o=0: k=0 -> in 0,1,2 ; k=1 -> in 0,1,2
            0.0, 1.0, 2.0, 10.0, 11.0, 12.0, // o=1
            100.0, 101.0, 102.0, 110.0, 111.0, 112.0,
        ];
        let got = conv_to_out_in_k(&stored, 2, 3, 2, ConvLayout::OutKIn);
        // Expected [out, in, k]: o=0 -> (in0: k0,k1), (in1: k0,k1), (in2: k0,k1)
        assert_eq!(
            got,
            vec![0.0, 10.0, 1.0, 11.0, 2.0, 12.0, 100.0, 110.0, 101.0, 111.0, 102.0, 112.0]
        );

        let passthrough = conv_to_out_in_k(&stored, 2, 3, 2, ConvLayout::OutInK);
        assert_eq!(passthrough, stored);
    }
}
