[package]
name = "tentaflow-addon-tentavision"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tentaflow-sdk-spec = { workspace = true }
minicbor = { workspace = true, features = ["alloc"] }
serde_json = { workspace = true, features = ["alloc"] }
base64 = { workspace = true }
