// Auto-generated by tentaflow-sdk-gen — DO NOT EDIT
// Regenerate: ./scripts/gen-rust.sh
//
// Typed UI catalog v1 bindings for Rust addons. Every catalog component,
// token enum, inline struct and tagged union is re-exported here from
// `tentaflow-sdk-spec` — the canonical encoders all SDKs are byte-compared
// against. NOTE: the catalog `Box` layout component shadows `std::boxed::Box`
// under a glob import; alias the module (`use ...::ui_v1 as ui;`) when the
// same scope also needs the std pointer type.

pub use tentaflow_sdk_spec::protocol::control::{
    BackpressureSeverity, CborMap, GrantRationale, RateLimitScope, RejectReason, ResumeMode,
    ResumeStatus, SessionEndCode,
};
pub use tentaflow_sdk_spec::protocol::ui::a11y::{
    Accessibility, EventKind, Visibility,
};
pub use tentaflow_sdk_spec::protocol::ui::action::{
    Action, ActionAck, ActionStatus, FieldError, FormFieldMap, FormFieldValue, ParamEntry,
};
pub use tentaflow_sdk_spec::protocol::ui::actions::{
    ActionBar, Button, ButtonGroup, Fab, FilterChips, IconButton, Link, LinkButton, Menu,
    MenuButton, SegmentedControl, WizardFooter,
};
pub use tentaflow_sdk_spec::protocol::ui::bind::{
    BindRef, BindSpec, MAX_STATE_PATH_SEGMENTS, PathSegment, StatePath,
};
pub use tentaflow_sdk_spec::protocol::ui::command::{
    Command,
};
pub use tentaflow_sdk_spec::protocol::ui::component::{
    Component, FieldMap, HandlerMap, TEST_ID_MAX_LEN, TestId, TestIdError,
};
pub use tentaflow_sdk_spec::protocol::ui::data::{
    AreaChart, Avatar, AvatarGroup, Badge, BarChart, BulletList, CalendarMonth, Chip,
    CodeBlock, DataDefinitionList, Diff, EmptyCell, Gauge, Heading, Heatmap, Image,
    JsonViewer, KeyValue, LineChart, List, LiveRegionComponent, Markdown, MonoBlock,
    Paragraph, PieChart, ProgressBar, RatingDisplay, RichText, Sparkline, StackedBar, Stat,
    StatCard, Table, Tag, Text, Timeline, Tree, VisuallyHidden,
};
pub use tentaflow_sdk_spec::protocol::ui::error_code::{
    ErrorCode,
};
pub use tentaflow_sdk_spec::protocol::ui::event::{
    Event, Topic, TopicSegment,
};
pub use tentaflow_sdk_spec::protocol::ui::feedback::{
    Alert, Banner, Callout, ConfirmationDialog, Drawer, GateScreen, Hint, LoadingBar, Modal,
    OfflineBanner, Popover, Sheet, Skeleton, Spinner, Toast,
};
pub use tentaflow_sdk_spec::protocol::ui::form::{
    Autocomplete, Checkbox, ColorPicker, Combobox, CurrencyInput, DatePicker,
    DateRangePicker, DateTimePicker, FileInput, Form, FormField, FormGroup, FormSection,
    FormValidator, Input, MentionInput, MultiSelect, NumericInput, Radio, RadioCardGroup,
    RadioGroup, RangeSlider, SearchBox, Select, Slider, SliderRow, TagInput, Textarea,
    TimePicker, Toggle,
};
pub use tentaflow_sdk_spec::protocol::ui::handler::{
    DEBOUNCE_MAX_MS, FailurePolicy, HANDLER_MAX_RECURSION_DEPTH, HANDLER_MAX_TOTAL_STEPS,
    Handler, HandlerValidationError, LocalAction, SEQUENCE_MAX_ITEMS,
};
pub use tentaflow_sdk_spec::protocol::ui::icon_name::{
    IconName,
};
pub use tentaflow_sdk_spec::protocol::ui::inline::{
    AccordionItem, AlarmItem, AspectRatio, AvatarRef, BorderEdges, BorderSide, BorderToken,
    BoxStyle, BreadcrumbItem, ChartAxis, ChartLegend, ChartSeries, ChartTooltip,
    ContainerWidth, CornerValues, DatePreset, DatePresetResolve, DecisionOption, DefItem,
    DimensionToken, EdgeValues, FeatureItem, FileMeta, FilterChipDef, Footnote,
    GaugeThreshold, GraphEdge, GraphNode, GridChild, GridCol, GridTrack, HeatmapBucket,
    HeatmapColumn, HeatmapRow, HeatmapScale, IconRef, InboxItem, InlineBadge, InlineChip,
    KvItem, LogEvent, MapMarker, MenuItem, NavTab, PermissionDef, RadioCardOption,
    RadioOption, RadiusValue, RangePreset, RangePresetRange, ResponsiveRule, RoleDef,
    SegmentOption, SelectGroup, SelectOption, SelectValue, SidebarItem, SliderMark,
    SpaceValue, SplitSize, StackSegment, StepDef, TabItem, TableColumn, TableColumnWidth,
    TablePagination, TableSort, TimelineItem, Trend, TrendDirection,
};
pub use tentaflow_sdk_spec::protocol::ui::layout::{
    Accordion, Box, Breadcrumb, Card, Cluster, Collapsible, Divider, Flex, Grid, NavTabs,
    Pagination, ScrollContainer, SectionCard, Sidebar, Spacer, Split, Stack, Tabs, Tooltip,
};
pub use tentaflow_sdk_spec::protocol::ui::molecules::{
    AppShell, EmptyState, ErrorBoundary, Header, Inspector, LoginShell, PageHeader,
    SectionHeader, StatGroup, Toolbar, WelcomeHero, WizardShell,
};
pub use tentaflow_sdk_spec::protocol::ui::panel::{
    CloseReason, PanelClose, PanelError, PanelOpen, PanelOpenContext, PanelReady,
    PanelReset, PanelShell, Viewport,
};
pub use tentaflow_sdk_spec::protocol::ui::patch::{
    PatchOp, PatchOpKind,
};
pub use tentaflow_sdk_spec::protocol::ui::slot::{
    CachePolicy, SlotDecl, SlotDefault, SlotSemantics, SlotVisibility, StateEntry,
};
pub use tentaflow_sdk_spec::protocol::ui::slot_msg::{
    SlotClear, SlotContent, SlotHide, SlotShow,
};
pub use tentaflow_sdk_spec::protocol::ui::specialized::{
    Audio, AudioCapture, Carousel, CodeEditor, FpsCounter, IFrame, ImageGallery,
    LiveCameraTile, MapView, PdfViewer, StepProgress, Stopwatch, Terminal, VideoStream,
    VirtualizedLog,
};
pub use tentaflow_sdk_spec::protocol::ui::state::{
    PatchRejectReason, PatchRejected, StatePatch, StateReset, StateSnapshot,
};
pub use tentaflow_sdk_spec::protocol::ui::tokens::{
    AccordionMode, AlertVariant, AreaStacking, AudioCaptureMode, AudioCaptureVariant,
    AudioControls, AudioVariant, AutocompleteHint, AvatarOverlap, AvatarShape, AvatarSize,
    AvatarStatus, BackgroundToken, BadgeVariant, BannerPosition, BarStacking, BorderColor,
    BorderLineStyle, BreadcrumbSeparator, Breakpoint, BulletListVariant,
    ButtonGroupOrientation, ButtonSize, ButtonVariant, CameraStatus, CardVariant,
    CarouselGestures, ChartAxisScale, ChartLegendAlign, ChartLegendPosition,
    ChartOrientation, ChartSeriesStyle, ChartZoomMode, CheckboxSize, ChipVariant,
    CodeEditorTheme, ColorPickerVariant, ColorToken, ColumnRender, CursorToken, DayOfWeek,
    Density, DiffVariant, DividerOrientation, DividerVariant, DlLayout, DrawerSide,
    DrawerSize, EmptyCellVariant, EmptyStateVariant, FabPosition, FabSize, FileCapture,
    FileUploadStatus, FilterChipsMode, FlexAlign, FlexDirection, FlexJustify, FlexWrap,
    FormFieldLayout, FormLayout, FpsVariant, GateVariant, GaugeVariant,
    HeatmapLegendPosition, IFrameReferrerPolicy, IFrameSandbox, IconSize, ImageFit,
    InputMode, InputSize, InputType, InputVariant, KvLayout, LinkTarget, LinkUnderline,
    LiveRegion, LogLevel, LogVariant, MarkdownBlock, MarkdownFeature, MarkdownMark,
    MenuPlacement, ModalSize, NavTabsVariant, NavigateTarget, Overflow, PaginationVariant,
    PdfZoomMode, PieVariant, PopoverPlacement, ProgressSize, ProgressVariant,
    RadioCardVariant, RadioGroupOrientation, RadiusToken, RatingPrecision, RatingVariant,
    ScrollBehavior, ScrollOrientation, SearchVariant, SegmentSize, ShadowToken, SheetDetent,
    SkeletonVariant, SliderRowLayout, SortDirection, SpacerAxis, Spacing, SparklineVariant,
    SpinnerSize, SpinnerVariant, SplitDivider, SplitOrientation, StatSize,
    StepProgressVariant, StepStatus, StopwatchVariant, TableSelectMode, TableVariant,
    TabsVariant, TagSize, TerminalTheme, TextAlign, TextStyle, TextWrap, TileProvider,
    TimePrecision, TimelineOrientation, TogglePosition, ToggleSize, Tone, TreeVariant,
    VideoControls,
};
pub use tentaflow_sdk_spec::protocol::ui::typed_field::{
    IntoComponentError, decode_from_value, encode_to_value,
};
pub use tentaflow_sdk_spec::protocol::ui::ui_payload::{
    BATCH_MAX_MEMBERS, Batch, BatchMember, UiPayload, UiTag,
};
pub use tentaflow_sdk_spec::protocol::ui::validation::{
    StateCondition, ValidationRule,
};
pub use tentaflow_sdk_spec::protocol::ui::value_format::{
    BytesBase, DateStyle, DateTimeStyle, DurationStyle, TimeStyle, ValueFormat,
};
pub use tentaflow_sdk_spec::protocol::value::{
    Value,
};

#[cfg(test)]
mod catalog_conformance {
    use super::*;

    fn tstr(s: &str) -> Vec<u8> {
        let mut b = Vec::new();
        minicbor::Encoder::new(&mut b).str(s).expect("tstr encode");
        b
    }

    fn enc<T: minicbor::Encode<()>>(v: &T) -> Vec<u8> {
        minicbor::to_vec(v).expect("encode")
    }

    #[test]
    fn component_tags_match_catalog_manifest() {
        assert_eq!(EmptyState::TAG, 0x0003u16, "EmptyState");
        assert_eq!(ErrorBoundary::TAG, 0x0008u16, "ErrorBoundary");
        assert_eq!(WelcomeHero::TAG, 0x0009u16, "WelcomeHero");
        assert_eq!(Header::TAG, 0x0001u16, "Header");
        assert_eq!(PageHeader::TAG, 0x0002u16, "PageHeader");
        assert_eq!(SectionHeader::TAG, 0x0004u16, "SectionHeader");
        assert_eq!(Toolbar::TAG, 0x0005u16, "Toolbar");
        assert_eq!(StatGroup::TAG, 0x000Au16, "StatGroup");
        assert_eq!(Inspector::TAG, 0x000Cu16, "Inspector");
        assert_eq!(AppShell::TAG, 0x0006u16, "AppShell");
        assert_eq!(LoginShell::TAG, 0x0007u16, "LoginShell");
        assert_eq!(WizardShell::TAG, 0x000Bu16, "WizardShell");
        assert_eq!(Divider::TAG, 0x0108u16, "Divider");
        assert_eq!(Spacer::TAG, 0x0109u16, "Spacer");
        assert_eq!(Tooltip::TAG, 0x010Fu16, "Tooltip");
        assert_eq!(Card::TAG, 0x0106u16, "Card");
        assert_eq!(SectionCard::TAG, 0x0107u16, "SectionCard");
        assert_eq!(Collapsible::TAG, 0x010Du16, "Collapsible");
        assert_eq!(Accordion::TAG, 0x010Eu16, "Accordion");
        assert_eq!(Flex::TAG, 0x0101u16, "Flex");
        assert_eq!(Grid::TAG, 0x0102u16, "Grid");
        assert_eq!(Stack::TAG, 0x0103u16, "Stack");
        assert_eq!(Cluster::TAG, 0x0104u16, "Cluster");
        assert_eq!(Split::TAG, 0x0105u16, "Split");
        assert_eq!(ScrollContainer::TAG, 0x0112u16, "ScrollContainer");
        assert_eq!(Box::TAG, 0x0115u16, "Box");
        assert_eq!(Sidebar::TAG, 0x010Au16, "Sidebar");
        assert_eq!(Tabs::TAG, 0x010Bu16, "Tabs");
        assert_eq!(NavTabs::TAG, 0x010Cu16, "NavTabs");
        assert_eq!(Breadcrumb::TAG, 0x0110u16, "Breadcrumb");
        assert_eq!(Pagination::TAG, 0x0111u16, "Pagination");
        assert_eq!(Avatar::TAG, 0x020Du16, "Avatar");
        assert_eq!(AvatarGroup::TAG, 0x020Eu16, "AvatarGroup");
        assert_eq!(Sparkline::TAG, 0x0215u16, "Sparkline");
        assert_eq!(LineChart::TAG, 0x0216u16, "LineChart");
        assert_eq!(BarChart::TAG, 0x0217u16, "BarChart");
        assert_eq!(AreaChart::TAG, 0x0218u16, "AreaChart");
        assert_eq!(PieChart::TAG, 0x0219u16, "PieChart");
        assert_eq!(StackedBar::TAG, 0x021Au16, "StackedBar");
        assert_eq!(Heatmap::TAG, 0x021Bu16, "Heatmap");
        assert_eq!(Gauge::TAG, 0x021Cu16, "Gauge");
        assert_eq!(Badge::TAG, 0x020Au16, "Badge");
        assert_eq!(Chip::TAG, 0x020Bu16, "Chip");
        assert_eq!(Tag::TAG, 0x020Cu16, "Tag");
        assert_eq!(BulletList::TAG, 0x020Fu16, "BulletList");
        assert_eq!(Timeline::TAG, 0x0210u16, "Timeline");
        assert_eq!(Markdown::TAG, 0x0220u16, "Markdown");
        assert_eq!(DataDefinitionList::TAG, 0x0221u16, "DataDefinitionList");
        assert_eq!(JsonViewer::TAG, 0x0222u16, "JsonViewer");
        assert_eq!(ProgressBar::TAG, 0x021Du16, "ProgressBar");
        assert_eq!(RatingDisplay::TAG, 0x021Eu16, "RatingDisplay");
        assert_eq!(Diff::TAG, 0x021Fu16, "Diff");
        assert_eq!(CalendarMonth::TAG, 0x0223u16, "CalendarMonth");
        assert_eq!(Image::TAG, 0x0224u16, "Image");
        assert_eq!(VisuallyHidden::TAG, 0x0225u16, "VisuallyHidden");
        assert_eq!(LiveRegionComponent::TAG, 0x0226u16, "LiveRegionComponent");
        assert_eq!(KeyValue::TAG, 0x0207u16, "KeyValue");
        assert_eq!(StatCard::TAG, 0x0208u16, "StatCard");
        assert_eq!(Stat::TAG, 0x0209u16, "Stat");
        assert_eq!(Table::TAG, 0x0211u16, "Table");
        assert_eq!(List::TAG, 0x0212u16, "List");
        assert_eq!(Tree::TAG, 0x0213u16, "Tree");
        assert_eq!(EmptyCell::TAG, 0x0214u16, "EmptyCell");
        assert_eq!(Text::TAG, 0x0201u16, "Text");
        assert_eq!(Heading::TAG, 0x0202u16, "Heading");
        assert_eq!(Paragraph::TAG, 0x0203u16, "Paragraph");
        assert_eq!(RichText::TAG, 0x0204u16, "RichText");
        assert_eq!(MonoBlock::TAG, 0x0205u16, "MonoBlock");
        assert_eq!(CodeBlock::TAG, 0x0206u16, "CodeBlock");
        assert_eq!(Toggle::TAG, 0x030Au16, "Toggle");
        assert_eq!(Checkbox::TAG, 0x030Bu16, "Checkbox");
        assert_eq!(Radio::TAG, 0x030Cu16, "Radio");
        assert_eq!(DatePicker::TAG, 0x0314u16, "DatePicker");
        assert_eq!(DateRangePicker::TAG, 0x0315u16, "DateRangePicker");
        assert_eq!(TimePicker::TAG, 0x0316u16, "TimePicker");
        assert_eq!(DateTimePicker::TAG, 0x0317u16, "DateTimePicker");
        assert_eq!(FileInput::TAG, 0x0318u16, "FileInput");
        assert_eq!(ColorPicker::TAG, 0x0319u16, "ColorPicker");
        assert_eq!(RadioGroup::TAG, 0x030Du16, "RadioGroup");
        assert_eq!(RadioCardGroup::TAG, 0x030Eu16, "RadioCardGroup");
        assert_eq!(Input::TAG, 0x0301u16, "Input");
        assert_eq!(Textarea::TAG, 0x0302u16, "Textarea");
        assert_eq!(SearchBox::TAG, 0x0307u16, "SearchBox");
        assert_eq!(TagInput::TAG, 0x0308u16, "TagInput");
        assert_eq!(MentionInput::TAG, 0x0309u16, "MentionInput");
        assert_eq!(NumericInput::TAG, 0x0312u16, "NumericInput");
        assert_eq!(CurrencyInput::TAG, 0x0313u16, "CurrencyInput");
        assert_eq!(Slider::TAG, 0x030Fu16, "Slider");
        assert_eq!(RangeSlider::TAG, 0x0310u16, "RangeSlider");
        assert_eq!(SliderRow::TAG, 0x0311u16, "SliderRow");
        assert_eq!(Select::TAG, 0x0303u16, "Select");
        assert_eq!(MultiSelect::TAG, 0x0304u16, "MultiSelect");
        assert_eq!(Combobox::TAG, 0x0305u16, "Combobox");
        assert_eq!(Autocomplete::TAG, 0x0306u16, "Autocomplete");
        assert_eq!(FormField::TAG, 0x031Au16, "FormField");
        assert_eq!(FormGroup::TAG, 0x031Bu16, "FormGroup");
        assert_eq!(FormSection::TAG, 0x031Cu16, "FormSection");
        assert_eq!(Form::TAG, 0x031Du16, "Form");
        assert_eq!(ActionBar::TAG, 0x0408u16, "ActionBar");
        assert_eq!(SegmentedControl::TAG, 0x0409u16, "SegmentedControl");
        assert_eq!(FilterChips::TAG, 0x040Au16, "FilterChips");
        assert_eq!(WizardFooter::TAG, 0x040Bu16, "WizardFooter");
        assert_eq!(Button::TAG, 0x0401u16, "Button");
        assert_eq!(IconButton::TAG, 0x0402u16, "IconButton");
        assert_eq!(ButtonGroup::TAG, 0x0403u16, "ButtonGroup");
        assert_eq!(LinkButton::TAG, 0x0404u16, "LinkButton");
        assert_eq!(Link::TAG, 0x0405u16, "Link");
        assert_eq!(Fab::TAG, 0x040Cu16, "Fab");
        assert_eq!(MenuButton::TAG, 0x0406u16, "MenuButton");
        assert_eq!(Menu::TAG, 0x0407u16, "Menu");
        assert_eq!(GateScreen::TAG, 0x050Du16, "GateScreen");
        assert_eq!(ConfirmationDialog::TAG, 0x050Eu16, "ConfirmationDialog");
        assert_eq!(Alert::TAG, 0x0501u16, "Alert");
        assert_eq!(Banner::TAG, 0x0502u16, "Banner");
        assert_eq!(Callout::TAG, 0x0503u16, "Callout");
        assert_eq!(Toast::TAG, 0x0504u16, "Toast");
        assert_eq!(Hint::TAG, 0x0505u16, "Hint");
        assert_eq!(OfflineBanner::TAG, 0x050Fu16, "OfflineBanner");
        assert_eq!(Skeleton::TAG, 0x0506u16, "Skeleton");
        assert_eq!(Spinner::TAG, 0x0507u16, "Spinner");
        assert_eq!(LoadingBar::TAG, 0x0508u16, "LoadingBar");
        assert_eq!(Modal::TAG, 0x0509u16, "Modal");
        assert_eq!(Drawer::TAG, 0x050Au16, "Drawer");
        assert_eq!(Popover::TAG, 0x050Bu16, "Popover");
        assert_eq!(Sheet::TAG, 0x050Cu16, "Sheet");
        assert_eq!(ImageGallery::TAG, 0x060Bu16, "ImageGallery");
        assert_eq!(Carousel::TAG, 0x060Cu16, "Carousel");
        assert_eq!(PdfViewer::TAG, 0x060Du16, "PdfViewer");
        assert_eq!(IFrame::TAG, 0x060Au16, "IFrame");
        assert_eq!(VirtualizedLog::TAG, 0x0611u16, "VirtualizedLog");
        assert_eq!(MapView::TAG, 0x0606u16, "MapView");
        assert_eq!(VideoStream::TAG, 0x0604u16, "VideoStream");
        assert_eq!(LiveCameraTile::TAG, 0x0605u16, "LiveCameraTile");
        assert_eq!(Audio::TAG, 0x0609u16, "Audio");
        assert_eq!(AudioCapture::TAG, 0x0612u16, "AudioCapture");
        assert_eq!(FpsCounter::TAG, 0x060Eu16, "FpsCounter");
        assert_eq!(Stopwatch::TAG, 0x0610u16, "Stopwatch");
        assert_eq!(CodeEditor::TAG, 0x0607u16, "CodeEditor");
        assert_eq!(Terminal::TAG, 0x0608u16, "Terminal");
        assert_eq!(StepProgress::TAG, 0x060Fu16, "StepProgress");
    }

    #[test]
    fn enum_wire_names_match_catalog_manifest() {
        assert_eq!(enc(&Tone::Neutral), tstr("neutral"), "Tone::Neutral");
        assert_eq!(enc(&Tone::Primary), tstr("primary"), "Tone::Primary");
        assert_eq!(enc(&Tone::Success), tstr("success"), "Tone::Success");
        assert_eq!(enc(&Tone::Warning), tstr("warning"), "Tone::Warning");
        assert_eq!(enc(&Tone::Critical), tstr("critical"), "Tone::Critical");
        assert_eq!(enc(&Tone::Info), tstr("info"), "Tone::Info");
        assert_eq!(enc(&Tone::Muted), tstr("muted"), "Tone::Muted");
        assert_eq!(enc(&ButtonVariant::Primary), tstr("primary"), "ButtonVariant::Primary");
        assert_eq!(enc(&ButtonVariant::Secondary), tstr("secondary"), "ButtonVariant::Secondary");
        assert_eq!(enc(&ButtonVariant::Tertiary), tstr("tertiary"), "ButtonVariant::Tertiary");
        assert_eq!(enc(&ButtonVariant::Ghost), tstr("ghost"), "ButtonVariant::Ghost");
        assert_eq!(enc(&ButtonVariant::Destructive), tstr("destructive"), "ButtonVariant::Destructive");
        assert_eq!(enc(&ButtonVariant::Link), tstr("link"), "ButtonVariant::Link");
        assert_eq!(enc(&BadgeVariant::Solid), tstr("solid"), "BadgeVariant::Solid");
        assert_eq!(enc(&BadgeVariant::Soft), tstr("soft"), "BadgeVariant::Soft");
        assert_eq!(enc(&BadgeVariant::Outline), tstr("outline"), "BadgeVariant::Outline");
        assert_eq!(enc(&BadgeVariant::Pulse), tstr("pulse"), "BadgeVariant::Pulse");
        assert_eq!(enc(&BadgeVariant::Dot), tstr("dot"), "BadgeVariant::Dot");
        assert_eq!(enc(&ChipVariant::Solid), tstr("solid"), "ChipVariant::Solid");
        assert_eq!(enc(&ChipVariant::Soft), tstr("soft"), "ChipVariant::Soft");
        assert_eq!(enc(&ChipVariant::Outline), tstr("outline"), "ChipVariant::Outline");
        assert_eq!(enc(&ChipVariant::Removable), tstr("removable"), "ChipVariant::Removable");
        assert_eq!(enc(&ChipVariant::Selectable), tstr("selectable"), "ChipVariant::Selectable");
        assert_eq!(enc(&ChipVariant::Toggle), tstr("toggle"), "ChipVariant::Toggle");
        assert_eq!(enc(&Density::Compact), tstr("compact"), "Density::Compact");
        assert_eq!(enc(&Density::Default), tstr("default"), "Density::Default");
        assert_eq!(enc(&Density::Comfortable), tstr("comfortable"), "Density::Comfortable");
        assert_eq!(enc(&Spacing::Zero), tstr("zero"), "Spacing::Zero");
        assert_eq!(enc(&Spacing::Xxs), tstr("xxs"), "Spacing::Xxs");
        assert_eq!(enc(&Spacing::Xs), tstr("xs"), "Spacing::Xs");
        assert_eq!(enc(&Spacing::Sm), tstr("sm"), "Spacing::Sm");
        assert_eq!(enc(&Spacing::Md), tstr("md"), "Spacing::Md");
        assert_eq!(enc(&Spacing::Lg), tstr("lg"), "Spacing::Lg");
        assert_eq!(enc(&Spacing::Xl), tstr("xl"), "Spacing::Xl");
        assert_eq!(enc(&Spacing::Xxl), tstr("xxl"), "Spacing::Xxl");
        assert_eq!(enc(&TextStyle::Display), tstr("display"), "TextStyle::Display");
        assert_eq!(enc(&TextStyle::Title), tstr("title"), "TextStyle::Title");
        assert_eq!(enc(&TextStyle::H1), tstr("h1"), "TextStyle::H1");
        assert_eq!(enc(&TextStyle::H2), tstr("h2"), "TextStyle::H2");
        assert_eq!(enc(&TextStyle::H3), tstr("h3"), "TextStyle::H3");
        assert_eq!(enc(&TextStyle::H4), tstr("h4"), "TextStyle::H4");
        assert_eq!(enc(&TextStyle::BodyLg), tstr("body_lg"), "TextStyle::BodyLg");
        assert_eq!(enc(&TextStyle::Body), tstr("body"), "TextStyle::Body");
        assert_eq!(enc(&TextStyle::BodyStrong), tstr("body_strong"), "TextStyle::BodyStrong");
        assert_eq!(enc(&TextStyle::Caption), tstr("caption"), "TextStyle::Caption");
        assert_eq!(enc(&TextStyle::CaptionStrong), tstr("caption_strong"), "TextStyle::CaptionStrong");
        assert_eq!(enc(&TextStyle::Overline), tstr("overline"), "TextStyle::Overline");
        assert_eq!(enc(&TextStyle::Code), tstr("code"), "TextStyle::Code");
        assert_eq!(enc(&TextStyle::Mono), tstr("mono"), "TextStyle::Mono");
        assert_eq!(enc(&TextStyle::Quote), tstr("quote"), "TextStyle::Quote");
        assert_eq!(enc(&TextAlign::Start), tstr("start"), "TextAlign::Start");
        assert_eq!(enc(&TextAlign::Center), tstr("center"), "TextAlign::Center");
        assert_eq!(enc(&TextAlign::End), tstr("end"), "TextAlign::End");
        assert_eq!(enc(&TextAlign::Justify), tstr("justify"), "TextAlign::Justify");
        assert_eq!(enc(&TextWrap::Wrap), tstr("wrap"), "TextWrap::Wrap");
        assert_eq!(enc(&TextWrap::Nowrap), tstr("nowrap"), "TextWrap::Nowrap");
        assert_eq!(enc(&TextWrap::Balance), tstr("balance"), "TextWrap::Balance");
        assert_eq!(enc(&TextWrap::Pretty), tstr("pretty"), "TextWrap::Pretty");
        assert_eq!(enc(&RadiusToken::None), tstr("none"), "RadiusToken::None");
        assert_eq!(enc(&RadiusToken::Xs), tstr("xs"), "RadiusToken::Xs");
        assert_eq!(enc(&RadiusToken::Sm), tstr("sm"), "RadiusToken::Sm");
        assert_eq!(enc(&RadiusToken::Md), tstr("md"), "RadiusToken::Md");
        assert_eq!(enc(&RadiusToken::Lg), tstr("lg"), "RadiusToken::Lg");
        assert_eq!(enc(&RadiusToken::Xl), tstr("xl"), "RadiusToken::Xl");
        assert_eq!(enc(&RadiusToken::Pill), tstr("pill"), "RadiusToken::Pill");
        assert_eq!(enc(&RadiusToken::Circle), tstr("circle"), "RadiusToken::Circle");
        assert_eq!(enc(&ShadowToken::None), tstr("none"), "ShadowToken::None");
        assert_eq!(enc(&ShadowToken::Subtle), tstr("subtle"), "ShadowToken::Subtle");
        assert_eq!(enc(&ShadowToken::Medium), tstr("medium"), "ShadowToken::Medium");
        assert_eq!(enc(&ShadowToken::Elevated), tstr("elevated"), "ShadowToken::Elevated");
        assert_eq!(enc(&ShadowToken::Floating), tstr("floating"), "ShadowToken::Floating");
        assert_eq!(enc(&ShadowToken::AccentGlow), tstr("accent_glow"), "ShadowToken::AccentGlow");
        assert_eq!(enc(&SplitDivider::Handle), tstr("handle"), "SplitDivider::Handle");
        assert_eq!(enc(&SplitDivider::Line), tstr("line"), "SplitDivider::Line");
        assert_eq!(enc(&SplitDivider::None), tstr("none"), "SplitDivider::None");
        assert_eq!(enc(&InputVariant::Outlined), tstr("outlined"), "InputVariant::Outlined");
        assert_eq!(enc(&InputVariant::Ghost), tstr("ghost"), "InputVariant::Ghost");
        assert_eq!(enc(&Breakpoint::Xs), tstr("xs"), "Breakpoint::Xs");
        assert_eq!(enc(&Breakpoint::Sm), tstr("sm"), "Breakpoint::Sm");
        assert_eq!(enc(&Breakpoint::Md), tstr("md"), "Breakpoint::Md");
        assert_eq!(enc(&Breakpoint::Lg), tstr("lg"), "Breakpoint::Lg");
        assert_eq!(enc(&Breakpoint::Xl), tstr("xl"), "Breakpoint::Xl");
        assert_eq!(enc(&Breakpoint::Xxl), tstr("xxl"), "Breakpoint::Xxl");
        assert_eq!(enc(&IconSize::Xs), tstr("xs"), "IconSize::Xs");
        assert_eq!(enc(&IconSize::Sm), tstr("sm"), "IconSize::Sm");
        assert_eq!(enc(&IconSize::Md), tstr("md"), "IconSize::Md");
        assert_eq!(enc(&IconSize::Lg), tstr("lg"), "IconSize::Lg");
        assert_eq!(enc(&IconSize::Xl), tstr("xl"), "IconSize::Xl");
        assert_eq!(enc(&ScrollBehavior::Auto), tstr("auto"), "ScrollBehavior::Auto");
        assert_eq!(enc(&ScrollBehavior::Smooth), tstr("smooth"), "ScrollBehavior::Smooth");
        assert_eq!(enc(&ScrollBehavior::Instant), tstr("instant"), "ScrollBehavior::Instant");
        assert_eq!(enc(&DrawerSide::Left), tstr("left"), "DrawerSide::Left");
        assert_eq!(enc(&DrawerSide::Right), tstr("right"), "DrawerSide::Right");
        assert_eq!(enc(&DrawerSide::Top), tstr("top"), "DrawerSide::Top");
        assert_eq!(enc(&DrawerSide::Bottom), tstr("bottom"), "DrawerSide::Bottom");
        assert_eq!(enc(&NavigateTarget::NewTab), tstr("new_tab"), "NavigateTarget::NewTab");
        assert_eq!(enc(&NavigateTarget::SameTab), tstr("same_tab"), "NavigateTarget::SameTab");
        assert_eq!(enc(&NavigateTarget::SystemBrowser), tstr("system_browser"), "NavigateTarget::SystemBrowser");
        assert_eq!(enc(&LiveRegion::Off), tstr("off"), "LiveRegion::Off");
        assert_eq!(enc(&LiveRegion::Polite), tstr("polite"), "LiveRegion::Polite");
        assert_eq!(enc(&LiveRegion::Assertive), tstr("assertive"), "LiveRegion::Assertive");
        assert_eq!(enc(&CursorToken::Default), tstr("default"), "CursorToken::Default");
        assert_eq!(enc(&CursorToken::Pointer), tstr("pointer"), "CursorToken::Pointer");
        assert_eq!(enc(&CursorToken::Text), tstr("text"), "CursorToken::Text");
        assert_eq!(enc(&CursorToken::Move), tstr("move"), "CursorToken::Move");
        assert_eq!(enc(&CursorToken::Grab), tstr("grab"), "CursorToken::Grab");
        assert_eq!(enc(&CursorToken::Grabbing), tstr("grabbing"), "CursorToken::Grabbing");
        assert_eq!(enc(&CursorToken::NotAllowed), tstr("not_allowed"), "CursorToken::NotAllowed");
        assert_eq!(enc(&CursorToken::Crosshair), tstr("crosshair"), "CursorToken::Crosshair");
        assert_eq!(enc(&CursorToken::ColResize), tstr("col_resize"), "CursorToken::ColResize");
        assert_eq!(enc(&CursorToken::RowResize), tstr("row_resize"), "CursorToken::RowResize");
        assert_eq!(enc(&ColorToken::BackgroundDefault), tstr("background_default"), "ColorToken::BackgroundDefault");
        assert_eq!(enc(&ColorToken::BackgroundSubtle), tstr("background_subtle"), "ColorToken::BackgroundSubtle");
        assert_eq!(enc(&ColorToken::BackgroundMuted), tstr("background_muted"), "ColorToken::BackgroundMuted");
        assert_eq!(enc(&ColorToken::SurfaceDefault), tstr("surface_default"), "ColorToken::SurfaceDefault");
        assert_eq!(enc(&ColorToken::SurfaceRaised), tstr("surface_raised"), "ColorToken::SurfaceRaised");
        assert_eq!(enc(&ColorToken::SurfaceOverlay), tstr("surface_overlay"), "ColorToken::SurfaceOverlay");
        assert_eq!(enc(&ColorToken::BorderDefault), tstr("border_default"), "ColorToken::BorderDefault");
        assert_eq!(enc(&ColorToken::BorderStrong), tstr("border_strong"), "ColorToken::BorderStrong");
        assert_eq!(enc(&ColorToken::BorderSubtle), tstr("border_subtle"), "ColorToken::BorderSubtle");
        assert_eq!(enc(&ColorToken::TextDefault), tstr("text_default"), "ColorToken::TextDefault");
        assert_eq!(enc(&ColorToken::TextMuted), tstr("text_muted"), "ColorToken::TextMuted");
        assert_eq!(enc(&ColorToken::TextInverse), tstr("text_inverse"), "ColorToken::TextInverse");
        assert_eq!(enc(&ColorToken::AccentPrimary), tstr("accent_primary"), "ColorToken::AccentPrimary");
        assert_eq!(enc(&ColorToken::AccentSecondary), tstr("accent_secondary"), "ColorToken::AccentSecondary");
        assert_eq!(enc(&ColorToken::ToneNeutral), tstr("tone_neutral"), "ColorToken::ToneNeutral");
        assert_eq!(enc(&ColorToken::ToneSuccess), tstr("tone_success"), "ColorToken::ToneSuccess");
        assert_eq!(enc(&ColorToken::ToneWarning), tstr("tone_warning"), "ColorToken::ToneWarning");
        assert_eq!(enc(&ColorToken::ToneCritical), tstr("tone_critical"), "ColorToken::ToneCritical");
        assert_eq!(enc(&ColorToken::ToneInfo), tstr("tone_info"), "ColorToken::ToneInfo");
        assert_eq!(enc(&BackgroundToken::None), tstr("none"), "BackgroundToken::None");
        assert_eq!(enc(&BackgroundToken::Subtle), tstr("subtle"), "BackgroundToken::Subtle");
        assert_eq!(enc(&BackgroundToken::Muted), tstr("muted"), "BackgroundToken::Muted");
        assert_eq!(enc(&BackgroundToken::Accent), tstr("accent"), "BackgroundToken::Accent");
        assert_eq!(enc(&BackgroundToken::Inverse), tstr("inverse"), "BackgroundToken::Inverse");
        assert_eq!(enc(&FlexAlign::Start), tstr("start"), "FlexAlign::Start");
        assert_eq!(enc(&FlexAlign::End), tstr("end"), "FlexAlign::End");
        assert_eq!(enc(&FlexAlign::Center), tstr("center"), "FlexAlign::Center");
        assert_eq!(enc(&FlexAlign::Baseline), tstr("baseline"), "FlexAlign::Baseline");
        assert_eq!(enc(&FlexAlign::Stretch), tstr("stretch"), "FlexAlign::Stretch");
        assert_eq!(enc(&FlexJustify::Start), tstr("start"), "FlexJustify::Start");
        assert_eq!(enc(&FlexJustify::End), tstr("end"), "FlexJustify::End");
        assert_eq!(enc(&FlexJustify::Center), tstr("center"), "FlexJustify::Center");
        assert_eq!(enc(&FlexJustify::SpaceBetween), tstr("space_between"), "FlexJustify::SpaceBetween");
        assert_eq!(enc(&FlexJustify::SpaceAround), tstr("space_around"), "FlexJustify::SpaceAround");
        assert_eq!(enc(&FlexJustify::SpaceEvenly), tstr("space_evenly"), "FlexJustify::SpaceEvenly");
        assert_eq!(enc(&SortDirection::Asc), tstr("asc"), "SortDirection::Asc");
        assert_eq!(enc(&SortDirection::Desc), tstr("desc"), "SortDirection::Desc");
        assert_eq!(enc(&FileUploadStatus::Queued), tstr("queued"), "FileUploadStatus::Queued");
        assert_eq!(enc(&FileUploadStatus::Uploading), tstr("uploading"), "FileUploadStatus::Uploading");
        assert_eq!(enc(&FileUploadStatus::Complete), tstr("complete"), "FileUploadStatus::Complete");
        assert_eq!(enc(&FileUploadStatus::Error), tstr("error"), "FileUploadStatus::Error");
        assert_eq!(enc(&StepStatus::Pending), tstr("pending"), "StepStatus::Pending");
        assert_eq!(enc(&StepStatus::Current), tstr("current"), "StepStatus::Current");
        assert_eq!(enc(&StepStatus::Complete), tstr("complete"), "StepStatus::Complete");
        assert_eq!(enc(&StepStatus::Error), tstr("error"), "StepStatus::Error");
        assert_eq!(enc(&StepStatus::Skipped), tstr("skipped"), "StepStatus::Skipped");
        assert_eq!(enc(&SheetDetent::Small), tstr("small"), "SheetDetent::Small");
        assert_eq!(enc(&SheetDetent::Medium), tstr("medium"), "SheetDetent::Medium");
        assert_eq!(enc(&SheetDetent::Large), tstr("large"), "SheetDetent::Large");
        assert_eq!(enc(&SheetDetent::Full), tstr("full"), "SheetDetent::Full");
        assert_eq!(enc(&ChartSeriesStyle::Solid), tstr("solid"), "ChartSeriesStyle::Solid");
        assert_eq!(enc(&ChartSeriesStyle::Dashed), tstr("dashed"), "ChartSeriesStyle::Dashed");
        assert_eq!(enc(&ChartSeriesStyle::Dotted), tstr("dotted"), "ChartSeriesStyle::Dotted");
        assert_eq!(enc(&ChartAxisScale::Linear), tstr("linear"), "ChartAxisScale::Linear");
        assert_eq!(enc(&ChartAxisScale::Log), tstr("log"), "ChartAxisScale::Log");
        assert_eq!(enc(&ChartAxisScale::Time), tstr("time"), "ChartAxisScale::Time");
        assert_eq!(enc(&ChartAxisScale::Category), tstr("category"), "ChartAxisScale::Category");
        assert_eq!(enc(&ChartLegendPosition::Top), tstr("top"), "ChartLegendPosition::Top");
        assert_eq!(enc(&ChartLegendPosition::Bottom), tstr("bottom"), "ChartLegendPosition::Bottom");
        assert_eq!(enc(&ChartLegendPosition::Left), tstr("left"), "ChartLegendPosition::Left");
        assert_eq!(enc(&ChartLegendPosition::Right), tstr("right"), "ChartLegendPosition::Right");
        assert_eq!(enc(&ChartLegendPosition::None), tstr("none"), "ChartLegendPosition::None");
        assert_eq!(enc(&ChartLegendAlign::Start), tstr("start"), "ChartLegendAlign::Start");
        assert_eq!(enc(&ChartLegendAlign::Center), tstr("center"), "ChartLegendAlign::Center");
        assert_eq!(enc(&ChartLegendAlign::End), tstr("end"), "ChartLegendAlign::End");
        assert_eq!(enc(&ColumnRender::Text), tstr("text"), "ColumnRender::Text");
        assert_eq!(enc(&ColumnRender::Number), tstr("number"), "ColumnRender::Number");
        assert_eq!(enc(&ColumnRender::Currency), tstr("currency"), "ColumnRender::Currency");
        assert_eq!(enc(&ColumnRender::Percent), tstr("percent"), "ColumnRender::Percent");
        assert_eq!(enc(&ColumnRender::Bytes), tstr("bytes"), "ColumnRender::Bytes");
        assert_eq!(enc(&ColumnRender::Date), tstr("date"), "ColumnRender::Date");
        assert_eq!(enc(&ColumnRender::Time), tstr("time"), "ColumnRender::Time");
        assert_eq!(enc(&ColumnRender::Datetime), tstr("datetime"), "ColumnRender::Datetime");
        assert_eq!(enc(&ColumnRender::Relative), tstr("relative"), "ColumnRender::Relative");
        assert_eq!(enc(&ColumnRender::Badge), tstr("badge"), "ColumnRender::Badge");
        assert_eq!(enc(&ColumnRender::Chip), tstr("chip"), "ColumnRender::Chip");
        assert_eq!(enc(&ColumnRender::Tag), tstr("tag"), "ColumnRender::Tag");
        assert_eq!(enc(&ColumnRender::Avatar), tstr("avatar"), "ColumnRender::Avatar");
        assert_eq!(enc(&ColumnRender::AvatarGroup), tstr("avatar_group"), "ColumnRender::AvatarGroup");
        assert_eq!(enc(&ColumnRender::Icon), tstr("icon"), "ColumnRender::Icon");
        assert_eq!(enc(&ColumnRender::Stat), tstr("stat"), "ColumnRender::Stat");
        assert_eq!(enc(&ColumnRender::Trend), tstr("trend"), "ColumnRender::Trend");
        assert_eq!(enc(&ColumnRender::Progress), tstr("progress"), "ColumnRender::Progress");
        assert_eq!(enc(&ColumnRender::Rating), tstr("rating"), "ColumnRender::Rating");
        assert_eq!(enc(&ColumnRender::Actions), tstr("actions"), "ColumnRender::Actions");
        assert_eq!(enc(&ColumnRender::Checkbox), tstr("checkbox"), "ColumnRender::Checkbox");
        assert_eq!(enc(&ColumnRender::Boolean), tstr("boolean"), "ColumnRender::Boolean");
        assert_eq!(enc(&ColumnRender::CustomTemplate), tstr("custom_template"), "ColumnRender::CustomTemplate");
        assert_eq!(enc(&EmptyStateVariant::Default), tstr("default"), "EmptyStateVariant::Default");
        assert_eq!(enc(&EmptyStateVariant::Compact), tstr("compact"), "EmptyStateVariant::Compact");
        assert_eq!(enc(&EmptyStateVariant::Illustrated), tstr("illustrated"), "EmptyStateVariant::Illustrated");
        assert_eq!(enc(&FlexDirection::Row), tstr("row"), "FlexDirection::Row");
        assert_eq!(enc(&FlexDirection::RowReverse), tstr("row_reverse"), "FlexDirection::RowReverse");
        assert_eq!(enc(&FlexDirection::Column), tstr("column"), "FlexDirection::Column");
        assert_eq!(enc(&FlexDirection::ColumnReverse), tstr("column_reverse"), "FlexDirection::ColumnReverse");
        assert_eq!(enc(&FlexWrap::NoWrap), tstr("no_wrap"), "FlexWrap::NoWrap");
        assert_eq!(enc(&FlexWrap::Wrap), tstr("wrap"), "FlexWrap::Wrap");
        assert_eq!(enc(&FlexWrap::WrapReverse), tstr("wrap_reverse"), "FlexWrap::WrapReverse");
        assert_eq!(enc(&SplitOrientation::Horizontal), tstr("horizontal"), "SplitOrientation::Horizontal");
        assert_eq!(enc(&SplitOrientation::Vertical), tstr("vertical"), "SplitOrientation::Vertical");
        assert_eq!(enc(&CardVariant::Filled), tstr("filled"), "CardVariant::Filled");
        assert_eq!(enc(&CardVariant::Outlined), tstr("outlined"), "CardVariant::Outlined");
        assert_eq!(enc(&CardVariant::Elevated), tstr("elevated"), "CardVariant::Elevated");
        assert_eq!(enc(&CardVariant::Ghost), tstr("ghost"), "CardVariant::Ghost");
        assert_eq!(enc(&DividerOrientation::Horizontal), tstr("horizontal"), "DividerOrientation::Horizontal");
        assert_eq!(enc(&DividerOrientation::Vertical), tstr("vertical"), "DividerOrientation::Vertical");
        assert_eq!(enc(&DividerVariant::Default), tstr("default"), "DividerVariant::Default");
        assert_eq!(enc(&DividerVariant::Subtle), tstr("subtle"), "DividerVariant::Subtle");
        assert_eq!(enc(&DividerVariant::Strong), tstr("strong"), "DividerVariant::Strong");
        assert_eq!(enc(&DividerVariant::Dashed), tstr("dashed"), "DividerVariant::Dashed");
        assert_eq!(enc(&SpacerAxis::X), tstr("x"), "SpacerAxis::X");
        assert_eq!(enc(&SpacerAxis::Y), tstr("y"), "SpacerAxis::Y");
        assert_eq!(enc(&SpacerAxis::Both), tstr("both"), "SpacerAxis::Both");
        assert_eq!(enc(&TabsVariant::Default), tstr("default"), "TabsVariant::Default");
        assert_eq!(enc(&TabsVariant::Pills), tstr("pills"), "TabsVariant::Pills");
        assert_eq!(enc(&TabsVariant::Underlined), tstr("underlined"), "TabsVariant::Underlined");
        assert_eq!(enc(&TabsVariant::Boxed), tstr("boxed"), "TabsVariant::Boxed");
        assert_eq!(enc(&NavTabsVariant::Default), tstr("default"), "NavTabsVariant::Default");
        assert_eq!(enc(&NavTabsVariant::Underlined), tstr("underlined"), "NavTabsVariant::Underlined");
        assert_eq!(enc(&NavTabsVariant::Pills), tstr("pills"), "NavTabsVariant::Pills");
        assert_eq!(enc(&AccordionMode::Single), tstr("single"), "AccordionMode::Single");
        assert_eq!(enc(&AccordionMode::Multiple), tstr("multiple"), "AccordionMode::Multiple");
        assert_eq!(enc(&BreadcrumbSeparator::Chevron), tstr("chevron"), "BreadcrumbSeparator::Chevron");
        assert_eq!(enc(&BreadcrumbSeparator::Slash), tstr("slash"), "BreadcrumbSeparator::Slash");
        assert_eq!(enc(&BreadcrumbSeparator::Dot), tstr("dot"), "BreadcrumbSeparator::Dot");
        assert_eq!(enc(&PaginationVariant::Compact), tstr("compact"), "PaginationVariant::Compact");
        assert_eq!(enc(&PaginationVariant::Full), tstr("full"), "PaginationVariant::Full");
        assert_eq!(enc(&PaginationVariant::Input), tstr("input"), "PaginationVariant::Input");
        assert_eq!(enc(&ScrollOrientation::Vertical), tstr("vertical"), "ScrollOrientation::Vertical");
        assert_eq!(enc(&ScrollOrientation::Horizontal), tstr("horizontal"), "ScrollOrientation::Horizontal");
        assert_eq!(enc(&ScrollOrientation::Both), tstr("both"), "ScrollOrientation::Both");
        assert_eq!(enc(&MarkdownMark::Bold), tstr("bold"), "MarkdownMark::Bold");
        assert_eq!(enc(&MarkdownMark::Italic), tstr("italic"), "MarkdownMark::Italic");
        assert_eq!(enc(&MarkdownMark::Code), tstr("code"), "MarkdownMark::Code");
        assert_eq!(enc(&MarkdownMark::Link), tstr("link"), "MarkdownMark::Link");
        assert_eq!(enc(&MarkdownBlock::Heading), tstr("heading"), "MarkdownBlock::Heading");
        assert_eq!(enc(&MarkdownBlock::List), tstr("list"), "MarkdownBlock::List");
        assert_eq!(enc(&MarkdownBlock::CodeBlock), tstr("code_block"), "MarkdownBlock::CodeBlock");
        assert_eq!(enc(&MarkdownBlock::Blockquote), tstr("blockquote"), "MarkdownBlock::Blockquote");
        assert_eq!(enc(&MarkdownBlock::Table), tstr("table"), "MarkdownBlock::Table");
        assert_eq!(enc(&KvLayout::Stacked), tstr("stacked"), "KvLayout::Stacked");
        assert_eq!(enc(&KvLayout::Horizontal), tstr("horizontal"), "KvLayout::Horizontal");
        assert_eq!(enc(&KvLayout::Grid), tstr("grid"), "KvLayout::Grid");
        assert_eq!(enc(&StatSize::Sm), tstr("sm"), "StatSize::Sm");
        assert_eq!(enc(&StatSize::Md), tstr("md"), "StatSize::Md");
        assert_eq!(enc(&StatSize::Lg), tstr("lg"), "StatSize::Lg");
        assert_eq!(enc(&TagSize::Xs), tstr("xs"), "TagSize::Xs");
        assert_eq!(enc(&TagSize::Sm), tstr("sm"), "TagSize::Sm");
        assert_eq!(enc(&TagSize::Md), tstr("md"), "TagSize::Md");
        assert_eq!(enc(&AvatarSize::Xs), tstr("xs"), "AvatarSize::Xs");
        assert_eq!(enc(&AvatarSize::Sm), tstr("sm"), "AvatarSize::Sm");
        assert_eq!(enc(&AvatarSize::Md), tstr("md"), "AvatarSize::Md");
        assert_eq!(enc(&AvatarSize::Lg), tstr("lg"), "AvatarSize::Lg");
        assert_eq!(enc(&AvatarSize::Xl), tstr("xl"), "AvatarSize::Xl");
        assert_eq!(enc(&AvatarShape::Circle), tstr("circle"), "AvatarShape::Circle");
        assert_eq!(enc(&AvatarShape::Rounded), tstr("rounded"), "AvatarShape::Rounded");
        assert_eq!(enc(&AvatarShape::Square), tstr("square"), "AvatarShape::Square");
        assert_eq!(enc(&AvatarStatus::Online), tstr("online"), "AvatarStatus::Online");
        assert_eq!(enc(&AvatarStatus::Offline), tstr("offline"), "AvatarStatus::Offline");
        assert_eq!(enc(&AvatarStatus::Busy), tstr("busy"), "AvatarStatus::Busy");
        assert_eq!(enc(&AvatarStatus::Away), tstr("away"), "AvatarStatus::Away");
        assert_eq!(enc(&AvatarOverlap::Tight), tstr("tight"), "AvatarOverlap::Tight");
        assert_eq!(enc(&AvatarOverlap::Default), tstr("default"), "AvatarOverlap::Default");
        assert_eq!(enc(&AvatarOverlap::Loose), tstr("loose"), "AvatarOverlap::Loose");
        assert_eq!(enc(&BulletListVariant::Bullet), tstr("bullet"), "BulletListVariant::Bullet");
        assert_eq!(enc(&BulletListVariant::Numbered), tstr("numbered"), "BulletListVariant::Numbered");
        assert_eq!(enc(&BulletListVariant::Check), tstr("check"), "BulletListVariant::Check");
        assert_eq!(enc(&BulletListVariant::Icon), tstr("icon"), "BulletListVariant::Icon");
        assert_eq!(enc(&TimelineOrientation::Vertical), tstr("vertical"), "TimelineOrientation::Vertical");
        assert_eq!(enc(&TimelineOrientation::Horizontal), tstr("horizontal"), "TimelineOrientation::Horizontal");
        assert_eq!(enc(&TableVariant::Default), tstr("default"), "TableVariant::Default");
        assert_eq!(enc(&TableVariant::Striped), tstr("striped"), "TableVariant::Striped");
        assert_eq!(enc(&TableVariant::Borderless), tstr("borderless"), "TableVariant::Borderless");
        assert_eq!(enc(&TableVariant::Compact), tstr("compact"), "TableVariant::Compact");
        assert_eq!(enc(&TableSelectMode::None), tstr("none"), "TableSelectMode::None");
        assert_eq!(enc(&TableSelectMode::Single), tstr("single"), "TableSelectMode::Single");
        assert_eq!(enc(&TableSelectMode::Multi), tstr("multi"), "TableSelectMode::Multi");
        assert_eq!(enc(&TreeVariant::Default), tstr("default"), "TreeVariant::Default");
        assert_eq!(enc(&TreeVariant::Compact), tstr("compact"), "TreeVariant::Compact");
        assert_eq!(enc(&TreeVariant::WithIcons), tstr("with_icons"), "TreeVariant::WithIcons");
        assert_eq!(enc(&EmptyCellVariant::Dash), tstr("dash"), "EmptyCellVariant::Dash");
        assert_eq!(enc(&EmptyCellVariant::EmDash), tstr("em_dash"), "EmptyCellVariant::EmDash");
        assert_eq!(enc(&EmptyCellVariant::NA), tstr("n_a"), "EmptyCellVariant::NA");
        assert_eq!(enc(&EmptyCellVariant::None), tstr("none"), "EmptyCellVariant::None");
        assert_eq!(enc(&EmptyCellVariant::Loading), tstr("loading"), "EmptyCellVariant::Loading");
        assert_eq!(enc(&SparklineVariant::Line), tstr("line"), "SparklineVariant::Line");
        assert_eq!(enc(&SparklineVariant::Area), tstr("area"), "SparklineVariant::Area");
        assert_eq!(enc(&SparklineVariant::Bar), tstr("bar"), "SparklineVariant::Bar");
        assert_eq!(enc(&ChartZoomMode::None), tstr("none"), "ChartZoomMode::None");
        assert_eq!(enc(&ChartZoomMode::X), tstr("x"), "ChartZoomMode::X");
        assert_eq!(enc(&ChartZoomMode::Y), tstr("y"), "ChartZoomMode::Y");
        assert_eq!(enc(&ChartZoomMode::Both), tstr("both"), "ChartZoomMode::Both");
        assert_eq!(enc(&ChartOrientation::Vertical), tstr("vertical"), "ChartOrientation::Vertical");
        assert_eq!(enc(&ChartOrientation::Horizontal), tstr("horizontal"), "ChartOrientation::Horizontal");
        assert_eq!(enc(&BarStacking::None), tstr("none"), "BarStacking::None");
        assert_eq!(enc(&BarStacking::Stacked), tstr("stacked"), "BarStacking::Stacked");
        assert_eq!(enc(&BarStacking::Percent), tstr("percent"), "BarStacking::Percent");
        assert_eq!(enc(&AreaStacking::None), tstr("none"), "AreaStacking::None");
        assert_eq!(enc(&AreaStacking::Stacked), tstr("stacked"), "AreaStacking::Stacked");
        assert_eq!(enc(&AreaStacking::Percent), tstr("percent"), "AreaStacking::Percent");
        assert_eq!(enc(&PieVariant::Pie), tstr("pie"), "PieVariant::Pie");
        assert_eq!(enc(&PieVariant::Donut), tstr("donut"), "PieVariant::Donut");
        assert_eq!(enc(&HeatmapLegendPosition::TopRight), tstr("top_right"), "HeatmapLegendPosition::TopRight");
        assert_eq!(enc(&HeatmapLegendPosition::Bottom), tstr("bottom"), "HeatmapLegendPosition::Bottom");
        assert_eq!(enc(&HeatmapLegendPosition::None), tstr("none"), "HeatmapLegendPosition::None");
        assert_eq!(enc(&GaugeVariant::Circular), tstr("circular"), "GaugeVariant::Circular");
        assert_eq!(enc(&GaugeVariant::Arc), tstr("arc"), "GaugeVariant::Arc");
        assert_eq!(enc(&GaugeVariant::Semi), tstr("semi"), "GaugeVariant::Semi");
        assert_eq!(enc(&ProgressVariant::Default), tstr("default"), "ProgressVariant::Default");
        assert_eq!(enc(&ProgressVariant::Striped), tstr("striped"), "ProgressVariant::Striped");
        assert_eq!(enc(&ProgressVariant::Indeterminate), tstr("indeterminate"), "ProgressVariant::Indeterminate");
        assert_eq!(enc(&ProgressSize::Xs), tstr("xs"), "ProgressSize::Xs");
        assert_eq!(enc(&ProgressSize::Sm), tstr("sm"), "ProgressSize::Sm");
        assert_eq!(enc(&ProgressSize::Md), tstr("md"), "ProgressSize::Md");
        assert_eq!(enc(&ProgressSize::Lg), tstr("lg"), "ProgressSize::Lg");
        assert_eq!(enc(&RatingVariant::Stars), tstr("stars"), "RatingVariant::Stars");
        assert_eq!(enc(&RatingVariant::Hearts), tstr("hearts"), "RatingVariant::Hearts");
        assert_eq!(enc(&RatingVariant::Circles), tstr("circles"), "RatingVariant::Circles");
        assert_eq!(enc(&RatingVariant::Numeric), tstr("numeric"), "RatingVariant::Numeric");
        assert_eq!(enc(&RatingPrecision::Full), tstr("full"), "RatingPrecision::Full");
        assert_eq!(enc(&RatingPrecision::Half), tstr("half"), "RatingPrecision::Half");
        assert_eq!(enc(&RatingPrecision::Decimal), tstr("decimal"), "RatingPrecision::Decimal");
        assert_eq!(enc(&DiffVariant::Split), tstr("split"), "DiffVariant::Split");
        assert_eq!(enc(&DiffVariant::Inline), tstr("inline"), "DiffVariant::Inline");
        assert_eq!(enc(&DiffVariant::Unified), tstr("unified"), "DiffVariant::Unified");
        assert_eq!(enc(&MarkdownFeature::Heading), tstr("heading"), "MarkdownFeature::Heading");
        assert_eq!(enc(&MarkdownFeature::List), tstr("list"), "MarkdownFeature::List");
        assert_eq!(enc(&MarkdownFeature::CodeBlock), tstr("code_block"), "MarkdownFeature::CodeBlock");
        assert_eq!(enc(&MarkdownFeature::Blockquote), tstr("blockquote"), "MarkdownFeature::Blockquote");
        assert_eq!(enc(&MarkdownFeature::Table), tstr("table"), "MarkdownFeature::Table");
        assert_eq!(enc(&MarkdownFeature::Link), tstr("link"), "MarkdownFeature::Link");
        assert_eq!(enc(&MarkdownFeature::Image), tstr("image"), "MarkdownFeature::Image");
        assert_eq!(enc(&MarkdownFeature::Emphasis), tstr("emphasis"), "MarkdownFeature::Emphasis");
        assert_eq!(enc(&MarkdownFeature::Strong), tstr("strong"), "MarkdownFeature::Strong");
        assert_eq!(enc(&MarkdownFeature::CodeInline), tstr("code_inline"), "MarkdownFeature::CodeInline");
        assert_eq!(enc(&LinkTarget::SelfTarget), tstr("self"), "LinkTarget::SelfTarget");
        assert_eq!(enc(&LinkTarget::BlankViaCommand), tstr("blank_via_command"), "LinkTarget::BlankViaCommand");
        assert_eq!(enc(&DlLayout::Stacked), tstr("stacked"), "DlLayout::Stacked");
        assert_eq!(enc(&DlLayout::TwoColumn), tstr("two_column"), "DlLayout::TwoColumn");
        assert_eq!(enc(&DayOfWeek::Sunday), tstr("sunday"), "DayOfWeek::Sunday");
        assert_eq!(enc(&DayOfWeek::Monday), tstr("monday"), "DayOfWeek::Monday");
        assert_eq!(enc(&ImageFit::Cover), tstr("cover"), "ImageFit::Cover");
        assert_eq!(enc(&ImageFit::Contain), tstr("contain"), "ImageFit::Contain");
        assert_eq!(enc(&ImageFit::Fill), tstr("fill"), "ImageFit::Fill");
        assert_eq!(enc(&ImageFit::None), tstr("none"), "ImageFit::None");
        assert_eq!(enc(&InputType::Text), tstr("text"), "InputType::Text");
        assert_eq!(enc(&InputType::Email), tstr("email"), "InputType::Email");
        assert_eq!(enc(&InputType::Password), tstr("password"), "InputType::Password");
        assert_eq!(enc(&InputType::Url), tstr("url"), "InputType::Url");
        assert_eq!(enc(&InputType::Phone), tstr("phone"), "InputType::Phone");
        assert_eq!(enc(&InputType::Number), tstr("number"), "InputType::Number");
        assert_eq!(enc(&InputType::Search), tstr("search"), "InputType::Search");
        assert_eq!(enc(&AutocompleteHint::Off), tstr("off"), "AutocompleteHint::Off");
        assert_eq!(enc(&AutocompleteHint::On), tstr("on"), "AutocompleteHint::On");
        assert_eq!(enc(&AutocompleteHint::Name), tstr("name"), "AutocompleteHint::Name");
        assert_eq!(enc(&AutocompleteHint::Email), tstr("email"), "AutocompleteHint::Email");
        assert_eq!(enc(&AutocompleteHint::Username), tstr("username"), "AutocompleteHint::Username");
        assert_eq!(enc(&AutocompleteHint::CurrentPassword), tstr("current_password"), "AutocompleteHint::CurrentPassword");
        assert_eq!(enc(&AutocompleteHint::NewPassword), tstr("new_password"), "AutocompleteHint::NewPassword");
        assert_eq!(enc(&AutocompleteHint::OneTimeCode), tstr("one_time_code"), "AutocompleteHint::OneTimeCode");
        assert_eq!(enc(&AutocompleteHint::Tel), tstr("tel"), "AutocompleteHint::Tel");
        assert_eq!(enc(&AutocompleteHint::Url), tstr("url"), "AutocompleteHint::Url");
        assert_eq!(enc(&AutocompleteHint::StreetAddress), tstr("street_address"), "AutocompleteHint::StreetAddress");
        assert_eq!(enc(&AutocompleteHint::PostalCode), tstr("postal_code"), "AutocompleteHint::PostalCode");
        assert_eq!(enc(&InputMode::None), tstr("none"), "InputMode::None");
        assert_eq!(enc(&InputMode::Text), tstr("text"), "InputMode::Text");
        assert_eq!(enc(&InputMode::Tel), tstr("tel"), "InputMode::Tel");
        assert_eq!(enc(&InputMode::Url), tstr("url"), "InputMode::Url");
        assert_eq!(enc(&InputMode::Email), tstr("email"), "InputMode::Email");
        assert_eq!(enc(&InputMode::Numeric), tstr("numeric"), "InputMode::Numeric");
        assert_eq!(enc(&InputMode::Decimal), tstr("decimal"), "InputMode::Decimal");
        assert_eq!(enc(&InputMode::Search), tstr("search"), "InputMode::Search");
        assert_eq!(enc(&InputSize::Sm), tstr("sm"), "InputSize::Sm");
        assert_eq!(enc(&InputSize::Md), tstr("md"), "InputSize::Md");
        assert_eq!(enc(&InputSize::Lg), tstr("lg"), "InputSize::Lg");
        assert_eq!(enc(&SearchVariant::Default), tstr("default"), "SearchVariant::Default");
        assert_eq!(enc(&SearchVariant::Subtle), tstr("subtle"), "SearchVariant::Subtle");
        assert_eq!(enc(&SearchVariant::Prominent), tstr("prominent"), "SearchVariant::Prominent");
        assert_eq!(enc(&ToggleSize::Sm), tstr("sm"), "ToggleSize::Sm");
        assert_eq!(enc(&ToggleSize::Md), tstr("md"), "ToggleSize::Md");
        assert_eq!(enc(&ToggleSize::Lg), tstr("lg"), "ToggleSize::Lg");
        assert_eq!(enc(&TogglePosition::Leading), tstr("leading"), "TogglePosition::Leading");
        assert_eq!(enc(&TogglePosition::Trailing), tstr("trailing"), "TogglePosition::Trailing");
        assert_eq!(enc(&CheckboxSize::Sm), tstr("sm"), "CheckboxSize::Sm");
        assert_eq!(enc(&CheckboxSize::Md), tstr("md"), "CheckboxSize::Md");
        assert_eq!(enc(&CheckboxSize::Lg), tstr("lg"), "CheckboxSize::Lg");
        assert_eq!(enc(&RadioGroupOrientation::Horizontal), tstr("horizontal"), "RadioGroupOrientation::Horizontal");
        assert_eq!(enc(&RadioGroupOrientation::Vertical), tstr("vertical"), "RadioGroupOrientation::Vertical");
        assert_eq!(enc(&RadioCardVariant::Default), tstr("default"), "RadioCardVariant::Default");
        assert_eq!(enc(&RadioCardVariant::Compact), tstr("compact"), "RadioCardVariant::Compact");
        assert_eq!(enc(&RadioCardVariant::Feature), tstr("feature"), "RadioCardVariant::Feature");
        assert_eq!(enc(&SliderRowLayout::Horizontal), tstr("horizontal"), "SliderRowLayout::Horizontal");
        assert_eq!(enc(&SliderRowLayout::Compact), tstr("compact"), "SliderRowLayout::Compact");
        assert_eq!(enc(&TimePrecision::Minute), tstr("minute"), "TimePrecision::Minute");
        assert_eq!(enc(&TimePrecision::Second), tstr("second"), "TimePrecision::Second");
        assert_eq!(enc(&FileCapture::User), tstr("user"), "FileCapture::User");
        assert_eq!(enc(&FileCapture::Environment), tstr("environment"), "FileCapture::Environment");
        assert_eq!(enc(&ColorPickerVariant::Swatch), tstr("swatch"), "ColorPickerVariant::Swatch");
        assert_eq!(enc(&ColorPickerVariant::Wheel), tstr("wheel"), "ColorPickerVariant::Wheel");
        assert_eq!(enc(&ColorPickerVariant::Compact), tstr("compact"), "ColorPickerVariant::Compact");
        assert_eq!(enc(&ColorPickerVariant::TokensOnly), tstr("tokens_only"), "ColorPickerVariant::TokensOnly");
        assert_eq!(enc(&FormFieldLayout::Stacked), tstr("stacked"), "FormFieldLayout::Stacked");
        assert_eq!(enc(&FormFieldLayout::Horizontal), tstr("horizontal"), "FormFieldLayout::Horizontal");
        assert_eq!(enc(&FormLayout::Stacked), tstr("stacked"), "FormLayout::Stacked");
        assert_eq!(enc(&FormLayout::Horizontal), tstr("horizontal"), "FormLayout::Horizontal");
        assert_eq!(enc(&FormLayout::Compact), tstr("compact"), "FormLayout::Compact");
        assert_eq!(enc(&ButtonSize::Xs), tstr("xs"), "ButtonSize::Xs");
        assert_eq!(enc(&ButtonSize::Sm), tstr("sm"), "ButtonSize::Sm");
        assert_eq!(enc(&ButtonSize::Md), tstr("md"), "ButtonSize::Md");
        assert_eq!(enc(&ButtonSize::Lg), tstr("lg"), "ButtonSize::Lg");
        assert_eq!(enc(&ButtonGroupOrientation::Horizontal), tstr("horizontal"), "ButtonGroupOrientation::Horizontal");
        assert_eq!(enc(&ButtonGroupOrientation::Vertical), tstr("vertical"), "ButtonGroupOrientation::Vertical");
        assert_eq!(enc(&LinkUnderline::Always), tstr("always"), "LinkUnderline::Always");
        assert_eq!(enc(&LinkUnderline::Hover), tstr("hover"), "LinkUnderline::Hover");
        assert_eq!(enc(&LinkUnderline::Never), tstr("never"), "LinkUnderline::Never");
        assert_eq!(enc(&MenuPlacement::BottomStart), tstr("bottom_start"), "MenuPlacement::BottomStart");
        assert_eq!(enc(&MenuPlacement::BottomEnd), tstr("bottom_end"), "MenuPlacement::BottomEnd");
        assert_eq!(enc(&MenuPlacement::TopStart), tstr("top_start"), "MenuPlacement::TopStart");
        assert_eq!(enc(&MenuPlacement::TopEnd), tstr("top_end"), "MenuPlacement::TopEnd");
        assert_eq!(enc(&MenuPlacement::LeftStart), tstr("left_start"), "MenuPlacement::LeftStart");
        assert_eq!(enc(&MenuPlacement::LeftEnd), tstr("left_end"), "MenuPlacement::LeftEnd");
        assert_eq!(enc(&MenuPlacement::RightStart), tstr("right_start"), "MenuPlacement::RightStart");
        assert_eq!(enc(&MenuPlacement::RightEnd), tstr("right_end"), "MenuPlacement::RightEnd");
        assert_eq!(enc(&SegmentSize::Sm), tstr("sm"), "SegmentSize::Sm");
        assert_eq!(enc(&SegmentSize::Md), tstr("md"), "SegmentSize::Md");
        assert_eq!(enc(&SegmentSize::Lg), tstr("lg"), "SegmentSize::Lg");
        assert_eq!(enc(&FilterChipsMode::Single), tstr("single"), "FilterChipsMode::Single");
        assert_eq!(enc(&FilterChipsMode::Multi), tstr("multi"), "FilterChipsMode::Multi");
        assert_eq!(enc(&FabSize::Sm), tstr("sm"), "FabSize::Sm");
        assert_eq!(enc(&FabSize::Md), tstr("md"), "FabSize::Md");
        assert_eq!(enc(&FabSize::Lg), tstr("lg"), "FabSize::Lg");
        assert_eq!(enc(&FabPosition::BottomRight), tstr("bottom_right"), "FabPosition::BottomRight");
        assert_eq!(enc(&FabPosition::BottomLeft), tstr("bottom_left"), "FabPosition::BottomLeft");
        assert_eq!(enc(&FabPosition::Inline), tstr("inline"), "FabPosition::Inline");
        assert_eq!(enc(&AlertVariant::Default), tstr("default"), "AlertVariant::Default");
        assert_eq!(enc(&AlertVariant::Filled), tstr("filled"), "AlertVariant::Filled");
        assert_eq!(enc(&AlertVariant::Outlined), tstr("outlined"), "AlertVariant::Outlined");
        assert_eq!(enc(&AlertVariant::Soft), tstr("soft"), "AlertVariant::Soft");
        assert_eq!(enc(&BannerPosition::Top), tstr("top"), "BannerPosition::Top");
        assert_eq!(enc(&BannerPosition::Inline), tstr("inline"), "BannerPosition::Inline");
        assert_eq!(enc(&SkeletonVariant::Text), tstr("text"), "SkeletonVariant::Text");
        assert_eq!(enc(&SkeletonVariant::Circle), tstr("circle"), "SkeletonVariant::Circle");
        assert_eq!(enc(&SkeletonVariant::Rectangle), tstr("rectangle"), "SkeletonVariant::Rectangle");
        assert_eq!(enc(&SkeletonVariant::Card), tstr("card"), "SkeletonVariant::Card");
        assert_eq!(enc(&SkeletonVariant::TableRow), tstr("table_row"), "SkeletonVariant::TableRow");
        assert_eq!(enc(&SpinnerSize::Xs), tstr("xs"), "SpinnerSize::Xs");
        assert_eq!(enc(&SpinnerSize::Sm), tstr("sm"), "SpinnerSize::Sm");
        assert_eq!(enc(&SpinnerSize::Md), tstr("md"), "SpinnerSize::Md");
        assert_eq!(enc(&SpinnerSize::Lg), tstr("lg"), "SpinnerSize::Lg");
        assert_eq!(enc(&SpinnerSize::Xl), tstr("xl"), "SpinnerSize::Xl");
        assert_eq!(enc(&SpinnerVariant::Default), tstr("default"), "SpinnerVariant::Default");
        assert_eq!(enc(&SpinnerVariant::Ring), tstr("ring"), "SpinnerVariant::Ring");
        assert_eq!(enc(&SpinnerVariant::Dots), tstr("dots"), "SpinnerVariant::Dots");
        assert_eq!(enc(&SpinnerVariant::Bars), tstr("bars"), "SpinnerVariant::Bars");
        assert_eq!(enc(&ModalSize::Xs), tstr("xs"), "ModalSize::Xs");
        assert_eq!(enc(&ModalSize::Sm), tstr("sm"), "ModalSize::Sm");
        assert_eq!(enc(&ModalSize::Md), tstr("md"), "ModalSize::Md");
        assert_eq!(enc(&ModalSize::Lg), tstr("lg"), "ModalSize::Lg");
        assert_eq!(enc(&ModalSize::Xl), tstr("xl"), "ModalSize::Xl");
        assert_eq!(enc(&ModalSize::Fullscreen), tstr("fullscreen"), "ModalSize::Fullscreen");
        assert_eq!(enc(&DrawerSize::Xs), tstr("xs"), "DrawerSize::Xs");
        assert_eq!(enc(&DrawerSize::Sm), tstr("sm"), "DrawerSize::Sm");
        assert_eq!(enc(&DrawerSize::Md), tstr("md"), "DrawerSize::Md");
        assert_eq!(enc(&DrawerSize::Lg), tstr("lg"), "DrawerSize::Lg");
        assert_eq!(enc(&DrawerSize::Xl), tstr("xl"), "DrawerSize::Xl");
        assert_eq!(enc(&PopoverPlacement::Top), tstr("top"), "PopoverPlacement::Top");
        assert_eq!(enc(&PopoverPlacement::TopStart), tstr("top_start"), "PopoverPlacement::TopStart");
        assert_eq!(enc(&PopoverPlacement::TopEnd), tstr("top_end"), "PopoverPlacement::TopEnd");
        assert_eq!(enc(&PopoverPlacement::Bottom), tstr("bottom"), "PopoverPlacement::Bottom");
        assert_eq!(enc(&PopoverPlacement::BottomStart), tstr("bottom_start"), "PopoverPlacement::BottomStart");
        assert_eq!(enc(&PopoverPlacement::BottomEnd), tstr("bottom_end"), "PopoverPlacement::BottomEnd");
        assert_eq!(enc(&PopoverPlacement::Left), tstr("left"), "PopoverPlacement::Left");
        assert_eq!(enc(&PopoverPlacement::LeftStart), tstr("left_start"), "PopoverPlacement::LeftStart");
        assert_eq!(enc(&PopoverPlacement::LeftEnd), tstr("left_end"), "PopoverPlacement::LeftEnd");
        assert_eq!(enc(&PopoverPlacement::Right), tstr("right"), "PopoverPlacement::Right");
        assert_eq!(enc(&PopoverPlacement::RightStart), tstr("right_start"), "PopoverPlacement::RightStart");
        assert_eq!(enc(&PopoverPlacement::RightEnd), tstr("right_end"), "PopoverPlacement::RightEnd");
        assert_eq!(enc(&GateVariant::AuthRequired), tstr("auth_required"), "GateVariant::AuthRequired");
        assert_eq!(enc(&GateVariant::PermissionDenied), tstr("permission_denied"), "GateVariant::PermissionDenied");
        assert_eq!(enc(&GateVariant::RateLimited), tstr("rate_limited"), "GateVariant::RateLimited");
        assert_eq!(enc(&GateVariant::Maintenance), tstr("maintenance"), "GateVariant::Maintenance");
        assert_eq!(enc(&VideoControls::None), tstr("none"), "VideoControls::None");
        assert_eq!(enc(&VideoControls::Minimal), tstr("minimal"), "VideoControls::Minimal");
        assert_eq!(enc(&VideoControls::Full), tstr("full"), "VideoControls::Full");
        assert_eq!(enc(&CameraStatus::Online), tstr("online"), "CameraStatus::Online");
        assert_eq!(enc(&CameraStatus::Offline), tstr("offline"), "CameraStatus::Offline");
        assert_eq!(enc(&CameraStatus::Buffering), tstr("buffering"), "CameraStatus::Buffering");
        assert_eq!(enc(&CameraStatus::Error), tstr("error"), "CameraStatus::Error");
        assert_eq!(enc(&TileProvider::Osm), tstr("osm"), "TileProvider::Osm");
        assert_eq!(enc(&TileProvider::Mapbox), tstr("mapbox"), "TileProvider::Mapbox");
        assert_eq!(enc(&TileProvider::TileServer), tstr("tile_server"), "TileProvider::TileServer");
        assert_eq!(enc(&CodeEditorTheme::Auto), tstr("auto"), "CodeEditorTheme::Auto");
        assert_eq!(enc(&CodeEditorTheme::Light), tstr("light"), "CodeEditorTheme::Light");
        assert_eq!(enc(&CodeEditorTheme::Dark), tstr("dark"), "CodeEditorTheme::Dark");
        assert_eq!(enc(&TerminalTheme::Default), tstr("default"), "TerminalTheme::Default");
        assert_eq!(enc(&TerminalTheme::HighContrast), tstr("high_contrast"), "TerminalTheme::HighContrast");
        assert_eq!(enc(&TerminalTheme::Dim), tstr("dim"), "TerminalTheme::Dim");
        assert_eq!(enc(&AudioControls::None), tstr("none"), "AudioControls::None");
        assert_eq!(enc(&AudioControls::Minimal), tstr("minimal"), "AudioControls::Minimal");
        assert_eq!(enc(&AudioControls::Full), tstr("full"), "AudioControls::Full");
        assert_eq!(enc(&AudioVariant::Default), tstr("default"), "AudioVariant::Default");
        assert_eq!(enc(&AudioVariant::Compact), tstr("compact"), "AudioVariant::Compact");
        assert_eq!(enc(&AudioVariant::Waveform), tstr("waveform"), "AudioVariant::Waveform");
        assert_eq!(enc(&AudioCaptureMode::PushToTalk), tstr("push_to_talk"), "AudioCaptureMode::PushToTalk");
        assert_eq!(enc(&AudioCaptureMode::Vad), tstr("vad"), "AudioCaptureMode::Vad");
        assert_eq!(enc(&AudioCaptureVariant::Standalone), tstr("standalone"), "AudioCaptureVariant::Standalone");
        assert_eq!(enc(&AudioCaptureVariant::Docked), tstr("docked"), "AudioCaptureVariant::Docked");
        assert_eq!(enc(&FpsVariant::Minimal), tstr("minimal"), "FpsVariant::Minimal");
        assert_eq!(enc(&FpsVariant::Detailed), tstr("detailed"), "FpsVariant::Detailed");
        assert_eq!(enc(&StopwatchVariant::Seconds), tstr("seconds"), "StopwatchVariant::Seconds");
        assert_eq!(enc(&StopwatchVariant::Minutes), tstr("minutes"), "StopwatchVariant::Minutes");
        assert_eq!(enc(&StopwatchVariant::Hours), tstr("hours"), "StopwatchVariant::Hours");
        assert_eq!(enc(&StopwatchVariant::Full), tstr("full"), "StopwatchVariant::Full");
        assert_eq!(enc(&CarouselGestures::Swipe), tstr("swipe"), "CarouselGestures::Swipe");
        assert_eq!(enc(&CarouselGestures::ArrowsOnly), tstr("arrows_only"), "CarouselGestures::ArrowsOnly");
        assert_eq!(enc(&CarouselGestures::None), tstr("none"), "CarouselGestures::None");
        assert_eq!(enc(&PdfZoomMode::FitWidth), tstr("fit_width"), "PdfZoomMode::FitWidth");
        assert_eq!(enc(&PdfZoomMode::FitHeight), tstr("fit_height"), "PdfZoomMode::FitHeight");
        assert_eq!(enc(&PdfZoomMode::Actual), tstr("actual"), "PdfZoomMode::Actual");
        assert_eq!(enc(&PdfZoomMode::Custom), tstr("custom"), "PdfZoomMode::Custom");
        assert_eq!(enc(&StepProgressVariant::Horizontal), tstr("horizontal"), "StepProgressVariant::Horizontal");
        assert_eq!(enc(&StepProgressVariant::Vertical), tstr("vertical"), "StepProgressVariant::Vertical");
        assert_eq!(enc(&StepProgressVariant::Compact), tstr("compact"), "StepProgressVariant::Compact");
        assert_eq!(enc(&IFrameSandbox::AllowScripts), tstr("allow-scripts"), "IFrameSandbox::AllowScripts");
        assert_eq!(enc(&IFrameSandbox::AllowForms), tstr("allow-forms"), "IFrameSandbox::AllowForms");
        assert_eq!(enc(&IFrameSandbox::AllowPopups), tstr("allow-popups"), "IFrameSandbox::AllowPopups");
        assert_eq!(enc(&IFrameSandbox::AllowModals), tstr("allow-modals"), "IFrameSandbox::AllowModals");
        assert_eq!(enc(&IFrameReferrerPolicy::NoReferrer), tstr("no-referrer"), "IFrameReferrerPolicy::NoReferrer");
        assert_eq!(enc(&IFrameReferrerPolicy::NoReferrerWhenDowngrade), tstr("no-referrer-when-downgrade"), "IFrameReferrerPolicy::NoReferrerWhenDowngrade");
        assert_eq!(enc(&IFrameReferrerPolicy::Origin), tstr("origin"), "IFrameReferrerPolicy::Origin");
        assert_eq!(enc(&IFrameReferrerPolicy::OriginWhenCrossOrigin), tstr("origin-when-cross-origin"), "IFrameReferrerPolicy::OriginWhenCrossOrigin");
        assert_eq!(enc(&IFrameReferrerPolicy::SameOrigin), tstr("same-origin"), "IFrameReferrerPolicy::SameOrigin");
        assert_eq!(enc(&IFrameReferrerPolicy::StrictOrigin), tstr("strict-origin"), "IFrameReferrerPolicy::StrictOrigin");
        assert_eq!(enc(&IFrameReferrerPolicy::StrictOriginWhenCrossOrigin), tstr("strict-origin-when-cross-origin"), "IFrameReferrerPolicy::StrictOriginWhenCrossOrigin");
        assert_eq!(enc(&IFrameReferrerPolicy::UnsafeUrl), tstr("unsafe-url"), "IFrameReferrerPolicy::UnsafeUrl");
        assert_eq!(enc(&BorderColor::Default), tstr("default"), "BorderColor::Default");
        assert_eq!(enc(&BorderColor::Hover), tstr("hover"), "BorderColor::Hover");
        assert_eq!(enc(&BorderColor::Accent), tstr("accent"), "BorderColor::Accent");
        assert_eq!(enc(&BorderColor::Success), tstr("success"), "BorderColor::Success");
        assert_eq!(enc(&BorderColor::Warning), tstr("warning"), "BorderColor::Warning");
        assert_eq!(enc(&BorderColor::Danger), tstr("danger"), "BorderColor::Danger");
        assert_eq!(enc(&BorderColor::Transparent), tstr("transparent"), "BorderColor::Transparent");
        assert_eq!(enc(&BorderLineStyle::Solid), tstr("solid"), "BorderLineStyle::Solid");
        assert_eq!(enc(&BorderLineStyle::Dashed), tstr("dashed"), "BorderLineStyle::Dashed");
        assert_eq!(enc(&BorderLineStyle::None), tstr("none"), "BorderLineStyle::None");
        assert_eq!(enc(&Overflow::Visible), tstr("visible"), "Overflow::Visible");
        assert_eq!(enc(&Overflow::Hidden), tstr("hidden"), "Overflow::Hidden");
        assert_eq!(enc(&Overflow::Auto), tstr("auto"), "Overflow::Auto");
        assert_eq!(enc(&Overflow::Scroll), tstr("scroll"), "Overflow::Scroll");
        assert_eq!(enc(&LogVariant::Compact), tstr("compact"), "LogVariant::Compact");
        assert_eq!(enc(&LogVariant::Default), tstr("default"), "LogVariant::Default");
        assert_eq!(enc(&LogVariant::Expanded), tstr("expanded"), "LogVariant::Expanded");
        assert_eq!(enc(&LogLevel::Trace), tstr("trace"), "LogLevel::Trace");
        assert_eq!(enc(&LogLevel::Debug), tstr("debug"), "LogLevel::Debug");
        assert_eq!(enc(&LogLevel::Info), tstr("info"), "LogLevel::Info");
        assert_eq!(enc(&LogLevel::Warn), tstr("warn"), "LogLevel::Warn");
        assert_eq!(enc(&LogLevel::Error), tstr("error"), "LogLevel::Error");
        assert_eq!(enc(&LogLevel::Fatal), tstr("fatal"), "LogLevel::Fatal");
        assert_eq!(enc(&BytesBase::Si), tstr("1000"), "BytesBase::Si");
        assert_eq!(enc(&BytesBase::Binary), tstr("1024"), "BytesBase::Binary");
        assert_eq!(enc(&DurationStyle::Short), tstr("short"), "DurationStyle::Short");
        assert_eq!(enc(&DurationStyle::Long), tstr("long"), "DurationStyle::Long");
        assert_eq!(enc(&DurationStyle::Stopwatch), tstr("stopwatch"), "DurationStyle::Stopwatch");
        assert_eq!(enc(&DateStyle::Short), tstr("short"), "DateStyle::Short");
        assert_eq!(enc(&DateStyle::Medium), tstr("medium"), "DateStyle::Medium");
        assert_eq!(enc(&DateStyle::Long), tstr("long"), "DateStyle::Long");
        assert_eq!(enc(&DateStyle::Full), tstr("full"), "DateStyle::Full");
        assert_eq!(enc(&TimeStyle::Short), tstr("short"), "TimeStyle::Short");
        assert_eq!(enc(&TimeStyle::Medium), tstr("medium"), "TimeStyle::Medium");
        assert_eq!(enc(&TimeStyle::Long), tstr("long"), "TimeStyle::Long");
        assert_eq!(enc(&DateTimeStyle::Short), tstr("short"), "DateTimeStyle::Short");
        assert_eq!(enc(&DateTimeStyle::Medium), tstr("medium"), "DateTimeStyle::Medium");
        assert_eq!(enc(&DateTimeStyle::Long), tstr("long"), "DateTimeStyle::Long");
        assert_eq!(enc(&DateTimeStyle::Full), tstr("full"), "DateTimeStyle::Full");
        assert_eq!(enc(&TrendDirection::Up), tstr("up"), "TrendDirection::Up");
        assert_eq!(enc(&TrendDirection::Down), tstr("down"), "TrendDirection::Down");
        assert_eq!(enc(&TrendDirection::Flat), tstr("flat"), "TrendDirection::Flat");
        assert_eq!(enc(&IconName::Add), tstr("add"), "IconName::Add");
        assert_eq!(enc(&IconName::Alarms), tstr("alarms"), "IconName::Alarms");
        assert_eq!(enc(&IconName::Alert), tstr("alert"), "IconName::Alert");
        assert_eq!(enc(&IconName::Apps), tstr("apps"), "IconName::Apps");
        assert_eq!(enc(&IconName::Arrow), tstr("arrow"), "IconName::Arrow");
        assert_eq!(enc(&IconName::ArrowDown), tstr("arrow_down"), "IconName::ArrowDown");
        assert_eq!(enc(&IconName::ArrowLeft), tstr("arrow_left"), "IconName::ArrowLeft");
        assert_eq!(enc(&IconName::ArrowOut), tstr("arrow_out"), "IconName::ArrowOut");
        assert_eq!(enc(&IconName::ArrowRight), tstr("arrow_right"), "IconName::ArrowRight");
        assert_eq!(enc(&IconName::ArrowUp), tstr("arrow_up"), "IconName::ArrowUp");
        assert_eq!(enc(&IconName::Audit), tstr("audit"), "IconName::Audit");
        assert_eq!(enc(&IconName::Ban), tstr("ban"), "IconName::Ban");
        assert_eq!(enc(&IconName::BarChart), tstr("bar_chart"), "IconName::BarChart");
        assert_eq!(enc(&IconName::Bell), tstr("bell"), "IconName::Bell");
        assert_eq!(enc(&IconName::Bolt), tstr("bolt"), "IconName::Bolt");
        assert_eq!(enc(&IconName::Brain), tstr("brain"), "IconName::Brain");
        assert_eq!(enc(&IconName::Branch), tstr("branch"), "IconName::Branch");
        assert_eq!(enc(&IconName::Cameras), tstr("cameras"), "IconName::Cameras");
        assert_eq!(enc(&IconName::Cancel), tstr("cancel"), "IconName::Cancel");
        assert_eq!(enc(&IconName::Catalog), tstr("catalog"), "IconName::Catalog");
        assert_eq!(enc(&IconName::ChartLine), tstr("chart_line"), "IconName::ChartLine");
        assert_eq!(enc(&IconName::Chat), tstr("chat"), "IconName::Chat");
        assert_eq!(enc(&IconName::Check), tstr("check"), "IconName::Check");
        assert_eq!(enc(&IconName::ChevronDown), tstr("chevron_down"), "IconName::ChevronDown");
        assert_eq!(enc(&IconName::ChevronLeft), tstr("chevron_left"), "IconName::ChevronLeft");
        assert_eq!(enc(&IconName::ChevronRight), tstr("chevron_right"), "IconName::ChevronRight");
        assert_eq!(enc(&IconName::ChevronUp), tstr("chevron_up"), "IconName::ChevronUp");
        assert_eq!(enc(&IconName::Chip), tstr("chip"), "IconName::Chip");
        assert_eq!(enc(&IconName::Clock), tstr("clock"), "IconName::Clock");
        assert_eq!(enc(&IconName::ClockGlance), tstr("clock_glance"), "IconName::ClockGlance");
        assert_eq!(enc(&IconName::Close), tstr("close"), "IconName::Close");
        assert_eq!(enc(&IconName::Cloud), tstr("cloud"), "IconName::Cloud");
        assert_eq!(enc(&IconName::Cluster), tstr("cluster"), "IconName::Cluster");
        assert_eq!(enc(&IconName::Code), tstr("code"), "IconName::Code");
        assert_eq!(enc(&IconName::Collapse), tstr("collapse"), "IconName::Collapse");
        assert_eq!(enc(&IconName::Copy), tstr("copy"), "IconName::Copy");
        assert_eq!(enc(&IconName::Core), tstr("core"), "IconName::Core");
        assert_eq!(enc(&IconName::Cpu), tstr("cpu"), "IconName::Cpu");
        assert_eq!(enc(&IconName::Cylinder), tstr("cylinder"), "IconName::Cylinder");
        assert_eq!(enc(&IconName::Danger), tstr("danger"), "IconName::Danger");
        assert_eq!(enc(&IconName::Dashboard), tstr("dashboard"), "IconName::Dashboard");
        assert_eq!(enc(&IconName::Database), tstr("database"), "IconName::Database");
        assert_eq!(enc(&IconName::Delete), tstr("delete"), "IconName::Delete");
        assert_eq!(enc(&IconName::Desktop), tstr("desktop"), "IconName::Desktop");
        assert_eq!(enc(&IconName::Docker), tstr("docker"), "IconName::Docker");
        assert_eq!(enc(&IconName::Document), tstr("document"), "IconName::Document");
        assert_eq!(enc(&IconName::Download), tstr("download"), "IconName::Download");
        assert_eq!(enc(&IconName::Edit), tstr("edit"), "IconName::Edit");
        assert_eq!(enc(&IconName::Evidence), tstr("evidence"), "IconName::Evidence");
        assert_eq!(enc(&IconName::ExternalLink), tstr("external_link"), "IconName::ExternalLink");
        assert_eq!(enc(&IconName::Eye), tstr("eye"), "IconName::Eye");
        assert_eq!(enc(&IconName::EyeOff), tstr("eye_off"), "IconName::EyeOff");
        assert_eq!(enc(&IconName::Face), tstr("face"), "IconName::Face");
        assert_eq!(enc(&IconName::File), tstr("file"), "IconName::File");
        assert_eq!(enc(&IconName::FileText), tstr("file_text"), "IconName::FileText");
        assert_eq!(enc(&IconName::Filter), tstr("filter"), "IconName::Filter");
        assert_eq!(enc(&IconName::Flow), tstr("flow"), "IconName::Flow");
        assert_eq!(enc(&IconName::Folder), tstr("folder"), "IconName::Folder");
        assert_eq!(enc(&IconName::Globe), tstr("globe"), "IconName::Globe");
        assert_eq!(enc(&IconName::GlobeGrid), tstr("globe_grid"), "IconName::GlobeGrid");
        assert_eq!(enc(&IconName::Gpu), tstr("gpu"), "IconName::Gpu");
        assert_eq!(enc(&IconName::GridRows), tstr("grid_rows"), "IconName::GridRows");
        assert_eq!(enc(&IconName::Grip), tstr("grip"), "IconName::Grip");
        assert_eq!(enc(&IconName::Help), tstr("help"), "IconName::Help");
        assert_eq!(enc(&IconName::Home), tstr("home"), "IconName::Home");
        assert_eq!(enc(&IconName::HomeSimple), tstr("home_simple"), "IconName::HomeSimple");
        assert_eq!(enc(&IconName::Host), tstr("host"), "IconName::Host");
        assert_eq!(enc(&IconName::IfaceLan), tstr("iface_lan"), "IconName::IfaceLan");
        assert_eq!(enc(&IconName::IfaceLoop), tstr("iface_loop"), "IconName::IfaceLoop");
        assert_eq!(enc(&IconName::IfaceTb), tstr("iface_tb"), "IconName::IfaceTb");
        assert_eq!(enc(&IconName::IfaceVirt), tstr("iface_virt"), "IconName::IfaceVirt");
        assert_eq!(enc(&IconName::IfaceVpn), tstr("iface_vpn"), "IconName::IfaceVpn");
        assert_eq!(enc(&IconName::IfaceWifi), tstr("iface_wifi"), "IconName::IfaceWifi");
        assert_eq!(enc(&IconName::Image), tstr("image"), "IconName::Image");
        assert_eq!(enc(&IconName::Info), tstr("info"), "IconName::Info");
        assert_eq!(enc(&IconName::Key), tstr("key"), "IconName::Key");
        assert_eq!(enc(&IconName::LineChart), tstr("line_chart"), "IconName::LineChart");
        assert_eq!(enc(&IconName::List), tstr("list"), "IconName::List");
        assert_eq!(enc(&IconName::Lock), tstr("lock"), "IconName::Lock");
        assert_eq!(enc(&IconName::Locked), tstr("locked"), "IconName::Locked");
        assert_eq!(enc(&IconName::Logout), tstr("logout"), "IconName::Logout");
        assert_eq!(enc(&IconName::Management), tstr("management"), "IconName::Management");
        assert_eq!(enc(&IconName::Max), tstr("max"), "IconName::Max");
        assert_eq!(enc(&IconName::Meeting), tstr("meeting"), "IconName::Meeting");
        assert_eq!(enc(&IconName::Message), tstr("message"), "IconName::Message");
        assert_eq!(enc(&IconName::Mic), tstr("mic"), "IconName::Mic");
        assert_eq!(enc(&IconName::Min), tstr("min"), "IconName::Min");
        assert_eq!(enc(&IconName::Model), tstr("model"), "IconName::Model");
        assert_eq!(enc(&IconName::Models), tstr("models"), "IconName::Models");
        assert_eq!(enc(&IconName::More), tstr("more"), "IconName::More");
        assert_eq!(enc(&IconName::Network), tstr("network"), "IconName::Network");
        assert_eq!(enc(&IconName::NetworkSvg), tstr("network_svg"), "IconName::NetworkSvg");
        assert_eq!(enc(&IconName::Os), tstr("os"), "IconName::Os");
        assert_eq!(enc(&IconName::Paperclip), tstr("paperclip"), "IconName::Paperclip");
        assert_eq!(enc(&IconName::Pause), tstr("pause"), "IconName::Pause");
        assert_eq!(enc(&IconName::Person), tstr("person"), "IconName::Person");
        assert_eq!(enc(&IconName::Pi), tstr("pi"), "IconName::Pi");
        assert_eq!(enc(&IconName::Pin), tstr("pin"), "IconName::Pin");
        assert_eq!(enc(&IconName::Play), tstr("play"), "IconName::Play");
        assert_eq!(enc(&IconName::Plus), tstr("plus"), "IconName::Plus");
        assert_eq!(enc(&IconName::Power), tstr("power"), "IconName::Power");
        assert_eq!(enc(&IconName::Profiles), tstr("profiles"), "IconName::Profiles");
        assert_eq!(enc(&IconName::Prompt), tstr("prompt"), "IconName::Prompt");
        assert_eq!(enc(&IconName::Puzzle), tstr("puzzle"), "IconName::Puzzle");
        assert_eq!(enc(&IconName::Question), tstr("question"), "IconName::Question");
        assert_eq!(enc(&IconName::RagDb), tstr("rag_db"), "IconName::RagDb");
        assert_eq!(enc(&IconName::Ram), tstr("ram"), "IconName::Ram");
        assert_eq!(enc(&IconName::Record), tstr("record"), "IconName::Record");
        assert_eq!(enc(&IconName::RecordDot), tstr("record_dot"), "IconName::RecordDot");
        assert_eq!(enc(&IconName::Refresh), tstr("refresh"), "IconName::Refresh");
        assert_eq!(enc(&IconName::Registry), tstr("registry"), "IconName::Registry");
        assert_eq!(enc(&IconName::Rotate), tstr("rotate"), "IconName::Rotate");
        assert_eq!(enc(&IconName::Rules), tstr("rules"), "IconName::Rules");
        assert_eq!(enc(&IconName::Save), tstr("save"), "IconName::Save");
        assert_eq!(enc(&IconName::Search), tstr("search"), "IconName::Search");
        assert_eq!(enc(&IconName::Send), tstr("send"), "IconName::Send");
        assert_eq!(enc(&IconName::Services), tstr("services"), "IconName::Services");
        assert_eq!(enc(&IconName::Settings), tstr("settings"), "IconName::Settings");
        assert_eq!(enc(&IconName::Settings2), tstr("settings2"), "IconName::Settings2");
        assert_eq!(enc(&IconName::Share), tstr("share"), "IconName::Share");
        assert_eq!(enc(&IconName::Shield), tstr("shield"), "IconName::Shield");
        assert_eq!(enc(&IconName::Sparkle), tstr("sparkle"), "IconName::Sparkle");
        assert_eq!(enc(&IconName::Speaker), tstr("speaker"), "IconName::Speaker");
        assert_eq!(enc(&IconName::SpeakerAlt), tstr("speaker_alt"), "IconName::SpeakerAlt");
        assert_eq!(enc(&IconName::Star), tstr("star"), "IconName::Star");
        assert_eq!(enc(&IconName::Stop), tstr("stop"), "IconName::Stop");
        assert_eq!(enc(&IconName::Success), tstr("success"), "IconName::Success");
        assert_eq!(enc(&IconName::Transform), tstr("transform"), "IconName::Transform");
        assert_eq!(enc(&IconName::Trash), tstr("trash"), "IconName::Trash");
        assert_eq!(enc(&IconName::Trend), tstr("trend"), "IconName::Trend");
        assert_eq!(enc(&IconName::Unlock), tstr("unlock"), "IconName::Unlock");
        assert_eq!(enc(&IconName::Unlocked), tstr("unlocked"), "IconName::Unlocked");
        assert_eq!(enc(&IconName::User), tstr("user"), "IconName::User");
        assert_eq!(enc(&IconName::Users), tstr("users"), "IconName::Users");
        assert_eq!(enc(&IconName::Vehicle), tstr("vehicle"), "IconName::Vehicle");
        assert_eq!(enc(&IconName::Video), tstr("video"), "IconName::Video");
        assert_eq!(enc(&IconName::Volume), tstr("volume"), "IconName::Volume");
        assert_eq!(enc(&IconName::Warning), tstr("warning"), "IconName::Warning");
        assert_eq!(enc(&IconName::WorkflowApp), tstr("workflow_app"), "IconName::WorkflowApp");
        assert_eq!(enc(&IconName::X), tstr("x"), "IconName::X");
        assert_eq!(enc(&IconName::Zap), tstr("zap"), "IconName::Zap");
        assert_eq!(enc(&IconName::Zones), tstr("zones"), "IconName::Zones");
        assert_eq!(enc(&ResumeMode::Replay), tstr("replay"), "ResumeMode::Replay");
        assert_eq!(enc(&ResumeMode::Snapshot), tstr("snapshot"), "ResumeMode::Snapshot");
        assert_eq!(enc(&SessionEndCode::UserInitiated), tstr("user_initiated"), "SessionEndCode::UserInitiated");
        assert_eq!(enc(&SessionEndCode::ServerShutdown), tstr("server_shutdown"), "SessionEndCode::ServerShutdown");
        assert_eq!(enc(&SessionEndCode::IdleTimeout), tstr("idle_timeout"), "SessionEndCode::IdleTimeout");
        assert_eq!(enc(&SessionEndCode::ProtocolError), tstr("protocol_error"), "SessionEndCode::ProtocolError");
        assert_eq!(enc(&SessionEndCode::AuthExpired), tstr("auth_expired"), "SessionEndCode::AuthExpired");
        assert_eq!(enc(&SessionEndCode::Replaced), tstr("replaced"), "SessionEndCode::Replaced");
        assert_eq!(enc(&GrantRationale::InitialAdvertise), tstr("initial_advertise"), "GrantRationale::InitialAdvertise");
        assert_eq!(enc(&GrantRationale::Refill), tstr("refill"), "GrantRationale::Refill");
        assert_eq!(enc(&GrantRationale::Recovery), tstr("recovery"), "GrantRationale::Recovery");
        assert_eq!(enc(&BackpressureSeverity::Warn), tstr("warn"), "BackpressureSeverity::Warn");
        assert_eq!(enc(&BackpressureSeverity::Critical), tstr("critical"), "BackpressureSeverity::Critical");
    }
}
