// ===== File: Ui/EventKind.cs — canonical event identifiers (spec protocol/ui/a11y.rs) =====
// Wire form: tstr. Used as HandlerMap keys; the renderer whitelists browser
// events through this enum.

#nullable enable

using System;

namespace TentaFlow.Sdk.Components;

public enum EventKind
{
    Click,
    DoubleClick,
    LongPress,
    ContextMenu,

    Change,
    Input,
    Submit,
    Reset,
    Commit,

    Focus,
    Blur,
    KeyDown,
    KeyUp,
    KeyPress,
    SaveShortcut,

    Open,
    Close,
    Select,
    Deselect,
    Dismiss,
    Confirm,
    Cancel,

    DragStart,
    DragEnd,
    Drop,

    Scroll,
    ScrollEnd,
    Resize,
    Intersect,

    PointerDown,
    PointerUp,
    PointerMove,
    PointerCancel,
    Wheel,

    Play,
    Pause,
    Ended,
    Loaded,
    StreamError,
    Fullscreen,

    StreamChunk,

    RowClick,
    RowDoubleClick,
    SelectionChange,
    CellClick,
    CellHover,
    ItemClick,
    MarkerClick,
    NodeClick,
    EdgeClick,
    ZoomEnd,
    PanEnd,
    PointHover,
    RangeSelect,

    FilesSelected,
    UploadProgress,
    UploadComplete,
    UploadError,

    StepChange,
    StepClick,
    Expand,
    Collapse,

    Frame,

    Remove,
    ImageClick,
    DayClick,
    SlotClick,
    EventClick,
    EventDrop,
    CellToggle,
    CellChange,
    BulkApply,
    AddRule,
    RemoveRule,
    ApproveRule,
    MarkRead,

    FieldChange,
    ScrollTop,
    FilterChange,
    Retry,
}

public static class EventKindWireExtensions
{
    public static string WireName(this EventKind kind) => kind switch
    {
        EventKind.Click => "click",
        EventKind.DoubleClick => "double_click",
        EventKind.LongPress => "long_press",
        EventKind.ContextMenu => "context_menu",
        EventKind.Change => "change",
        EventKind.Input => "input",
        EventKind.Submit => "submit",
        EventKind.Reset => "reset",
        EventKind.Commit => "commit",
        EventKind.Focus => "focus",
        EventKind.Blur => "blur",
        EventKind.KeyDown => "key_down",
        EventKind.KeyUp => "key_up",
        EventKind.KeyPress => "key_press",
        EventKind.SaveShortcut => "save_shortcut",
        EventKind.Open => "open",
        EventKind.Close => "close",
        EventKind.Select => "select",
        EventKind.Deselect => "deselect",
        EventKind.Dismiss => "dismiss",
        EventKind.Confirm => "confirm",
        EventKind.Cancel => "cancel",
        EventKind.DragStart => "drag_start",
        EventKind.DragEnd => "drag_end",
        EventKind.Drop => "drop",
        EventKind.Scroll => "scroll",
        EventKind.ScrollEnd => "scroll_end",
        EventKind.Resize => "resize",
        EventKind.Intersect => "intersect",
        EventKind.PointerDown => "pointer_down",
        EventKind.PointerUp => "pointer_up",
        EventKind.PointerMove => "pointer_move",
        EventKind.PointerCancel => "pointer_cancel",
        EventKind.Wheel => "wheel",
        EventKind.Play => "play",
        EventKind.Pause => "pause",
        EventKind.Ended => "ended",
        EventKind.Loaded => "loaded",
        EventKind.StreamError => "stream_error",
        EventKind.Fullscreen => "fullscreen",
        EventKind.StreamChunk => "stream_chunk",
        EventKind.RowClick => "row_click",
        EventKind.RowDoubleClick => "row_double_click",
        EventKind.SelectionChange => "selection_change",
        EventKind.CellClick => "cell_click",
        EventKind.CellHover => "cell_hover",
        EventKind.ItemClick => "item_click",
        EventKind.MarkerClick => "marker_click",
        EventKind.NodeClick => "node_click",
        EventKind.EdgeClick => "edge_click",
        EventKind.ZoomEnd => "zoom_end",
        EventKind.PanEnd => "pan_end",
        EventKind.PointHover => "point_hover",
        EventKind.RangeSelect => "range_select",
        EventKind.FilesSelected => "files_selected",
        EventKind.UploadProgress => "upload_progress",
        EventKind.UploadComplete => "upload_complete",
        EventKind.UploadError => "upload_error",
        EventKind.StepChange => "step_change",
        EventKind.StepClick => "step_click",
        EventKind.Expand => "expand",
        EventKind.Collapse => "collapse",
        EventKind.Frame => "frame",
        EventKind.Remove => "remove",
        EventKind.ImageClick => "image_click",
        EventKind.DayClick => "day_click",
        EventKind.SlotClick => "slot_click",
        EventKind.EventClick => "event_click",
        EventKind.EventDrop => "event_drop",
        EventKind.CellToggle => "cell_toggle",
        EventKind.CellChange => "cell_change",
        EventKind.BulkApply => "bulk_apply",
        EventKind.AddRule => "add_rule",
        EventKind.RemoveRule => "remove_rule",
        EventKind.ApproveRule => "approve_rule",
        EventKind.MarkRead => "mark_read",
        EventKind.FieldChange => "field_change",
        EventKind.ScrollTop => "scroll_top",
        EventKind.FilterChange => "filter_change",
        EventKind.Retry => "retry",
        _ => throw new ArgumentOutOfRangeException(nameof(kind)),
    };
}
