// ============================================================================
// TENTAFLOW PROTOCOL - Wspólne typy protokołu QUIC + rkyv
// ============================================================================
//
// CEL:
// Definicje typów protokołu QUIC + rkyv używanych w komunikacji wewnątrz
// klastra TentaFlow. Typy są serializowane używając rkyv (zero-copy) dla
// maksymalnej wydajności.
//
// KLUCZOWE KONCEPCJE:
// - rkyv: Zero-copy deserialization (10x szybsze niż serde)
// - Archive: Trait dla archived representation (zero-copy access)
// - Serialize/Deserialize: Traits dla konwersji to/from archived form
// - #[archive(check_bytes)]: Runtime validation dla bezpieczeństwa
//
// UWAGI:
// - Wszystkie typy muszą implementować Archive + Serialize + Deserialize
// - Używamy #[archive(check_bytes)] dla walidacji (ochrona przed corrupted data)
// - Stringi są serializowane jako archived strings (zero-copy)
//
// ============================================================================

pub mod envelope;
pub mod mesh;
pub mod message_body;
pub mod pii;
pub mod profiling;
pub mod types;
pub mod vision;

pub use envelope::{
    message_kind, Envelope, EnvelopeFlags, Routing, SessionAuth, SignedSessionClaim, SCHEMA_VERSION,
};
pub use mesh::*;
pub use message_body::{
    // Addons + Notes + Translate + Users (theme 7 recovery).
    AddonAdminOnlySetRequest,
    AddonAdminOnlySetResponse,
    AddonConfigField,
    AddonConfigGetRequest,
    AddonConfigGetResponse,
    AddonConfigSetRequest,
    AddonConfigSetResponse,
    AddonDetailRequest,
    AddonDetailResponse,
    AddonInfo,
    AddonInstallRequest,
    AddonInstallResponse,
    AddonLogEntry,
    AddonLogsRequest,
    AddonLogsResponse,
    AddonNetworkRuleDecl,
    AddonNetworkRulesGetRequest,
    AddonNetworkRulesGetResponse,
    AddonNetworkRulesSetRequest,
    AddonNetworkRulesSetResponse,
    AddonOAuthAuthorizeStartRequest,
    AddonOAuthAuthorizeStartResponse,
    AddonOAuthConfigClearSecretRequest,
    AddonOAuthConfigClearSecretResponse,
    AddonOAuthConfigListRequest,
    AddonOAuthConfigListResponse,
    AddonOAuthConfigRow,
    AddonOAuthConfigSetRequest,
    AddonOAuthConfigSetResponse,
    AddonOAuthLinkedAccountsRequest,
    AddonOAuthLinkedAccountsResponse,
    AddonOAuthProviderDecl,
    AddonOAuthReauthorizeRequest,
    AddonOAuthReauthorizeResponse,
    AddonOAuthRevokeRequest,
    AddonOAuthRevokeResponse,
    AddonOAuthTestConnectionRequest,
    AddonOAuthTestConnectionResponse,
    AddonPermissionCatalogRequest,
    AddonPermissionCatalogResponse,
    AddonPermissionChangedEvent,
    AddonPermissionCheckRequest,
    AddonPermissionCheckResponse,
    AddonPermissionDecl,
    AddonPermissionDefault,
    AddonPermissionDefaultSetRequest,
    AddonPermissionDefaultSetResponse,
    AddonPermissionMatrixRequest,
    AddonPermissionMatrixResponse,
    AddonPermissionRow,
    AddonPermissionSetRequest,
    AddonPermissionSetResponse,
    AddonReloadRequest,
    AddonReloadResponse,
    AddonResourcesGetRequest,
    AddonResourcesGetResponse,
    AddonResourcesSetRequest,
    AddonResourcesSetResponse,
    AddonShowInCatalogSetRequest,
    AddonShowInCatalogSetResponse,
    AddonToggleRequest,
    AddonToggleResponse,
    AddonToolDecl,
    AddonToolParam,
    AddonToolsRequest,
    AddonToolsResponse,
    AddonUninstallRequest,
    AddonUninstallResponse,
    AddonVisibilityListRequest,
    AddonVisibilityListResponse,
    AddonVisibilityRow,
    AddonVisibilitySetRequest,
    AddonVisibilitySetResponse,
    AddonsListResponse,
    ApiKeyCreateRequest,
    ApiKeyCreateResponse,
    ApiKeySummary,
    AuditEvent,
    AuditLogCleanupRequest,
    AuditLogCleanupResponse,
    AuditLogEntry,
    AuditLogExportRequest,
    AuditLogExportResponse,
    AuditLogFilters,
    AuditLogListRequest,
    AuditLogListResponse,
    AuthLoginRequest,
    AuthLoginResponse,
    AuthMeResponse,
    BrowserCapturePayload,
    BrowserCaptureRequest,
    BrowserCaptureResponse,
    ChatMessage,
    ChatStreamChunk,
    ChatStreamEnd,
    ChatStreamRequest,
    ClusterAddMemberRequest,
    ClusterAddMemberResponse,
    ClusterCreateRequest,
    ClusterCreateResponse,
    ClusterDeleteRequest,
    ClusterDeleteResponse,
    ClusterDetailRequest,
    ClusterDetailResponse,
    ClusterInfo,
    ClusterListResponse,
    ClusterMember,
    ClusterProbeStreamChunk,
    ClusterProbeStreamEnd,
    ClusterProbeStreamRequest,
    ClusterRemoveMemberRequest,
    ClusterRemoveMemberResponse,
    ClusterUpdateRequest,
    ClusterUpdateResponse,
    ContainerLogChunk,
    ContainerSummary,
    DashboardSnapshot,
    DeploymentListRequest,
    DeploymentListResponse,
    DeploymentLogStreamRequest,
    DeploymentPayload,
    DeploymentStatusRequest,
    DeploymentStatusResponse,
    DeploymentStreamChunk,
    DeploymentStreamEnd,
    DeploymentSummary,
    DeployVllmConfig,
    DeployVllmGpuCompatibility,
    DeployVllmGpuInfo,
    DeployVllmModelSpecSummary,
    DeployVllmRecommendRequest,
    DeployVllmRecommendResponse,
    EngineRecommendRequest,
    EngineRecommendResponse,
    DeployVllmVramEstimate,
    FastPathPattern,
    FlowCreateRequest,
    FlowDetail,
    FlowExecutionSummary,
    FlowNodeTemplate,
    FlowNodeTemplatesListResponse,
    FlowSummary,
    FlowUpdateRequest,
    FlowUpdateResponse,
    FlowVersionFull,
    FlowVersionGetRequest,
    FlowVersionGetResponse,
    FlowVersionListRequest,
    FlowVersionListResponse,
    FlowVersionRestoreRequest,
    FlowVersionRestoreResponse,
    FlowVersionSummary,
    GroupInfo,
    HubDownloadProgress,
    HubEngineSummary,
    HubModelSearchResult,
    IamPayload,
    MeetingActionItemItem,
    MeetingActionItemStatusUpdateRequest,
    MeetingActionItemStatusUpdateResponse,
    MeetingActionItemsListRequest,
    MeetingActionItemsListResponse,
    MeetingActiveSessionRequest,
    MeetingActiveSessionResponse,
    MeetingPayload,
    MeetingSessionDescriptor,
    MeetingSessionDetailRequest,
    MeetingSessionDetailResponse,
    MeetingSessionLeaveRequest,
    MeetingSessionLeaveResponse,
    MeetingSessionListRequest,
    MeetingSessionListResponse,
    MeetingSessionStartRequest,
    MeetingSessionStartResponse,
    MeetingSettingKv,
    MeetingSettingsGetRequest,
    MeetingSettingsGetResponse,
    MeetingSettingsUpdateRequest,
    MeetingSettingsUpdateResponse,
    MeetingSummariesListRequest,
    MeetingSummariesListResponse,
    MeetingSummaryItem,
    MeetingTranscriptEntry,
    MeetingTranscriptExportRequest,
    MeetingTranscriptExportResponse,
    MeetingTranscriptsListRequest,
    MeetingTranscriptsListResponse,
    MeetingWakeWordRequest,
    MeetingWakeWordResponse,
    MePreferencesGetRequest,
    MePreferencesGetResponse,
    MePreferencesUpdateRequest,
    MePreferencesUpdateResponse,
    MeshConnState,
    MeshConnectRequest,
    MeshConnectResponse,
    MeshConnectionInfo,
    MeshConnectionPathInfo,
    MeshIdentityResponse,
    MeshNodeCommandRequest,
    MeshNodeCommandResponse,
    MeshNodeContainer,
    MeshNodeDetailRequest,
    MeshNodeDetailResponse,
    MeshNodeGpuInfo,
    MeshNodeInfo,
    MeshNodeListResponse,
    MeshNodeModel,
    MeshNodeNetworkConfigRequest,
    MeshNodeNetworkConfigResponse,
    MeshNodeNetworkInterface,
    MeshNodeRoute,
    MeshPairInitRequest,
    MeshPairInitResponse,
    MeshPairingConfirmRequest,
    MeshPairingConfirmResponse,
    MeshPairingRejectRequest,
    MeshPairingRejectResponse,
    MeshPairingStartRequest,
    MeshPairingStartResponse,
    MeshPeerSummary,
    MeshPendingListResponse,
    MeshPendingPair,
    MeshServicesEntry,
    MeshServicesListResponse,
    MeshTrustEventPayload,
    MeshTrustRetrustRequest,
    MeshTrustRetrustResponse,
    MeshTrustRevokeRequest,
    MeshTrustRevokeResponse,
    MeshTrustRevokedEvent,
    MeshTrustedKeysSyncEvent,
    MeshTrustedListResponse,
    MeshTrustedNode,
    MessageBody,
    ModelAliasCreateRequest,
    ModelAliasCreateResponse,
    ModelAliasDeleteRequest,
    ModelAliasDeleteResponse,
    ModelAliasEntry,
    ModelAliasListResponse,
    ModelAliasUpdateRequest,
    ModelAliasUpdateResponse,
    ModelDetail,
    ModelInstallRequest,
    ModelSummary,
    CatalogDiagnosticWire,
    CatalogEntryKindWire,
    CatalogEntryWire,
    CatalogListRequest,
    CatalogListResponse,
    CatalogModelInstance,
    MyOAuthAccountsListRequest,
    MyOAuthAccountsListResponse,
    MyOAuthEntry,
    NetworkConfig,
    NetworkInterfaceInfo,
    NetworkPayload,
    NgcStatusResponse,
    NimCatalogListResponse,
    NimContainerEntry,
    NoteCreateRequest,
    NoteCreateResponse,
    NoteDeleteRequest,
    NoteDeleteResponse,
    NoteDetailRequest,
    NoteDetailResponse,
    NoteEntry,
    NoteSetPinnedRequest,
    NoteSetPinnedResponse,
    NoteUpdateRequest,
    NoteUpdateResponse,
    NotesListRequest,
    NotesListResponse,
    NotesRequest,
    NotesResponse,
    PermissionEntry,
    PiiRule,
    PromptDetail,
    PromptSummary,
    KeyValue,
    ProtocolError,
    ProtocolErrorCode,
    RegistrySummary,
    RelayHealthInfo,
    RequestTimeParameters,
    ServiceChange,
    ServiceDeleteRequest,
    ServiceDeleteResponse,
    ServiceInfo,
    ServiceListRequest,
    ServiceListResponse,
    ServiceManifestDeployRequest,
    ServiceManifestDeployResponse,
    ServiceModelEntry,
    ServicePauseRequest,
    ServicePauseResponse,
    ServicePayload,
    ServicePinRequest,
    ServicePinResponse,
    ServiceStartRequest,
    ServiceStartResponse,
    ServiceUpdateRequest,
    ServiceUpdateResponse,
    ServiceVramHintRequest,
    ServiceVramHintResponse,
    ServiceEnginePresetsRequest,
    ServiceEnginePresetsResponse,
    ServicePresetInfo,
    GpuVramSnapshot,
    GpuProcessInfo,
    SettingEntry,
    SettingsUpdateRequest,
    SsoProviderCreateRequest,
    SsoProviderCreateResponse,
    SsoProviderDeleteRequest,
    SsoProviderDeleteResponse,
    SsoProviderEntry,
    SsoProvidersListResponse,
    SystemEventPayload,
    TlsStatusResponse,
    TranslatePayload,
    TranslateRequest,
    TranslateResponse,
    TtsRule,
    UserInfo,
    UserOAuthAccountRow,
    UsersListResponse,
    VncTunnelChunk,
    VncTunnelCloseRequest,
    VncTunnelCloseResponse,
    VncTunnelOpenRequest,
    VncTunnelOpenResponse,
    VncTunnelPayload,
    VncTunnelSendRequest,
    VncTunnelSendResponse,
    VncTunnelStreamEnd,
    VoiceProfileSummary,
    WakeWord,
    WakeWordOp,
    BROWSER_CAPTURE_FAILED,
    BROWSER_CAPTURE_FORBIDDEN,
    BROWSER_CAPTURE_KIND_DOM,
    BROWSER_CAPTURE_KIND_SCREENSHOT,
    BROWSER_CAPTURE_NOT_FOUND,
    BROWSER_CAPTURE_OK,
    BROWSER_CAPTURE_REMOTE_NODE,
    VNC_TUNNEL_OPEN_FAILED,
    VNC_TUNNEL_OPEN_FORBIDDEN,
    VNC_TUNNEL_OPEN_NOT_FOUND,
    VNC_TUNNEL_OPEN_NO_PORT,
    VNC_TUNNEL_OPEN_OK,
    VNC_TUNNEL_OPEN_REMOTE_NODE,
};
pub use pii::PiiRulePayload;
pub use profiling::{
    ClockSamples, CollectorRunInfo, CollectorStatus, CounterKind, DriftReport, EventCategory,
    EventPayload, Frame, GpuTargets, GpuVendor, PowerDomain, ProfileReportV2, ProfileScope,
    ProfileSourceFlags, ProfileTarget, ProfilingActiveInfoRequest,
    ProfilingActiveInfoResponse, ProfilingActiveSessionInfo, ProfilingDeleteRequest,
    ProfilingDeleteResponse, ProfilingDownloadRequest, ProfilingDownloadResponse, ProfilingPayload,
    ProfilingReportRequest, ProfilingReportResponse, ProfilingSessionEntry,
    ProfilingSessionsRequest, ProfilingSessionsResponse, ProfilingSkippedCollector,
    ProfilingStartRequest, ProfilingStartResponse, ProfilingStopRequest, ProfilingStopResponse,
    ProfilingCollectorStatus, ProfilingCollectorsStatusRequest, ProfilingCollectorsStatusResponse,
    ProfilingValidateSudoRequest, ProfilingValidateSudoResponse,
    TimelineEvent, TransferKind,
};
pub use types::*;
pub use vision::{
    VisionFaceDet, VisionImageFormat, VisionInferPayload, VisionInferRequest, VisionInferResponse,
    VisionInferResult, VisionPoseDet, VisionPoseKeypoint,
};
