// ============================================================================
// TENTAFLOW PROTOCOL - Wspólne typy protokołu QUIC + CBOR
// ============================================================================
//
// CEL:
// Definicje typów protokołu QUIC + CBOR używanych w komunikacji wewnątrz
// klastra TentaFlow.
//
// KLUCZOWE KONCEPCJE:
// - CBOR: binarny format ramek po stronie dashboardu, mesh i sidecarów
// - Serialize/Deserialize: Traits dla konwersji to/from wire form
//
// UWAGI:
// - Wszystkie typy komunikacyjne muszą implementować serde Serialize + Deserialize
//
// ============================================================================

pub mod benchmark;
pub mod bus;
pub mod camera;
pub mod cbor;
pub mod code_studio;
pub mod compliance;
pub mod envelope;
pub mod environment;
pub mod events;
pub mod legal;
pub mod mesh;
pub mod message_body;
pub mod model_conversion;
pub mod model_metrics;
pub mod pii;
pub mod profiling;
pub mod project_studio;
pub mod storage;
pub mod stream;
pub mod tentanas;
pub mod token_usage;
pub mod types;
pub mod vision;

pub use benchmark::{
    BenchmarkPayload, BenchmarkSummaryWire, BenchmarkWire, ResultRowWire, RunSummaryWire,
    TargetInputWire, TargetWire,
};
pub use bus::{
    BusAclEntryWire, BusBrowsePartitionInfoWire, BusCapabilitiesWire, BusDlqListResultWire,
    BusDlqRecordWire, BusEnvelope, BusFailoverEventWire, BusFieldPolicyWire, BusGroupDetailWire,
    BusGroupLagSummaryWire, BusGroupPartitionDetailWire, BusGroupSummaryWire, BusHeaderWire,
    BusMessagePreviewWire, BusMessagesBrowseResultWire, BusOffsetResetMode, BusPartitionInfoWire,
    BusPartitionOffsetWire, BusPartitionReplicaWire, BusPayload, BusQuotaWire, BusReplicaLagWire,
    BusReplicaNodeWire, BusSchemaSubjectWire, BusSchemaVersionWire, BusStatsSnapshotWire,
    BusTopicConfigWire, BusTopicOptionsWire, BusTopicStatsWire, BusTopicSummaryWire,
};
pub use camera::{
    CameraAddOnvifRequest, CameraAddOnvifResponse, CameraAdminPayload, CameraDetectionsFrame,
    CameraDetectionsSubscribeRequest, CameraDiscoverRequest, CameraDiscoverResponse,
    CameraFrameUrlRequest, CameraFrameUrlResponse, DetectionItem, DiscoveredCameraInfo,
};
pub use compliance::{
    ComplianceAdminPayload, ComplianceAiEventListFilter, ComplianceAiEventSummary,
    ComplianceDataCategorySummary, ComplianceLocalizedText, ComplianceRetentionPolicySummary,
};
pub use envelope::{
    message_kind, Envelope, EnvelopeFlags, Routing, SessionAuth, SignedSessionClaim, SCHEMA_VERSION,
};
pub use environment::{
    EnvironmentBundleTableCount, EnvironmentDiffEntry, EnvironmentExportBundleRequest,
    EnvironmentExportBundleResponse, EnvironmentGetKindRequest, EnvironmentGetKindResponse,
    EnvironmentImportApplyRequest, EnvironmentImportApplyResponse,
    EnvironmentImportFromFileRequest, EnvironmentImportPreviewDiffRequest,
    EnvironmentImportPreviewDiffResponse, EnvironmentPromotionPayload, EnvironmentPullDonorInfo,
    EnvironmentPullDonorListRequest, EnvironmentPullDonorListResponse, EnvironmentPullStartRequest,
    EnvironmentPullStartResponse, EnvironmentPullStatusRequest, EnvironmentPullStatusResponse,
    EnvironmentSetKindRequest, EnvironmentSetKindResponse, EnvironmentSetStrictIsolationRequest,
    EnvironmentSetStrictIsolationResponse, NodeEnvironment,
};
pub use events::{
    EventRowWire, EventsBrowseRequest, EventsBrowseResponse, EventsCursor, EventsPayload,
    EventsRunRequest, EventsRunResponse,
};
pub use legal::{
    LegalAdminPayload, LegalDocumentGenerateRequest, LegalDocumentGenerateResponse,
    LegalDocumentRevokeRequest, LegalDocumentRevokeResponse, LegalDocumentSummary,
    LegalDocumentsListRequest, LegalDocumentsListResponse,
};
pub use mesh::*;
pub use message_body::{
    AccessConsumerEntry,
    AccessMutationResponse,
    AccessTransition,
    AddonAccessDecisionRequest,
    AddonAccessListRequest,
    AddonAccessListResponse,
    // Addons + Translate + Users (theme 7 recovery).
    AddonAdminOnlySetRequest,
    AddonAdminOnlySetResponse,
    AddonApplicationInfo,
    AddonConfigField,
    AddonConfigGetRequest,
    AddonConfigGetResponse,
    AddonConfigSetRequest,
    AddonConfigSetResponse,
    AddonConnectionParam,
    AddonDetailRequest,
    AddonDetailResponse,
    AddonDocumentPayload,
    AddonDocumentUploadChunkRequest,
    AddonDocumentUploadChunkResponse,
    AddonInfo,
    AddonInstallRequest,
    AddonInstallResponse,
    AddonInstanceDuplicateRequest,
    AddonInstanceInstallRequest,
    AddonInstanceInstallResponse,
    AddonInstancePayload,
    AddonInstanceUpdateRequest,
    AddonInstanceUpdateResponse,
    AddonInstanceVersionsRequest,
    AddonInstanceVersionsResponse,
    AddonKvStats,
    AddonLogEntry,
    AddonLogsRequest,
    AddonLogsResponse,
    AddonMilvusService,
    AddonNetworkRuleDecl,
    AddonNetworkRulesGetRequest,
    AddonNetworkRulesGetResponse,
    AddonNetworkRulesSetRequest,
    AddonNetworkRulesSetResponse,
    AddonNodeStatus,
    AddonOAuthAuthorizeStartRequest,
    AddonOAuthAuthorizeStartResponse,
    AddonOAuthConfigClearSecretRequest,
    AddonOAuthConfigClearSecretResponse,
    AddonOAuthConfigListRequest,
    AddonOAuthConfigListResponse,
    AddonOAuthConfigRow,
    AddonOAuthConfigSetRequest,
    AddonOAuthConfigSetResponse,
    AddonOAuthLinkedAccountsRequest,
    AddonOAuthLinkedAccountsResponse,
    AddonOAuthProviderDecl,
    AddonOAuthReauthorizeRequest,
    AddonOAuthReauthorizeResponse,
    AddonOAuthRevokeRequest,
    AddonOAuthRevokeResponse,
    AddonOAuthTestConnectionRequest,
    AddonOAuthTestConnectionResponse,
    AddonPackageInfo,
    AddonPermissionCatalogRequest,
    AddonPermissionCatalogResponse,
    AddonPermissionChangedEvent,
    AddonPermissionCheckRequest,
    AddonPermissionCheckResponse,
    AddonPermissionDecl,
    AddonPermissionDefault,
    AddonPermissionDefaultSetRequest,
    AddonPermissionDefaultSetResponse,
    AddonPermissionMatrixRequest,
    AddonPermissionMatrixResponse,
    AddonPermissionRow,
    AddonPermissionSetRequest,
    AddonPermissionSetResponse,
    AddonRecordingStats,
    AddonReloadRequest,
    AddonReloadResponse,
    AddonResourcesGetRequest,
    AddonResourcesGetResponse,
    AddonResourcesSetRequest,
    AddonResourcesSetResponse,
    AddonShowInCatalogSetRequest,
    AddonShowInCatalogSetResponse,
    AddonSqlStats,
    AddonSqlTable,
    AddonStoragePayload,
    AddonStorageStatsRequest,
    AddonStorageStatsResponse,
    AddonTeardownDependent,
    AddonTeardownEntry,
    AddonTeardownPlanRequest,
    AddonTeardownPlanResponse,
    AddonToggleRequest,
    AddonToggleResponse,
    AddonToolDecl,
    AddonToolParam,
    AddonToolsRequest,
    AddonToolsResponse,
    AddonUiPayload,
    AddonUninstallRequest,
    AddonUninstallResponse,
    AddonUsesEntry,
    AddonVectorConfig,
    AddonVectorConfigResponse,
    AddonVectorGetConfigRequest,
    AddonVectorNamespace,
    AddonVectorPayload,
    AddonVectorServiceRef,
    AddonVectorSetConfigRequest,
    AddonVectorSetConfigResponse,
    AddonVectorStats,
    AddonVisibilityListRequest,
    AddonVisibilityListResponse,
    AddonVisibilityRow,
    AddonVisibilitySetRequest,
    AddonVisibilitySetResponse,
    AddonsListResponse,
    AgentBuilderAssistRequest,
    AgentBuilderAssistResponse,
    AgentPermissionReplyRequest,
    AgentPermissionReplyResponse,
    AgentRunCancelRequest,
    AgentRunCancelResponse,
    AgentRunDetailRequest,
    AgentRunDetailResponse,
    AgentRunEvent,
    AgentRunEventScope,
    AgentRunEventsSubscribeRequest,
    AgentRunReplyRequest,
    AgentRunReplyResponse,
    AgentRunStartRequest,
    AgentRunStartResponse,
    AgentRunsListRequest,
    AgentRunsListResponse,
    AgentsDeleteRequest,
    AgentsDeleteResponse,
    AgentsDetailRequest,
    AgentsDetailResponse,
    AgentsListRequest,
    AgentsListResponse,
    AgentsPayload,
    AgentsUpsertRequest,
    AgentsUpsertResponse,
    AliasConsumerGrantRequest,
    AliasConsumerListRequest,
    AliasConsumerListResponse,
    AliasConsumerRevokeRequest,
    AliasVisibilitySetRequest,
    ApiKeyCreateRequest,
    ApiKeyCreateResponse,
    ApiKeySummary,
    AppEntryWire,
    AuditEvent,
    AuditLogCleanupRequest,
    AuditLogCleanupResponse,
    AuditLogEntry,
    AuditLogExportRequest,
    AuditLogExportResponse,
    AuditLogFilters,
    AuditLogListRequest,
    AuditLogListResponse,
    AuthLoginRequest,
    AuthLoginResponse,
    AuthMeResponse,
    BaselineAdoptClearResponse,
    BaselineAdoptPhaseTag,
    BaselineAdoptReport,
    BaselineAdoptStartRequest,
    BaselineAdoptStartResponse,
    BaselineAdoptStatusResponse,
    BaselineDonorCandidate,
    BaselineDonorListResponse,
    BaselineDonorSummary,
    BrowserCapturePayload,
    BrowserCaptureRequest,
    BrowserCaptureResponse,
    CatalogDiagnosticWire,
    CatalogEntryKindWire,
    CatalogEntryWire,
    CatalogListRequest,
    CatalogListResponse,
    CatalogModelInstance,
    ChatMessage,
    ChatStreamChunk,
    ChatStreamEnd,
    ChatStreamRequest,
    ClassCount,
    ClusterAddMemberRequest,
    ClusterAddMemberResponse,
    ClusterCreateRequest,
    ClusterCreateResponse,
    ClusterDeleteRequest,
    ClusterDeleteResponse,
    ClusterDeployMemberStatus,
    ClusterDeployRequest,
    ClusterDeployResponse,
    ClusterDeployStopRequest,
    ClusterDeployStopResponse,
    ClusterDeploymentInfo,
    ClusterDeploymentMemberInfo,
    ClusterDetailRequest,
    ClusterDetailResponse,
    ClusterInfo,
    ClusterListResponse,
    ClusterMember,
    ClusterProbeAssignment,
    ClusterProbeStreamChunk,
    ClusterProbeStreamEnd,
    ClusterProbeStreamRequest,
    ClusterRdmaConfigureRequest,
    ClusterRdmaConfigureResponse,
    ClusterRdmaInterface,
    ClusterRdmaMemberStatus,
    ClusterRemoveMemberRequest,
    ClusterRemoveMemberResponse,
    ClusterUpdateRequest,
    ClusterUpdateResponse,
    ColumnProfile,
    ContainerLogChunk,
    ContainerPayload,
    ContainerSummary,
    DashboardSnapshot,
    DatasetSummary,
    DeployVllmConfig,
    DeployVllmGpuCompatibility,
    DeployVllmGpuInfo,
    DeployVllmModelSpecSummary,
    DeployVllmRecommendRequest,
    DeployVllmRecommendResponse,
    DeployVllmVramEstimate,
    DeploymentListRequest,
    DeploymentListResponse,
    DeploymentLogStreamRequest,
    DeploymentPayload,
    DeploymentStatusRequest,
    DeploymentStatusResponse,
    DeploymentStreamChunk,
    DeploymentStreamEnd,
    DeploymentSummary,
    EngineRecommendRequest,
    EngineRecommendResponse,
    FastPathPattern,
    FlowCreateRequest,
    FlowDetail,
    FlowExecutionSummary,
    FlowFactoryRestoreRequest,
    FlowInputValue,
    FlowInvokeChunk,
    FlowInvokeEnd,
    FlowInvokeRequest,
    FlowNodeTemplate,
    FlowNodeTemplatesListResponse,
    FlowSummary,
    FlowUpdateRequest,
    FlowUpdateResponse,
    FlowVersionFull,
    FlowVersionGetRequest,
    FlowVersionGetResponse,
    FlowVersionListRequest,
    FlowVersionListResponse,
    FlowVersionRestoreRequest,
    FlowVersionRestoreResponse,
    FlowVersionSummary,
    GenericMetricPoint,
    GpuProcessInfo,
    GpuStats,
    GpuVramSnapshot,
    GroupInfo,
    HubDownloadProgress,
    HubEngineSummary,
    HubModelSearchResult,
    IamPayload,
    KeyValue,
    MePreferencesGetRequest,
    MePreferencesGetResponse,
    MePreferencesUpdateRequest,
    MePreferencesUpdateResponse,
    MeetingActionItemItem,
    MeetingActionItemStatusUpdateRequest,
    MeetingActionItemStatusUpdateResponse,
    MeetingActionItemsListRequest,
    MeetingActionItemsListResponse,
    MeetingActiveSessionRequest,
    MeetingActiveSessionResponse,
    MeetingPayload,
    MeetingSessionDescriptor,
    MeetingSessionDetailRequest,
    MeetingSessionDetailResponse,
    MeetingSessionLeaveRequest,
    MeetingSessionLeaveResponse,
    MeetingSessionListRequest,
    MeetingSessionListResponse,
    MeetingSessionStartRequest,
    MeetingSessionStartResponse,
    MeetingSettingKv,
    MeetingSettingsGetRequest,
    MeetingSettingsGetResponse,
    MeetingSettingsUpdateRequest,
    MeetingSettingsUpdateResponse,
    MeetingSummariesListRequest,
    MeetingSummariesListResponse,
    MeetingSummaryItem,
    MeetingTranscriptEntry,
    MeetingTranscriptExportRequest,
    MeetingTranscriptExportResponse,
    MeetingTranscriptsListRequest,
    MeetingTranscriptsListResponse,
    MeetingWakeWordRequest,
    MeetingWakeWordResponse,
    MeshConnState,
    MeshConnectRequest,
    MeshConnectResponse,
    MeshConnectionInfo,
    MeshConnectionPathInfo,
    MeshGpuLink,
    MeshIdentityResponse,
    MeshNodeCommandRequest,
    MeshNodeCommandResponse,
    MeshNodeContainer,
    MeshNodeDetailRequest,
    MeshNodeDetailResponse,
    MeshNodeGpuInfo,
    MeshNodeInfo,
    MeshNodeListResponse,
    MeshNodeModel,
    MeshNodeNetworkConfigRequest,
    MeshNodeNetworkConfigResponse,
    MeshNodeNetworkInterface,
    MeshNodeRoute,
    MeshPairInitRequest,
    MeshPairInitResponse,
    MeshPairingConfirmRequest,
    MeshPairingConfirmResponse,
    MeshPairingRejectRequest,
    MeshPairingRejectResponse,
    MeshPairingStartRequest,
    MeshPairingStartResponse,
    MeshPeerSummary,
    MeshPendingListResponse,
    MeshPendingPair,
    MeshServicesEntry,
    MeshServicesListResponse,
    MeshTrustEventPayload,
    MeshTrustRetrustRequest,
    MeshTrustRetrustResponse,
    MeshTrustRevokeRequest,
    MeshTrustRevokeResponse,
    MeshTrustRevokedEvent,
    MeshTrustedKeysSyncEvent,
    MeshTrustedListResponse,
    MeshTrustedNode,
    MessageBody,
    MlStudioClassifierHyperparams,
    MlStudioClassifierTrainStartRequest,
    MlStudioClassifierTrainStartResponse,
    MlStudioDatasetProfileRequest,
    MlStudioDatasetProfileResponse,
    MlStudioDatasetRowsRequest,
    MlStudioDatasetRowsResponse,
    MlStudioDatasetRowsSaveRequest,
    MlStudioDatasetRowsSaveResponse,
    MlStudioDatasetUploadChunkRequest,
    MlStudioDatasetUploadChunkResponse,
    MlStudioDatasetUploadRequest,
    MlStudioDatasetUploadResponse,
    MlStudioDatasetsListRequest,
    MlStudioDatasetsListResponse,
    MlStudioDistConfig,
    MlStudioDistillGenerateRequest,
    MlStudioDistillGenerateResponse,
    MlStudioDistillGenerateStatusRequest,
    MlStudioDistillGenerateStatusResponse,
    MlStudioDistillQaPair,
    MlStudioFtChatRequest,
    MlStudioFtChatResponse,
    MlStudioFtDeployRequest,
    MlStudioFtDeployResponse,
    MlStudioFtExportRequest,
    MlStudioFtExportResponse,
    MlStudioFtExportStatusRequest,
    MlStudioFtExportStatusResponse,
    MlStudioFtHyperparams,
    MlStudioFtTrainStartRequest,
    MlStudioFtTrainStartResponse,
    MlStudioFtTrainStatusRequest,
    MlStudioFtTrainStatusResponse,
    MlStudioGenericTrainStatusRequest,
    MlStudioGenericTrainStatusResponse,
    MlStudioImportDatasetInfo,
    MlStudioImportMissingArtifact,
    MlStudioJobsOverviewRequest,
    MlStudioJobsOverviewResponse,
    MlStudioLookupDictDeleteRequest,
    MlStudioLookupDictDeleteResponse,
    MlStudioLookupDictSaveRequest,
    MlStudioLookupDictSaveResponse,
    MlStudioLookupDictsListRequest,
    MlStudioLookupDictsListResponse,
    MlStudioLossPoint,
    MlStudioModelSummary,
    MlStudioModelsListRequest,
    MlStudioModelsListResponse,
    MlStudioOcrHyperparams,
    MlStudioOcrTrainStartRequest,
    MlStudioOcrTrainStartResponse,
    MlStudioPayload,
    MlStudioProjectCreateRequest,
    MlStudioProjectCreateResponse,
    MlStudioProjectDetail,
    MlStudioProjectDetailRequest,
    MlStudioProjectDetailResponse,
    MlStudioProjectExportStartRequest,
    MlStudioProjectExportStartResponse,
    MlStudioProjectExportStatusRequest,
    MlStudioProjectExportStatusResponse,
    MlStudioProjectGrantsListRequest,
    MlStudioProjectGrantsListResponse,
    MlStudioProjectImportApplyRequest,
    MlStudioProjectImportApplyResponse,
    MlStudioProjectImportCancelRequest,
    MlStudioProjectImportCancelResponse,
    MlStudioProjectImportPreviewRequest,
    MlStudioProjectImportPreviewResponse,
    MlStudioProjectImportStatusRequest,
    MlStudioProjectImportStatusResponse,
    MlStudioProjectImportUploadChunkRequest,
    MlStudioProjectImportUploadChunkResponse,
    MlStudioProjectImportUploadStatusRequest,
    MlStudioProjectImportUploadStatusResponse,
    MlStudioProjectInviteRequest,
    MlStudioProjectInviteResponse,
    MlStudioProjectMember,
    MlStudioProjectMemberRemoveRequest,
    MlStudioProjectMemberRemoveResponse,
    MlStudioProjectMemberRoleSetRequest,
    MlStudioProjectMemberRoleSetResponse,
    MlStudioProjectMembersListRequest,
    MlStudioProjectMembersListResponse,
    MlStudioProjectResourcesRequest,
    MlStudioProjectResourcesResponse,
    MlStudioProjectSummary,
    MlStudioProjectTypeInfo,
    MlStudioProjectTypesListRequest,
    MlStudioProjectTypesListResponse,
    MlStudioProjectsListRequest,
    MlStudioProjectsListResponse,
    MlStudioRecogAutolabelRequest,
    MlStudioRecogAutolabelResponse,
    MlStudioRecogAutolabelStatusRequest,
    MlStudioRecogAutolabelStatusResponse,
    MlStudioRecogBuildDatasetRequest,
    MlStudioRecogBuildDatasetResponse,
    MlStudioRecogBuildStatusRequest,
    MlStudioRecogBuildStatusResponse,
    MlStudioRecogDatasetRegisterRequest,
    MlStudioRecogDatasetRegisterResponse,
    MlStudioRecogDetectRequest,
    MlStudioRecogDetectResponse,
    MlStudioRecogHyperparams,
    MlStudioRecogImageRequest,
    MlStudioRecogImageResponse,
    MlStudioRecogImagesListRequest,
    MlStudioRecogImagesListResponse,
    MlStudioRecogImportRecordingsRequest,
    MlStudioRecogImportRecordingsResponse,
    MlStudioRecogImportRecordingsStatusRequest,
    MlStudioRecogImportRecordingsStatusResponse,
    MlStudioRecogMetricPoint,
    MlStudioRecogSaveAnnotationsRequest,
    MlStudioRecogSaveAnnotationsResponse,
    MlStudioRecogStageMediaRequest,
    MlStudioRecogStageMediaResponse,
    MlStudioRecogTrainStartRequest,
    MlStudioRecogTrainStartResponse,
    MlStudioRecogTrainStatusRequest,
    MlStudioRecogTrainStatusResponse,
    MlStudioRecordingItem,
    MlStudioRecordingOutcome,
    MlStudioRecordingsListRequest,
    MlStudioRecordingsListResponse,
    MlStudioRemoteImportPreviewRequest,
    MlStudioRemoteImportPreviewResponse,
    MlStudioRemoteImportStartRequest,
    MlStudioRemoteImportStartResponse,
    MlStudioRemoteImportStatusRequest,
    MlStudioRemoteImportStatusResponse,
    MlStudioResourceGrant,
    MlStudioResourceGrantCreateRequest,
    MlStudioResourceGrantCreateResponse,
    MlStudioResourceGrantRevokeRequest,
    MlStudioResourceGrantRevokeResponse,
    MlStudioResourceGrantsListRequest,
    MlStudioResourceGrantsListResponse,
    MlStudioSchemaGetRequest,
    MlStudioSchemaGetResponse,
    MlStudioSchemaSaveRequest,
    MlStudioSchemaSaveResponse,
    MlStudioServiceModelsListRequest,
    MlStudioServiceModelsListResponse,
    MlStudioTabularLeaderboardEntry,
    MlStudioTabularTrainRequest,
    MlStudioTabularTrainResponse,
    MlStudioTrainCancelRequest,
    MlStudioTrainCancelResponse,
    MlStudioTrainingRunSummary,
    MlStudioTrainingRunsListRequest,
    MlStudioTrainingRunsListResponse,
    MlStudioVisionModelDeleteRequest,
    MlStudioVisionModelDeleteResponse,
    MlStudioVisionModelInfo,
    MlStudioVisionModelPublishRequest,
    MlStudioVisionModelPublishResponse,
    MlStudioVisionModelsListRequest,
    MlStudioVisionModelsListResponse,
    ModelAliasCreateRequest,
    ModelAliasCreateResponse,
    ModelAliasDeleteRequest,
    ModelAliasDeleteResponse,
    ModelAliasEntry,
    ModelAliasListResponse,
    ModelAliasUpdateRequest,
    ModelAliasUpdateResponse,
    ModelConsumerGrantRequest,
    ModelConsumerListRequest,
    ModelConsumerListResponse,
    ModelConsumerRevokeRequest,
    ModelDetail,
    ModelInstallRequest,
    ModelPricingInput,
    ModelSummary,
    ModelVisibilityEntry,
    ModelVisibilityListResponse,
    ModelVisibilitySetRequest,
    MyOAuthAccountsListRequest,
    MyOAuthAccountsListResponse,
    MyOAuthEntry,
    NetworkConfig,
    NetworkInterfaceInfo,
    NetworkPayload,
    NgcStatusResponse,
    NimCatalogListResponse,
    NimContainerEntry,
    PermissionEntry,
    PiiRule,
    PromptDetail,
    PromptSummary,
    ProtocolError,
    ProtocolErrorCode,
    RegistrySummary,
    RelayHealthInfo,
    RequestTimeParameters,
    ResourceRef,
    RobotActionMeta,
    RobotActionParam,
    RobotActionWire,
    RobotBatterySnapshot,
    RobotCameraShareRequest,
    RobotCameraShareResponse,
    RobotControlRequest,
    RobotControlResponse,
    RobotEntry,
    RobotGeoAnchorGetRequest,
    RobotGeoAnchorResponse,
    RobotGeoAnchorSetRequest,
    RobotImuSnapshot,
    RobotLidarStatus,
    RobotTelemetrySnapshot,
    RobotsListRequest,
    RobotsListResponse,
    RobotsPayload,
    SchedulerActionsListRequest,
    SchedulerActionsListResponse,
    SchedulerJobDeleteRequest,
    SchedulerJobDeleteResponse,
    SchedulerJobRunNowRequest,
    SchedulerJobRunNowResponse,
    SchedulerJobUpsertRequest,
    SchedulerJobUpsertResponse,
    SchedulerJobsListRequest,
    SchedulerJobsListResponse,
    SchedulerPayload,
    SchedulerRunsListRequest,
    SchedulerRunsListResponse,
    ServiceAgentRequest,
    ServiceAgentResponse,
    ServiceChange,
    ServiceDeleteRequest,
    ServiceDeleteResponse,
    ServiceEnginePresetsRequest,
    ServiceEnginePresetsResponse,
    ServiceInfo,
    ServiceListRequest,
    ServiceListResponse,
    ServiceManifestDeployRequest,
    ServiceManifestDeployResponse,
    ServiceModelCatalogEntry,
    ServiceModelCatalogRequest,
    ServiceModelCatalogResponse,
    ServiceModelEntry,
    ServiceModelSelectionRequest,
    ServiceModelSelectionResponse,
    ServiceOauthPollRequest,
    ServiceOauthPollResponse,
    ServiceOauthStartRequest,
    ServiceOauthStartResponse,
    ServicePauseRequest,
    ServicePauseResponse,
    ServicePayload,
    ServicePinRequest,
    ServicePinResponse,
    ServicePresetInfo,
    ServiceRedeployRequest,
    ServiceRedeployResponse,
    ServiceStartRequest,
    ServiceStartResponse,
    ServiceUpdateRequest,
    ServiceUpdateResponse,
    ServiceVramHintRequest,
    ServiceVramHintResponse,
    SettingEntry,
    SettingsUpdateRequest,
    SkillsCuratorApplyRequest,
    SkillsCuratorApplyResponse,
    SkillsCuratorRollbackRequest,
    SkillsCuratorRollbackResponse,
    SkillsCuratorRunRequest,
    SkillsCuratorRunResponse,
    SkillsDeleteRequest,
    SkillsDeleteResponse,
    SkillsDetailRequest,
    SkillsDetailResponse,
    SkillsForkRequest,
    SkillsForkResponse,
    SkillsHubApproveRequest,
    SkillsHubApproveResponse,
    SkillsHubImportRequest,
    SkillsHubImportResponse,
    SkillsHubRejectRequest,
    SkillsHubRejectResponse,
    SkillsHubSearchRequest,
    SkillsHubSearchResponse,
    SkillsListRequest,
    SkillsListResponse,
    SkillsPayload,
    SkillsUpsertRequest,
    SkillsUpsertResponse,
    SsoProviderCreateRequest,
    SsoProviderCreateResponse,
    SsoProviderDeleteRequest,
    SsoProviderDeleteResponse,
    SsoProviderEntry,
    SsoProvidersListResponse,
    SuggestServicePortRequest,
    SuggestServicePortResponse,
    SyncConflictPayload,
    SyncConflictResolution,
    SyncConflictResolveRequest,
    SyncConflictResolveResponse,
    SyncConflictRow,
    SyncConflictsListRequest,
    SyncConflictsListResponse,
    SyncStoragePathUsage,
    SyncStoragePayload,
    SyncStoragePressureLevel,
    SyncStorageReportRequest,
    SyncStorageReportResponse,
    SystemEventPayload,
    TableProfile,
    TlsStatusResponse,
    ToolsCatalogRequest,
    ToolsCatalogResponse,
    TrainingJobInfo,
    TranslatePayload,
    TranslateRequest,
    TranslateResponse,
    TtsRule,
    UserInfo,
    UserOAuthAccountRow,
    UsersListResponse,
    VisionImportFetchManifestRequest,
    VisionImportFetchManifestResponse,
    VisionImportManifestFile,
    VisionImportManifestModel,
    VisionImportModelRequest,
    VisionImportModelResponse,
    VisionImportPayload,
    VncTunnelChunk,
    VncTunnelCloseRequest,
    VncTunnelCloseResponse,
    VncTunnelOpenRequest,
    VncTunnelOpenResponse,
    VncTunnelPayload,
    VncTunnelSendRequest,
    VncTunnelSendResponse,
    VncTunnelStreamEnd,
    VoiceProfileSummary,
    WakeWord,
    WakeWordOp,
    BROWSER_CAPTURE_FAILED,
    BROWSER_CAPTURE_FORBIDDEN,
    BROWSER_CAPTURE_KIND_DOM,
    BROWSER_CAPTURE_KIND_SCREENSHOT,
    BROWSER_CAPTURE_NOT_FOUND,
    BROWSER_CAPTURE_OK,
    BROWSER_CAPTURE_REMOTE_NODE,
    UPLOAD_SOURCE_AUDIO_CAPTURE,
    VNC_TUNNEL_OPEN_FAILED,
    VNC_TUNNEL_OPEN_FORBIDDEN,
    VNC_TUNNEL_OPEN_NOT_FOUND,
    VNC_TUNNEL_OPEN_NO_PORT,
    VNC_TUNNEL_OPEN_OK,
    VNC_TUNNEL_OPEN_REMOTE_NODE,
};
pub use model_conversion::{
    ModelConversionPayload, ModelConversionStartRequest, ModelConversionStartResponse,
    ModelConversionStatusRequest, ModelConversionStatusResponse,
};
pub use model_metrics::{
    ModelMetricsFilterWire, ModelMetricsPayload, ModelMetricsRowWire, ModelNodeServiceRowWire,
    ModelPricingWire,
};
pub use pii::PiiRulePayload;
pub use profiling::{
    ClockSamples, CollectorRunInfo, CollectorStatus, CounterKind, DriftReport, EventCategory,
    EventPayload, Frame, GpuTargets, GpuVendor, PowerDomain, ProfileReportV2, ProfileScope,
    ProfileSourceFlags, ProfileTarget, ProfilingActiveInfoRequest, ProfilingActiveInfoResponse,
    ProfilingActiveSessionInfo, ProfilingCollectorStatus, ProfilingCollectorsStatusRequest,
    ProfilingCollectorsStatusResponse, ProfilingDeleteRequest, ProfilingDeleteResponse,
    ProfilingDownloadRequest, ProfilingDownloadResponse, ProfilingPayload, ProfilingReportRequest,
    ProfilingReportResponse, ProfilingSessionEntry, ProfilingSessionsRequest,
    ProfilingSessionsResponse, ProfilingSkippedCollector, ProfilingStartRequest,
    ProfilingStartResponse, ProfilingStopRequest, ProfilingStopResponse,
    ProfilingValidateSudoRequest, ProfilingValidateSudoResponse, TimelineEvent, TransferKind,
};
pub use storage::{
    StorageAdminPayload, StorageBrowseRequest, StorageBrowseResponse, StorageCategoryInfo,
    StorageCreateDirRequest, StorageCreateDirResponse, StorageDirEntry, StorageMigrateRequest,
    StorageMigrateResponse, StorageOverviewResponse,
};
pub use stream::{
    StreamCloseRequest, StreamClosedPayload, StreamFramePayload, StreamPayload,
    StreamSubscribeRequest, StreamSubscribeResponse,
};
pub use token_usage::{
    TokenLeaseWire, TokenQuotaUpsertWire, TokenQuotaWire, TokenUsagePayload, TokenUsageSummaryWire,
};
pub use types::*;
pub use vision::{
    VisionFaceDet, VisionImageFormat, VisionInferPayload, VisionInferRequest, VisionInferResponse,
    VisionInferResult, VisionPoseDet, VisionPoseKeypoint,
};
