// =============================================================================
// File: gen_csharp.rs — C# SDK source generator
// Reads ManifestEnvelope, emits a single .cs file with all components,
// enums, inline structs and tagged unions for TentaFlow.Sdk.Components.
// =============================================================================

use std::fmt::Write;

use crate::{
    ComponentEntry, EnumEntry, FieldEntry, InlineEntry, ManifestEnvelope, UnionEntry,
    VariantEntry,
};

/// Produce a complete C# source file from the manifest.
pub fn generate(manifest: &ManifestEnvelope) -> String {
    let mut out = String::with_capacity(128 * 1024);
    emit_header(&mut out);
    emit_enums(&mut out, &manifest.enums);
    emit_inline_structs(&mut out, &manifest.inline_structs);
    emit_tagged_unions(&mut out, &manifest.tagged_unions);
    emit_components(&mut out, &manifest.components);
    out
}

fn emit_header(out: &mut String) {
    out.push_str("// Auto-generated by tentaflow-sdk-gen — DO NOT EDIT\n");
    out.push_str("#nullable enable\n\n");
    out.push_str("using System;\n");
    out.push_str("using System.Collections.Generic;\n\n");
    out.push_str("namespace TentaFlow.Sdk.Components;\n\n");
}

fn emit_enums(out: &mut String, enums: &[EnumEntry]) {
    for e in enums {
        let _ = writeln!(out, "/// <summary>Enum: {}</summary>", e.name);
        let _ = writeln!(out, "public enum {} {{", e.name);
        for (i, v) in e.variants.iter().enumerate() {
            let comma = if i + 1 < e.variants.len() { "," } else { "" };
            let _ = writeln!(
                out,
                "    [Wire(\"{wire}\")] {name}{comma}",
                wire = v.wire,
                name = v.rust_name,
            );
        }
        out.push_str("}\n\n");
    }
}

fn emit_inline_structs(out: &mut String, inlines: &[InlineEntry]) {
    for s in inlines {
        let _ = writeln!(out, "/// <summary>Inline struct: {}</summary>", s.name);
        let _ = writeln!(out, "public sealed class {} {{", s.name);
        emit_field_properties(out, &s.fields);
        emit_to_field_map(out, &s.fields);
        out.push_str("}\n\n");
    }
}

fn emit_tagged_unions(out: &mut String, unions: &[UnionEntry]) {
    for u in unions {
        let _ = writeln!(
            out,
            "/// <summary>Tagged union: {} (discriminator: \"{}\")</summary>",
            u.name, u.discriminator_key
        );
        let _ = writeln!(out, "public abstract class {} {{", u.name);
        let _ = writeln!(
            out,
            "    public abstract string {}Kind {{ get; }}",
            u.name
        );
        out.push_str("}\n\n");
        for v in &u.variants {
            emit_union_variant(out, &u.name, v);
        }
    }
}

fn emit_union_variant(out: &mut String, union_name: &str, v: &VariantEntry) {
    let class_name = format!("{}{}", union_name, v.rust_name);
    let _ = writeln!(
        out,
        "/// <summary>{} variant: {} (wire kind \"{}\")</summary>",
        union_name, v.rust_name, v.wire_kind
    );
    let _ = writeln!(
        out,
        "public sealed class {} : {} {{",
        class_name, union_name
    );
    let _ = writeln!(
        out,
        "    public override string {}Kind => \"{}\";",
        union_name, v.wire_kind
    );
    if !v.fields.is_empty() {
        out.push('\n');
        emit_field_properties(out, &v.fields);
    }
    out.push_str("}\n\n");
}

fn emit_components(out: &mut String, components: &[ComponentEntry]) {
    for c in components {
        let _ = writeln!(
            out,
            "/// <summary>{} component (tag 0x{:04X}, §{})</summary>",
            c.name, c.tag, c.section
        );
        let _ = writeln!(
            out,
            "public sealed class {} : Component {{",
            c.name
        );
        let _ = writeln!(out, "    public const ushort Tag = 0x{:04X};", c.tag);
        if !c.handlers.is_empty() {
            out.push('\n');
            for h in &c.handlers {
                let _ = writeln!(
                    out,
                    "    public const string Handler{} = \"{}\";",
                    to_pascal_case(h),
                    h
                );
            }
        }
        out.push('\n');
        emit_field_properties(out, &c.fields);
        emit_to_field_map(out, &c.fields);
        out.push_str("}\n\n");
    }
}

fn emit_field_properties(out: &mut String, fields: &[FieldEntry]) {
    for f in fields {
        let cs_type = wire_to_csharp(&f.wire);
        let prop_name = to_pascal_case(&f.name);
        let default = csharp_default(&f.wire, &f.default, f.required);
        let _ = writeln!(
            out,
            "    /// <summary>Field {}: {} ({})</summary>",
            f.key, f.name, f.wire
        );
        let _ = writeln!(
            out,
            "    public {ty} {name} {{ get; set; }}{def}",
            ty = cs_type,
            name = prop_name,
            def = default,
        );
    }
}

fn emit_to_field_map(out: &mut String, fields: &[FieldEntry]) {
    out.push('\n');
    out.push_str("    public FieldMap ToFieldMap() {\n");
    out.push_str("        var map = new FieldMap();\n");
    for f in fields {
        let prop = to_pascal_case(&f.name);
        let is_optional = f.wire.starts_with("Option<");
        let inner_wire = if is_optional {
            &f.wire[7..f.wire.len() - 1]
        } else {
            &f.wire
        };
        let setter = field_map_setter(inner_wire, &prop);
        if is_optional {
            let _ = writeln!(
                out,
                "        if ({prop} != null) map.Set({key}, {setter});",
                prop = prop,
                key = f.key,
                setter = setter,
            );
        } else {
            let _ = writeln!(
                out,
                "        map.Set({key}, {setter});",
                key = f.key,
                setter = setter,
            );
        }
    }
    out.push_str("        return map;\n");
    out.push_str("    }\n");
}

/// Produce the `Value.Xxx(...)` expression for a field setter.
fn field_map_setter(inner_wire: &str, prop: &str) -> String {
    if inner_wire == "tstr" {
        return format!("Value.Text({prop})");
    }
    if inner_wire == "bool" {
        return format!("Value.Bool({prop})");
    }
    if inner_wire == "Value" || inner_wire == "CborMap" {
        return format!("Value.Raw({prop})");
    }
    if inner_wire == "BindRef" || inner_wire == "StatePath" {
        return format!("Value.Text({prop}.ToString())");
    }
    if matches!(
        inner_wire,
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64"
    ) {
        return format!("Value.Int({prop})");
    }
    if inner_wire == "f32" || inner_wire == "f64" {
        return format!("Value.Float({prop})");
    }
    if inner_wire.starts_with("Enum<") {
        return format!("{prop}.ToWire()");
    }
    if inner_wire.starts_with("Inline<") || inner_wire.starts_with("ComponentRef<") {
        return format!("{prop}.ToFieldMap()");
    }
    if inner_wire == "Component" {
        return format!("{prop}.ToFieldMap()");
    }
    if inner_wire.starts_with("Array<") {
        return format!("Value.Array({prop})");
    }
    format!("Value.Raw({prop})")
}

/// Map a manifest wire type string to a C# type string.
fn wire_to_csharp(wire: &str) -> String {
    if let Some(inner) = wire.strip_prefix("Option<").and_then(|s| s.strip_suffix('>')) {
        let base = wire_to_csharp(inner);
        // Value types need ? suffix, reference types are already nullable
        if is_csharp_value_type(inner) {
            return format!("{base}?");
        }
        return base;
    }
    if let Some(inner) = wire.strip_prefix("Array<").and_then(|s| s.strip_suffix('>')) {
        let elem = wire_to_csharp(inner);
        return format!("List<{elem}>");
    }
    if let Some(name) = wire.strip_prefix("Enum<").and_then(|s| s.strip_suffix('>')) {
        return name.to_string();
    }
    if let Some(name) = wire.strip_prefix("Inline<").and_then(|s| s.strip_suffix('>')) {
        return name.to_string();
    }
    if let Some(_name) = wire.strip_prefix("ComponentRef<").and_then(|s| s.strip_suffix('>')) {
        return "Component".to_string();
    }
    match wire {
        "tstr" => "string".to_string(),
        "bool" => "bool".to_string(),
        "u8" => "byte".to_string(),
        "u16" => "ushort".to_string(),
        "u32" => "uint".to_string(),
        "u64" => "ulong".to_string(),
        "i8" => "sbyte".to_string(),
        "i16" => "short".to_string(),
        "i32" => "int".to_string(),
        "i64" => "long".to_string(),
        "f32" => "float".to_string(),
        "f64" => "double".to_string(),
        "BindRef" => "BindRef".to_string(),
        "StatePath" => "StatePath".to_string(),
        "Value" => "Value".to_string(),
        "CborMap" => "Value".to_string(),
        "Component" => "Component".to_string(),
        other => other.to_string(),
    }
}

fn is_csharp_value_type(wire: &str) -> bool {
    matches!(
        wire,
        "bool"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "i8"
            | "i16"
            | "i32"
            | "i64"
            | "f32"
            | "f64"
    ) || wire.starts_with("Enum<")
}

fn csharp_default(wire: &str, default: &Option<String>, _required: bool) -> String {
    if wire.starts_with("Option<") {
        return String::new();
    }
    if let Some(d) = default {
        let cs_type_base = wire;
        if cs_type_base == "tstr" {
            return format!(" = \"{d}\";");
        }
        if cs_type_base == "bool" {
            let val = if d == "true" { "true" } else { "false" };
            return format!(" = {val};");
        }
        if matches!(
            cs_type_base,
            "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64"
        ) {
            return format!(" = {d};");
        }
        if cs_type_base == "f32" || cs_type_base == "f64" {
            let suffix = if cs_type_base == "f32" { "f" } else { "d" };
            return format!(" = {d}{suffix};");
        }
        if let Some(enum_name) = cs_type_base
            .strip_prefix("Enum<")
            .and_then(|s| s.strip_suffix('>'))
        {
            return format!(" = {enum_name}.{d};");
        }
        return format!(" = {d};");
    }
    // Non-optional fields without explicit defaults need sensible zero values
    match wire {
        "tstr" => " = \"\";".to_string(),
        "bool" => " = false;".to_string(),
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => " = 0;".to_string(),
        "f32" | "f64" => " = 0;".to_string(),
        w if w.starts_with("Array<") => {
            let elem = wire_to_csharp(&w[6..w.len() - 1]);
            format!(" = new List<{elem}>();")
        }
        _ => String::new(),
    }
}

/// Convert `snake_case` to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => {
                    let mut r = c.to_uppercase().to_string();
                    r.extend(chars);
                    r
                }
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{build_manifest, EnumVariant};

    #[test]
    fn generates_enums() {
        let enums = vec![EnumEntry {
            name: "ButtonVariant".into(),
            variants: vec![
                EnumVariant {
                    rust_name: "Primary".into(),
                    wire: "primary".into(),
                },
                EnumVariant {
                    rust_name: "Secondary".into(),
                    wire: "secondary".into(),
                },
            ],
        }];
        let manifest = ManifestEnvelope {
            protocol_version: 1,
            components: vec![],
            enums,
            inline_structs: vec![],
            tagged_unions: vec![],
        };
        let code = generate(&manifest);
        assert!(code.contains("public enum ButtonVariant {"));
        assert!(code.contains("[Wire(\"primary\")] Primary,"));
        assert!(code.contains("[Wire(\"secondary\")] Secondary"));
    }

    #[test]
    fn generates_component() {
        let components = vec![ComponentEntry {
            tag: 0x0200,
            name: "Text".into(),
            section: "4 Data Display".into(),
            fields: vec![
                FieldEntry {
                    key: 0,
                    name: "content".into(),
                    wire: "tstr".into(),
                    required: true,
                    default: None,
                },
                FieldEntry {
                    key: 1,
                    name: "style".into(),
                    wire: "Option<Enum<TextStyle>>".into(),
                    required: false,
                    default: None,
                },
            ],
            handlers: vec!["on_click".into()],
        }];
        let manifest = ManifestEnvelope {
            protocol_version: 1,
            components,
            enums: vec![],
            inline_structs: vec![],
            tagged_unions: vec![],
        };
        let code = generate(&manifest);
        assert!(code.contains("public sealed class Text : Component {"));
        assert!(code.contains("public const ushort Tag = 0x0200;"));
        assert!(code.contains("public string Content { get; set; } = \"\";"));
        assert!(code.contains("public TextStyle? Style { get; set; }"));
        assert!(code.contains("public const string HandlerOnClick = \"on_click\";"));
    }

    #[test]
    fn full_manifest_generates() {
        let manifest = build_manifest();
        let code = generate(&manifest);
        assert!(!code.is_empty());
        assert!(code.contains("namespace TentaFlow.Sdk.Components;"));
        // Every component produces a class
        for c in &manifest.components {
            assert!(
                code.contains(&format!("public sealed class {} : Component", c.name)),
                "missing component class: {}",
                c.name
            );
        }
        // Every enum produces an enum
        for e in &manifest.enums {
            assert!(
                code.contains(&format!("public enum {} {{", e.name)),
                "missing enum: {}",
                e.name
            );
        }
    }

    #[test]
    fn wire_type_mapping() {
        assert_eq!(wire_to_csharp("tstr"), "string");
        assert_eq!(wire_to_csharp("u32"), "uint");
        assert_eq!(wire_to_csharp("f64"), "double");
        assert_eq!(wire_to_csharp("bool"), "bool");
        assert_eq!(wire_to_csharp("Option<tstr>"), "string");
        assert_eq!(wire_to_csharp("Option<u32>"), "uint?");
        assert_eq!(wire_to_csharp("Array<tstr>"), "List<string>");
        assert_eq!(wire_to_csharp("Enum<ButtonVariant>"), "ButtonVariant");
        assert_eq!(wire_to_csharp("Option<Enum<Tone>>"), "Tone?");
        assert_eq!(wire_to_csharp("Inline<Handler>"), "Handler");
        assert_eq!(wire_to_csharp("ComponentRef<Button>"), "Component");
        assert_eq!(wire_to_csharp("Array<Component>"), "List<Component>");
        assert_eq!(wire_to_csharp("BindRef"), "BindRef");
        assert_eq!(wire_to_csharp("StatePath"), "StatePath");
        assert_eq!(wire_to_csharp("Value"), "Value");
        assert_eq!(wire_to_csharp("CborMap"), "Value");
    }

    #[test]
    fn pascal_case_conversion() {
        assert_eq!(to_pascal_case("on_click"), "OnClick");
        assert_eq!(to_pascal_case("content"), "Content");
        assert_eq!(to_pascal_case("aria_label"), "AriaLabel");
        assert_eq!(to_pascal_case("x"), "X");
    }
}
