// =============================================================================
// File: gen_python.rs — Python SDK source generator
// Reads ManifestEnvelope, emits a single .py file with all components,
// enums, inline structs and tagged unions for tentaflow_sdk.components.
// =============================================================================

use std::fmt::Write;

use crate::{
    ComponentEntry, EnumEntry, FieldEntry, InlineEntry, ManifestEnvelope, UnionEntry,
    VariantEntry,
};

/// Produce a complete Python source file from the manifest.
pub fn generate(manifest: &ManifestEnvelope) -> String {
    let mut out = String::with_capacity(128 * 1024);
    emit_header(&mut out);
    emit_enums(&mut out, &manifest.enums);
    emit_inline_structs(&mut out, &manifest.inline_structs);
    emit_tagged_unions(&mut out, &manifest.tagged_unions);
    emit_components(&mut out, &manifest.components);
    out
}

fn emit_header(out: &mut String) {
    out.push_str("# Auto-generated by tentaflow-sdk-gen — DO NOT EDIT\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass, field\n");
    out.push_str("from enum import Enum\n");
    out.push_str("from typing import Any, List, Optional\n\n\n");
}

fn emit_enums(out: &mut String, enums: &[EnumEntry]) {
    for e in enums {
        let _ = writeln!(out, "class {}(Enum):", e.name);
        let _ = writeln!(out, "    \"\"\"Enum: {}\"\"\"", e.name);
        if e.variants.is_empty() {
            out.push_str("    pass\n");
        } else {
            for v in &e.variants {
                let _ = writeln!(
                    out,
                    "    {} = \"{}\"",
                    rust_name_to_screaming_snake(&v.rust_name),
                    v.wire
                );
            }
        }
        out.push_str("\n\n");
    }
}

fn emit_inline_structs(out: &mut String, inlines: &[InlineEntry]) {
    for s in inlines {
        out.push_str("@dataclass\n");
        let _ = writeln!(out, "class {}:", s.name);
        let _ = writeln!(out, "    \"\"\"Inline struct: {}\"\"\"", s.name);
        if s.fields.is_empty() {
            out.push_str("    pass\n");
        } else {
            emit_dataclass_fields(out, &s.fields);
            out.push('\n');
            emit_to_field_map_py(out, &s.fields);
        }
        out.push_str("\n\n");
    }
}

fn emit_tagged_unions(out: &mut String, unions: &[UnionEntry]) {
    for u in unions {
        // Abstract base
        out.push_str("@dataclass\n");
        let _ = writeln!(out, "class {}:", u.name);
        let _ = writeln!(
            out,
            "    \"\"\"Tagged union: {} (discriminator: \\\"{}\\\")\"\"\"",
            u.name, u.discriminator_key
        );
        out.push_str("    pass\n\n\n");

        for v in &u.variants {
            emit_union_variant_py(out, &u.name, v);
        }
    }
}

fn emit_union_variant_py(out: &mut String, union_name: &str, v: &VariantEntry) {
    let class_name = format!("{}{}", union_name, v.rust_name);
    out.push_str("@dataclass\n");
    let _ = writeln!(out, "class {}({}):", class_name, union_name);
    let _ = writeln!(
        out,
        "    \"\"\"Variant {} (wire kind \\\"{}\\\")\"\"\"",
        v.rust_name, v.wire_kind
    );
    let _ = writeln!(out, "    KIND: str = \"{}\"", v.wire_kind);
    if !v.fields.is_empty() {
        emit_dataclass_fields(out, &v.fields);
    }
    out.push_str("\n\n");
}

fn emit_components(out: &mut String, components: &[ComponentEntry]) {
    for c in components {
        out.push_str("@dataclass\n");
        let _ = writeln!(out, "class {}(Component):", c.name);
        let _ = writeln!(
            out,
            "    \"\"\"Component {} (tag 0x{:04X}, section {})\"\"\"",
            c.name, c.tag, c.section
        );
        let _ = writeln!(out, "    TAG: int = 0x{:04X}", c.tag);
        if !c.handlers.is_empty() {
            for h in &c.handlers {
                let _ = writeln!(
                    out,
                    "    HANDLER_{}: str = \"{}\"",
                    h.to_uppercase(),
                    h
                );
            }
        }
        if c.fields.is_empty() {
            out.push_str("    pass\n");
        } else {
            emit_dataclass_fields(out, &c.fields);
            out.push('\n');
            emit_to_field_map_py(out, &c.fields);
        }
        out.push_str("\n\n");
    }
}

fn emit_dataclass_fields(out: &mut String, fields: &[FieldEntry]) {
    // Emit required fields (no default) first, then optional/defaulted fields.
    // Python dataclass rules: fields without defaults must precede fields with defaults.
    let (required, defaulted): (Vec<_>, Vec<_>) = fields
        .iter()
        .partition(|f| f.required && f.default.is_none() && !f.wire.starts_with("Option<"));

    for f in &required {
        let py_type = wire_to_python(&f.wire);
        let _ = writeln!(out, "    {}: {}", f.name, py_type);
    }
    for f in &defaulted {
        let py_type = wire_to_python(&f.wire);
        let default = python_default(&f.wire, &f.default);
        let _ = writeln!(out, "    {}: {} = {}", f.name, py_type, default);
    }
}

fn emit_to_field_map_py(out: &mut String, fields: &[FieldEntry]) {
    out.push_str("    def to_field_map(self) -> FieldMap:\n");
    out.push_str("        m = FieldMap()\n");
    for f in fields {
        let is_optional = f.wire.starts_with("Option<");
        let inner_wire = if is_optional {
            &f.wire[7..f.wire.len() - 1]
        } else {
            &f.wire
        };
        let value_expr = python_value_expr(inner_wire, &f.name);
        if is_optional {
            let _ = writeln!(
                out,
                "        if self.{name} is not None:\n            m.set({key}, {val})",
                name = f.name,
                key = f.key,
                val = value_expr,
            );
        } else {
            let _ = writeln!(
                out,
                "        m.set({key}, {val})",
                key = f.key,
                val = value_expr,
            );
        }
    }
    out.push_str("        return m\n");
}

fn python_value_expr(inner_wire: &str, field_name: &str) -> String {
    if inner_wire == "tstr" || inner_wire == "BindRef" || inner_wire == "StatePath" {
        return format!("str(self.{field_name})");
    }
    if inner_wire.starts_with("Enum<") {
        return format!("self.{field_name}.value");
    }
    if inner_wire.starts_with("Inline<")
        || inner_wire.starts_with("ComponentRef<")
        || inner_wire == "Component"
    {
        return format!("self.{field_name}.to_field_map()");
    }
    format!("self.{field_name}")
}

/// Map a manifest wire type string to a Python type annotation.
fn wire_to_python(wire: &str) -> String {
    if let Some(inner) = wire.strip_prefix("Option<").and_then(|s| s.strip_suffix('>')) {
        let base = wire_to_python(inner);
        return format!("Optional[{base}]");
    }
    if let Some(inner) = wire.strip_prefix("Array<").and_then(|s| s.strip_suffix('>')) {
        let elem = wire_to_python(inner);
        return format!("List[{elem}]");
    }
    if let Some(name) = wire.strip_prefix("Enum<").and_then(|s| s.strip_suffix('>')) {
        return name.to_string();
    }
    if let Some(name) = wire.strip_prefix("Inline<").and_then(|s| s.strip_suffix('>')) {
        return name.to_string();
    }
    if let Some(_name) = wire.strip_prefix("ComponentRef<").and_then(|s| s.strip_suffix('>')) {
        return "Component".to_string();
    }
    match wire {
        "tstr" => "str".to_string(),
        "bool" => "bool".to_string(),
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => "int".to_string(),
        "f32" | "f64" => "float".to_string(),
        "BindRef" => "BindRef".to_string(),
        "StatePath" => "StatePath".to_string(),
        "Value" | "CborMap" => "Any".to_string(),
        "Component" => "Component".to_string(),
        other => other.to_string(),
    }
}

fn python_default(wire: &str, default: &Option<String>) -> String {
    if wire.starts_with("Option<") {
        return "None".to_string();
    }
    if let Some(d) = default {
        if wire == "tstr" {
            return format!("\"{d}\"");
        }
        if wire == "bool" {
            return if d == "true" {
                "True".to_string()
            } else {
                "False".to_string()
            };
        }
        if matches!(
            wire,
            "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "f32" | "f64"
        ) {
            return d.clone();
        }
        if wire.starts_with("Enum<") {
            if let Some(enum_name) = wire.strip_prefix("Enum<").and_then(|s| s.strip_suffix('>')) {
                return format!(
                    "{}.{}",
                    enum_name,
                    rust_name_to_screaming_snake(d)
                );
            }
        }
        return d.clone();
    }
    // Non-optional fields without explicit defaults
    match wire {
        "tstr" => "\"\"".to_string(),
        "bool" => "False".to_string(),
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "f32" | "f64" => {
            "0".to_string()
        }
        w if w.starts_with("Array<") => "field(default_factory=list)".to_string(),
        _ => "None".to_string(),
    }
}

/// Convert `PascalCase` or `CamelCase` to `SCREAMING_SNAKE_CASE`.
fn rust_name_to_screaming_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            let prev = s.as_bytes()[i - 1] as char;
            if prev.is_lowercase() || prev.is_ascii_digit() {
                out.push('_');
            }
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{build_manifest, EnumVariant};

    #[test]
    fn generates_enums() {
        let enums = vec![EnumEntry {
            name: "ButtonVariant".into(),
            variants: vec![
                EnumVariant {
                    rust_name: "Primary".into(),
                    wire: "primary".into(),
                },
                EnumVariant {
                    rust_name: "Secondary".into(),
                    wire: "secondary".into(),
                },
            ],
        }];
        let manifest = ManifestEnvelope {
            protocol_version: 1,
            components: vec![],
            enums,
            inline_structs: vec![],
            tagged_unions: vec![],
        };
        let code = generate(&manifest);
        assert!(code.contains("class ButtonVariant(Enum):"));
        assert!(code.contains("PRIMARY = \"primary\""));
        assert!(code.contains("SECONDARY = \"secondary\""));
    }

    #[test]
    fn generates_component() {
        let components = vec![ComponentEntry {
            tag: 0x0200,
            name: "Text".into(),
            section: "4 Data Display".into(),
            fields: vec![
                FieldEntry {
                    key: 0,
                    name: "content".into(),
                    wire: "tstr".into(),
                    required: true,
                    default: None,
                },
                FieldEntry {
                    key: 1,
                    name: "style".into(),
                    wire: "Option<Enum<TextStyle>>".into(),
                    required: false,
                    default: None,
                },
            ],
            handlers: vec!["on_click".into()],
        }];
        let manifest = ManifestEnvelope {
            protocol_version: 1,
            components,
            enums: vec![],
            inline_structs: vec![],
            tagged_unions: vec![],
        };
        let code = generate(&manifest);
        assert!(code.contains("class Text(Component):"));
        assert!(code.contains("TAG: int = 0x0200"));
        assert!(code.contains("content: str"));
        assert!(code.contains("style: Optional[TextStyle] = None"));
        assert!(code.contains("HANDLER_ON_CLICK: str = \"on_click\""));
    }

    #[test]
    fn full_manifest_generates() {
        let manifest = build_manifest();
        let code = generate(&manifest);
        assert!(!code.is_empty());
        assert!(code.contains("from dataclasses import dataclass, field"));
        for c in &manifest.components {
            assert!(
                code.contains(&format!("class {}(Component):", c.name)),
                "missing component class: {}",
                c.name
            );
        }
        for e in &manifest.enums {
            assert!(
                code.contains(&format!("class {}(Enum):", e.name)),
                "missing enum: {}",
                e.name
            );
        }
    }

    #[test]
    fn wire_type_mapping() {
        assert_eq!(wire_to_python("tstr"), "str");
        assert_eq!(wire_to_python("u32"), "int");
        assert_eq!(wire_to_python("f64"), "float");
        assert_eq!(wire_to_python("bool"), "bool");
        assert_eq!(wire_to_python("Option<tstr>"), "Optional[str]");
        assert_eq!(wire_to_python("Option<u32>"), "Optional[int]");
        assert_eq!(wire_to_python("Array<tstr>"), "List[str]");
        assert_eq!(wire_to_python("Enum<ButtonVariant>"), "ButtonVariant");
        assert_eq!(wire_to_python("Option<Enum<Tone>>"), "Optional[Tone]");
        assert_eq!(wire_to_python("Inline<Handler>"), "Handler");
        assert_eq!(wire_to_python("ComponentRef<Button>"), "Component");
        assert_eq!(wire_to_python("Array<Component>"), "List[Component]");
        assert_eq!(wire_to_python("BindRef"), "BindRef");
        assert_eq!(wire_to_python("StatePath"), "StatePath");
        assert_eq!(wire_to_python("Value"), "Any");
        assert_eq!(wire_to_python("CborMap"), "Any");
    }

    #[test]
    fn screaming_snake_conversion() {
        assert_eq!(rust_name_to_screaming_snake("Primary"), "PRIMARY");
        assert_eq!(rust_name_to_screaming_snake("OnClick"), "ON_CLICK");
        assert_eq!(
            rust_name_to_screaming_snake("SameOrigin"),
            "SAME_ORIGIN"
        );
        assert_eq!(rust_name_to_screaming_snake("X"), "X");
    }
}
