# =============================================================================
# File: executor/run_pytest.py — executes api/security/unit items: writes the
# untrusted script + a generated conftest.py (network guard, base_url and
# api_client fixtures) into the item workdir and runs pytest with
# pytest-json-report in a killable subprocess.
# =============================================================================

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

from .junit import ItemOutcome, outcome_from_report

if TYPE_CHECKING:
    from .job import ItemContext

# The conftest never embeds the secret — it reads TF_* env vars at runtime, so
# nothing sensitive is ever written to disk.
CONFTEST_TEMPLATE = '''\
# Generated by TentaFlow test-runner — do not edit. Installs the network guard
# before any test module is imported and exposes the standard fixtures.
import json
import os

import httpx
import pytest

from executor.sandbox_net import HostNotAllowed, check_host, install_socket_guard

install_socket_guard()


def _reject_disallowed(request: httpx.Request) -> None:
    check_host(request.url.host or "")


@pytest.fixture(scope="session")
def base_url() -> str:
    return os.environ.get("TF_BASE_URL", "")


@pytest.fixture(scope="session")
def api_client(base_url):
    auth_type = os.environ.get("TF_AUTH_TYPE", "none")
    secret = os.environ.get("TF_SECRET", "")
    headers = {}
    auth = None
    if auth_type == "bearer" and secret:
        headers["Authorization"] = "Bearer " + secret
    elif auth_type == "api_key" and secret:
        headers["X-API-Key"] = secret
    elif auth_type == "basic" and secret:
        user, _, password = secret.partition(":")
        auth = httpx.BasicAuth(user, password)
    try:
        headers.update(json.loads(os.environ.get("TF_EXTRA_HEADERS", "{}")))
    except ValueError:
        pass
    timeout = float(os.environ.get("TF_HTTP_TIMEOUT_SECS", "30"))
    client = httpx.Client(
        base_url=base_url,
        headers=headers,
        auth=auth,
        timeout=timeout,
        event_hooks={"request": [_reject_disallowed]},
    )
    yield client
    client.close()
'''


def run(ctx: "ItemContext") -> ItemOutcome:
    script = ctx.content.get("script")
    if not isinstance(script, str) or not script.strip():
        return ItemOutcome(status="error", message="item content has no script")

    (ctx.workdir / "conftest.py").write_text(CONFTEST_TEMPLATE, encoding="utf-8")
    (ctx.workdir / "test_tf_item.py").write_text(script, encoding="utf-8")

    extra_env = {}
    timeout_ms = ctx.config.get("timeout_ms") or ctx.content.get("config", {}).get("timeout_ms")
    if isinstance(timeout_ms, (int, float)) and timeout_ms > 0:
        extra_env["TF_HTTP_TIMEOUT_SECS"] = str(max(1.0, float(timeout_ms) / 1000.0))
    if ctx.kind == "unit":
        # Unit items must not touch the network at all — even localhost.
        extra_env["TF_NET_BLOCK_ALL"] = "1"

    report_path = ctx.workdir / "report.json"
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        "test_tf_item.py",
        "-q",
        "-p",
        "no:cacheprovider",
        "--json-report",
        f"--json-report-file={report_path}",
    ]
    sub = ctx.run(cmd, log_name="console.log", extra_env=extra_env)
    return outcome_from_report(report_path, sub, ctx.timeout_secs)
