# =============================================================================
# File: executor/run_ui.py — executes ui items: pytest + Playwright sync API in
# a subprocess. The generated conftest provides `page`/`base_url` fixtures,
# aborts browser requests to hosts outside the allowlist via context.route,
# and captures a full-page screenshot + trace into the artifacts dir on
# failure.
# =============================================================================

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

from .junit import ItemOutcome, outcome_from_report

if TYPE_CHECKING:
    from .job import ItemContext

UI_CONFTEST_TEMPLATE = '''\
# Generated by TentaFlow test-runner — do not edit. Provides Playwright
# fixtures with network allowlisting, tracing and failure screenshots.
import os
import re
from pathlib import Path
from urllib.parse import urlparse

import pytest

from executor.sandbox_net import HostNotAllowed, check_host, install_socket_guard
from playwright.sync_api import sync_playwright

install_socket_guard()

_ARTIFACTS = Path(os.environ["TF_ARTIFACTS_DIR"])
_TIMEOUT_MS = int(os.environ.get("TF_UI_TIMEOUT_MS", "30000"))
_HEADED = os.environ.get("TF_UI_HEADED") == "1"
_VIEWPORT = {
    "width": int(os.environ.get("TF_UI_VIEWPORT_WIDTH", "1280")),
    "height": int(os.environ.get("TF_UI_VIEWPORT_HEIGHT", "720")),
}


def _route_guard(route):
    url = route.request.url
    scheme = url.split(":", 1)[0].lower()
    # about/blob/data URLs are page-internal, they carry no network egress.
    if scheme in ("about", "blob", "data"):
        route.continue_()
        return
    try:
        check_host(urlparse(url).hostname or "")
    except HostNotAllowed:
        route.abort()
        return
    route.continue_()


@pytest.fixture(scope="session")
def base_url() -> str:
    return os.environ.get("TF_BASE_URL", "")


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    # Stash per-phase reports on the node so the page fixture can detect
    # failures during teardown and persist screenshot + trace artifacts.
    outcome = yield
    rep = outcome.get_result()
    setattr(item, "tf_rep_" + rep.when, rep)


@pytest.fixture
def page(request):
    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            headless=not _HEADED,
            args=["--disable-gpu", "--disable-dev-shm-usage"],
        )
        context = browser.new_context(viewport=_VIEWPORT)
        context.set_default_timeout(_TIMEOUT_MS)
        context.route("**/*", _route_guard)
        context.tracing.start(screenshots=True, snapshots=True, sources=False)
        page = context.new_page()
        try:
            yield page
        finally:
            safe = re.sub(r"[^a-zA-Z0-9._-]+", "_", request.node.name)[:80]
            failed = any(
                getattr(request.node, "tf_rep_" + when, None) is not None
                and getattr(request.node, "tf_rep_" + when).failed
                for when in ("setup", "call", "teardown")
            )
            if failed:
                try:
                    page.screenshot(path=str(_ARTIFACTS / (safe + ".png")), full_page=True)
                except Exception:
                    pass
                try:
                    context.tracing.stop(path=str(_ARTIFACTS / (safe + ".trace.zip")))
                except Exception:
                    pass
            else:
                context.tracing.stop()
            context.close()
            browser.close()
'''


def run(ctx: "ItemContext") -> ItemOutcome:
    script = ctx.content.get("script")
    if not isinstance(script, str) or not script.strip():
        return ItemOutcome(status="error", message="item content has no script")

    (ctx.workdir / "conftest.py").write_text(UI_CONFTEST_TEMPLATE, encoding="utf-8")
    (ctx.workdir / "test_tf_item.py").write_text(script, encoding="utf-8")

    ui_config = ctx.content.get("config") or ctx.config or {}
    extra_env = {}
    timeout_ms = ui_config.get("timeout_ms")
    if isinstance(timeout_ms, (int, float)) and timeout_ms > 0:
        extra_env["TF_UI_TIMEOUT_MS"] = str(int(timeout_ms))
    if ui_config.get("headed") is True:
        extra_env["TF_UI_HEADED"] = "1"
    viewport = ui_config.get("viewport")
    if isinstance(viewport, dict):
        if isinstance(viewport.get("width"), (int, float)):
            extra_env["TF_UI_VIEWPORT_WIDTH"] = str(int(viewport["width"]))
        if isinstance(viewport.get("height"), (int, float)):
            extra_env["TF_UI_VIEWPORT_HEIGHT"] = str(int(viewport["height"]))

    report_path = ctx.workdir / "report.json"
    cmd = [
        sys.executable,
        "-m",
        "pytest",
        "test_tf_item.py",
        "-q",
        "-p",
        "no:cacheprovider",
        "--json-report",
        f"--json-report-file={report_path}",
    ]
    sub = ctx.run(cmd, log_name="console.log", extra_env=extra_env)
    return outcome_from_report(report_path, sub, ctx.timeout_secs)
